### ISSUE TITLE
[Issue] Console error spam 

### ISSUE THREAD

**Issue by ShayneBauzon** [GC-spigot/AdvancedEnchantments#1200]
**Describe the bug**
[ERROR] .... Could not pass event BlockBreakEvent to AdvancedEnchantments v7.9.8

java.lang.NullPointerException: null

at n3kas.ae.utils.AManager.replaceInList(AManager.java:355) ~[?:?]

at n3kas.ae.features.souls.SoulsAPI.addSouls(SoulsAPI.java:64) ~[?:?]

at n3kas.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:97) ~[?:?]

at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor810.execute(Unknown Source) ~[?:?]

at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-243]

at org.bukkit.plugin.EventExecutor$$Lambda$2855.0000000059630F60.execute(Unknown Source) ~[?:?]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-243]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-243]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.PlayerInteractManager.breakBlock(PlayerInteractManager.java:306) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:265) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:239) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1307) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.PlayerConnectionUtils$$Lambda$4118.000000005C09ACB0.run(Unknown Source) ~[?:?]

at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-243]

at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-243]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/64379231/85852456-37cf1980-b7e3-11ea-9bae-12c8cf9d9520.png)

**Server Information (please complete the following information):**
 - Minecraft Version 1.14.4 [e.g. PaperSpigot 1.14.4]
- Plugin Version [7.9.11]

**Comment by GC-spigot** [comment]
That doesn't happen with 7.9.11 and only with 7.9.8 which is what you're using
