### ISSUE TITLE
[Issue] Error

### ISSUE THREAD

**Issue by shocgod** [GC-spigot/AdvancedEnchantments#1226]
[11:56:26 WARN]: java.io.IOException: Server returned HTTP response code: 522 for URL: http://servers.advancedmarket.co/ae/enchantments/share.php?list=true
[11:56:26 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
[11:56:26 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
[11:56:26 WARN]:        at n3kas.ae.handlers.netsharing.MarketInventory.readUrl(MarketInventory.java:367)
[11:56:26 WARN]:        at n3kas.ae.handlers.netsharing.MarketInventory.cache(MarketInventory.java:217)
[11:56:26 WARN]:        at n3kas.ae.handlers.netsharing.MarketInventory.access$0(MarketInventory.java:213)
[11:56:26 WARN]:        at n3kas.ae.handlers.netsharing.MarketInventory$1.run(MarketInventory.java:48)
[11:56:26 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[11:56:26 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[11:56:26 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:56:26 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:56:26 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:56:26 WARN]:        at java.lang.Thread.run(Thread.java:748)
[11:56:26 WARN]: [AdvancedEnchantments] Failed to connect to remote server, is your firewall configured properly?

**Comment by GC-spigot** [comment]
Fixed
