### ISSUE TITLE
[Issue] InvocationTargetException triggered by api calls

### ISSUE THREAD

**Issue by emanondev** [GC-spigot/AdvancedEnchantments#1242]
**Describe the bug**
i get InvocationTargetException when i  use AEAPI.getEnchantmentsOnItem()

[11:47:32] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[11:47:32] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
[11:47:32] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:47:32] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[11:47:32] [Server thread/WARN]: 	at n3kas.ae.utils.nbt.backend.ReflectionMethod.run(ReflectionMethod.java:97)
[11:47:32] [Server thread/WARN]: 	at n3kas.ae.utils.nbt.backend.NBTItem.getCompound(NBTItem.java:18)
[11:47:32] [Server thread/WARN]: 	at n3kas.ae.utils.nbt.backend.NBTReflectionUtil.getKeys(NBTReflectionUtil.java:287)
[11:47:32] [Server thread/WARN]: 	at n3kas.ae.utils.nbt.backend.NBTCompound.getKeys(NBTCompound.java:147)
[11:47:32] [Server thread/WARN]: 	at n3kas.ae.utils.nbt.NBTapi.getEnchantments(NBTapi.java:194)
[11:47:32] [Server thread/WARN]: 	at n3kas.ae.api.AEAPI.getEnchantmentsOnItem(AEAPI.java:217)
[11:47:32] [Server thread/WARN]: 	at emanondev.arcanealtar.enchants.EnchantManager.grabEnchants(EnchantManager.java:338)

**To Reproduce**
HashMap<String, Integer> map;
map = AEAPI.getEnchantmentsOnItem(equip.getHelmet());

**Server Information (please complete the following information):**
 - Minecraft Version Tuinity 1.15.2
- Plugin Version [7.9.14]

**Comment by GC-spigot** [comment]
Seems like the item was invalid, will catch errors and return empty list.

**Comment by emanondev** [comment]
[13:40:02] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[13:40:02] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
[13:40:02] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:40:02] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[13:40:02] [Server thread/WARN]: 	at n3kas.ae.utils.nbt.backend.ReflectionMethod.run(ReflectionMethod.java:97)
[13:40:02] [Server thread/WARN]: 	at n3kas.ae.utils.nbt.backend.NBTItem.getCompound(NBTItem.java:18)
[13:40:02] [Server thread/WARN]: 	at n3kas.ae.utils.nbt.backend.NBTReflectionUtil.getKeys(NBTReflectionUtil.java:287)
[13:40:02] [Server thread/WARN]: 	at n3kas.ae.utils.nbt.backend.NBTCompound.getKeys(NBTCompound.java:147)
[13:40:02] [Server thread/WARN]: 	at n3kas.ae.utils.nbt.NBTapi.getEnchantments(NBTapi.java:194)
[13:40:02] [Server thread/WARN]: 	at n3kas.ae.api.AEAPI.getEnchantmentsOnItem(AEAPI.java:217)
[13:40:02] [Server thread/WARN]: 	at emanondev.arcanealtar.enchants.EnchantManager.grabEnchants(EnchantManager.java:345)
[13:40:02] [Server thread/WARN]: 	at emanondev.arcanealtar.enchants.EnchantManager.event(EnchantManager.java:225)
[13:40:02] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[13:40:02] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:40:02] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:40:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:40:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:240)
[13:40:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1008)
[13:40:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:990)
[13:40:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleNonLivingEntityDamageEvent(CraftEventFactory.java:1063)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityArmorStand.damageEntity(EntityArmorStand.java:469)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityLiving.entityBaseTick(EntityLiving.java:250)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.Entity.tick(Entity.java:444)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityLiving.tick(EntityLiving.java:2347)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.EntityArmorStand.tick(EntityArmorStand.java:634)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:1264)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.World.a(World.java:903)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:968)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1387)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:432)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1239)
[13:40:02] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[13:40:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[13:40:02] [Server thread/WARN]: Caused by: java.lang.NullPointerException

i check if the item is null or air before calling the api, item is valid

**Comment by GC-spigot** [comment]
I’m not sure what causes this, not using my nbt api but someone else’s, will ask them
