### ISSUE TITLE
[Issue] java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.IChatBaseComponent

### ISSUE THREAD

**Issue by GamingWubba93** [GC-spigot/AdvancedEnchantments#1260]
**Describe the bug**
On server start, the console fires the following issue related to java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.IChatBaseComponent

**To Reproduce**
N/A cause all I did was add the latest version to my plugins.

**Console Error**
```
[18:34:31] [Server thread/ERROR]: Error occurred while enabling AdvancedEnchantments v7.9.31 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/IChatBaseComponent
at n3kas.ae.utils.AF.getStringList(AF.java:40) ~[?:?]
at n3kas.ae.Core.onEnable(Core.java:375) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.IChatBaseComponent
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]
at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
... 11 more
```

**Server Information**
 - Minecraft Version Spigot 1.15.2
- Plugin Version AdvancedEnchantments v7.9.31

**Comment by GamingWubba93** [comment]
Issue has disappeared upon adding AdvancedEnchantments v7.9.32 to my server plugins. Issue closed.
