### ISSUE TITLE
[Issue] NumberFormatException: <math>5 * (1.0 + 0.25 * 2)</math> console spam

### ISSUE THREAD

**Issue by WolverStones** [GC-spigot/AdvancedEnchantments#1433]
Error: 
https://pastebin.com/ekx3ZpV9

**Server Information:**
 - Minecraft Version git-Paper-183 (MC: 1.16.2)
- Plugin Version 8.0.0-Pre1.6

**Comment by GC-spigot** [comment]
Fixed

**Comment by WolverStones** [comment]
@GC-spigot

I tried to use the latest version and this show in console:

```
[13:48:58 INFO]: [AdvancedEnchantments] Couldn't do a math evaluation for EXP:<math>(5 * (1.0 + 0.25 * 2))*2.0</math> %victim% String
[13:48:58 WARN]: java.lang.NumberFormatException: For input string: "(5 * (1.0 + 0.25 * 2))*2.0"
[13:48:58 WARN]: at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
[13:48:58 WARN]: at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[13:48:58 WARN]: at java.lang.Double.parseDouble(Double.java:538)
[13:48:58 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:752)
[13:48:58 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:116)
[13:48:58 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:254)
[13:48:58 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:123)
[13:48:58 WARN]: at n3kas.ae.enchanthandler.enchanttypes.KILL_MOB.onMobDeath(KILL_MOB.java:53)
[13:48:58 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1189.execute(Unknown Source)
[13:48:58 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:48:58 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:48:58 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:48:58 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:48:58 WARN]: at com.bgsoftware.wildstacker.listeners.L.L(mj:299)
[13:48:58 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[13:48:58 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[13:48:58 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[13:48:58 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375)
[13:48:58 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[13:48:58 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[13:48:58 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[13:48:58 WARN]: at java.lang.Thread.run(Thread.java:748)
``` 
git-Paper-186 (MC: 1.16.2) 

8.0.0-Pre2.3
