### ISSUE TITLE
[Issue]Could not pass event PrepareItemEnchantEvent to AdvancedEnchantments v8.0.0-Pre2.1 org.bukkit.event.EventException: null

### ISSUE THREAD

**Issue by viocu** [GC-spigot/AdvancedEnchantments#1440]
**Describe the bug**
`[02:22:18] [Server thread/ERROR]: Could not pass event PrepareItemEnchantEvent to AdvancedEnchantments v8.0.0-Pre2.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerEnchantTable.lambda$0(ContainerEnchantTable.java:183) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess.lambda$0(ContainerAccess.java:59) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess$2.a(ContainerAccess.java:46) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess.a(ContainerAccess.java:58) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerEnchantTable.a(ContainerEnchantTable.java:112) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerEnchantTable$1.update(ContainerEnchantTable.java:45) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.InventorySubcontainer.setItem(InventorySubcontainer.java:183) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerEnchantTable.lambda$1(ContainerEnchantTable.java:261) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess.lambda$0(ContainerAccess.java:59) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess$2.a(ContainerAccess.java:46) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess.a(ContainerAccess.java:58) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerEnchantTable.a(ContainerEnchantTable.java:230) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2301) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PacketPlayInEnchantItem.a(SourceFile:22) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PacketPlayInEnchantItem.a(SourceFile:8) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
	at n3kas.ae.handlers.enchantTable.EnchantTableEvent.onPreEnchant(EnchantTableEvent.java:102) ~[AdvancedEnchantments-8.0.0-Pre2.1.jar:?]
	at sun.reflect.GeneratedMethodAccessor1056.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	... 30 more
[02:22:18] [Server thread/ERROR]: Could not pass event PrepareItemEnchantEvent to AdvancedEnchantments v8.0.0-Pre2.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerEnchantTable.lambda$0(ContainerEnchantTable.java:183) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess.lambda$0(ContainerAccess.java:59) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess$2.a(ContainerAccess.java:46) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess.a(ContainerAccess.java:58) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerEnchantTable.a(ContainerEnchantTable.java:112) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerEnchantTable.lambda$1(ContainerEnchantTable.java:301) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess.lambda$0(ContainerAccess.java:59) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess$2.a(ContainerAccess.java:46) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerAccess.a(ContainerAccess.java:58) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.ContainerEnchantTable.a(ContainerEnchantTable.java:230) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:2301) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PacketPlayInEnchantItem.a(SourceFile:22) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PacketPlayInEnchantItem.a(SourceFile:8) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:943) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:936) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:920) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:852) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.NullPointerException
	at n3kas.ae.handlers.enchantTable.EnchantTableEvent.onPreEnchant(EnchantTableEvent.java:102) ~[AdvancedEnchantments-8.0.0-Pre2.1.jar:?]
	at sun.reflect.GeneratedMethodAccessor1056.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.1.jar:git-Spigot-9639cf7-4b9bc9d]
	... 28 more`
**To Reproduce**
A way to reproduce the video

I'm not even sure. it just triggers randomly. Sometimes it'll trigger with /enchant, sometimes just out of the blue.

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version [e.g. PaperSpigot 1.8.8]

minecraft version 1.16.1/Spigot 1.16.1
- Plugin Version [e.g. 6.7.8]
AdvancedEnchantments v8.0.0-Pre2.1

If you need more info, lmk. I have no idea what this error is or how to fix it. Advice would be great!

**Comment by GC-spigot** [comment]
Fixed
