### ISSUE TITLE
[Issue] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

### ISSUE THREAD

**Issue by idani20** [GC-spigot/AdvancedEnchantments#1448]
Hello, im using AdvancedEnchantments on my hamachi server and in one hosted server and i'm getting an error message, plugin can't load.

`[01:44:42] [Craft Scheduler Thread - 13/WARN]: [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.
[01:44:42] [Craft Scheduler Thread - 13/INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v8.0.0-Pre2.8
[01:44:42] [Craft Scheduler Thread - 13/ERROR]: Error occurred (in the plugin loader) while disabling AdvancedEnchantments v8.0.0-Pre2.8 (Is it up to date?)
java.lang.IllegalStateException: PluginDisableEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[spigot116.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:370) ~[spigot116.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) [spigot116.jar:git-Spigot-0287a20-7560f5f]
        at n3kas.ae.Core$2.run(Core.java:700) [AdvancedEnchantments-8.0.0-Pre2.8.jar:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot116.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot116.jar:git-Spigot-0287a20-7560f5f]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
[01:44:42] [Craft Scheduler Thread - 13/ERROR]: Error occurred (in the plugin loader) while unregistering services for AdvancedEnchantments v8.0.0-Pre2.8 (Is it up to date?)
java.lang.IllegalStateException: ServiceUnregisterEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[spigot116.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.plugin.SimpleServicesManager.unregisterAll(SimpleServicesManager.java:100) ~[spigot116.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:513) [spigot116.jar:git-Spigot-0287a20-7560f5f]
        at n3kas.ae.Core$2.run(Core.java:700) [AdvancedEnchantments-8.0.0-Pre2.8.jar:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) [spigot116.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot116.jar:git-Spigot-0287a20-7560f5f]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_221]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]`

**Server Information (please complete the following information):**
 - Spigot 1.16.1
- Plugin Version [e.g. 6.7.8]
 2.8

**Comment by GC-spigot** [comment]
What is your spigot username?

**Comment by idani20** [comment]
> What is your spigot username?

astralcraft212

**Comment by ItzVoid1** [comment]
[03:00:14 WARN]: [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.

**Comment by ItzVoid1** [comment]
[03:04:06 INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v8.8.11
[03:04:07 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[03:04:11 INFO]: [AdvancedEnchantments] Loaded 7 armor sets.
[03:04:11 INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[03:04:12 INFO]: Running delayed init tasks
[03:04:12 INFO]: Done (8.659s)! For help, type "help"
[03:04:12 INFO]: Timings Reset
[03:04:12 WARN]: [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.
[03:04:12 INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v8.8.11

> Please help AdvancedEnchantments

@GC-spigot

**Comment by GC-spigot** [comment]
Make a ticket on the discord server.
