### ISSUE TITLE
[Issue] Could not pass NumberFormatException: For input string: "10 * (1.0 + 0.25 * 4)"

### ISSUE THREAD

**Issue by WolverStones** [GC-spigot/AdvancedEnchantments#1450]
**Describe the bug**
`[AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "10 * (1.0 + 0.25 * 4)"
[15:14:34 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:765)
[15:14:34 INFO]: [AdvancedEnchantments] Extra info: effect[EXP:10 * (1.0 + 0.25 * 4)]; enchant [inquisitive]; mc[116]; ae[8.0.0-Pre2.9]
[15:14:34 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.
[15:14:41 INFO]: [AdvancedEnchantments] Couldn't do a math evaluation for EXP:<math>10 * (1.0 + 0.25 * 4)</math> %victim% String
[15:14:41 WARN]: java.lang.NumberFormatException: For input string: "10 * (1.0 + 0.25 * 4)"
[15:14:41 WARN]: at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
[15:14:41 WARN]: at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[15:14:41 WARN]: at java.lang.Double.parseDouble(Double.java:538)
[15:14:41 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:765)
[15:14:41 WARN]: at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:116)
[15:14:41 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:254)
[15:14:41 WARN]: at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:123)
[15:14:41 WARN]: at n3kas.ae.enchanthandler.enchanttypes.KILL_MOB.onMobDeath(KILL_MOB.java:53)
[15:14:41 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1190.execute(Unknown Source)
[15:14:41 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[15:14:41 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[15:14:41 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[15:14:41 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[15:14:41 WARN]: at com.bgsoftware.wildstacker.listeners.L.L(mj:299)
[15:14:41 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[15:14:41 WARN]: at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:14:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[15:14:41 WARN]: at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375)
[15:14:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[15:14:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[15:14:41 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:14:41 WARN]: at java.lang.Thread.run(Thread.java:748)
[15:14:41 INFO]: [AdvancedEnchantments ERROR] Could not pass NumberFormatException: For input string: "10 * (1.0 + 0.25 * 4)"
[15:14:41 INFO]: [AdvancedEnchantments] Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:765)
[15:14:41 INFO]: [AdvancedEnchantments] Extra info: effect[EXP:10 * (1.0 + 0.25 * 4)]; enchant [inquisitive]; mc[116]; ae[8.0.0-Pre2.9]
[15:14:41 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.`

**Server Information (please complete the following information):**
 - Minecraft Version git-Paper-191 (MC: 1.16.3)
- Plugin Version 8.0.0-Pre2.9

**Comment by Coolfire02** [comment]
I'm pretty sure this is an issue because the code isn't reading an expression to begin with. Why not just do the calculation yourself and put it in as the number?

**Comment by myiume** [comment]
I ran into the same issue with the inquisitive default enchants that use the <math> tags. It's not parsing the expression as intended.
