### ISSUE TITLE
NPE on Tinkerer using dia sword

### ISSUE THREAD

**Issue by Scorpionvssub** [GC-spigot/AdvancedEnchantments#1480]
**Describe the bug**
Tinkerer throws NPE
`[17:07:03 WARN]: java.lang.NullPointerException
[17:07:03 WARN]: at n3kas.ae.features.tinkerer.TinkererFormula.getAmountForItem(TinkererFormula.java:35)
[17:07:03 WARN]: at n3kas.ae.features.tinkerer.TinkererInventory.onClick(TinkererInventory.java:301)
[17:07:03 WARN]: at n3kas.ae.globallisteners.InventoryClicks.onInvClix(InventoryClicks.java:36)
[17:07:03 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor576.execute(Unknown Source)
[17:07:03 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[17:07:03 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:07:03 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:07:03 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2427)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1202)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[17:07:03 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[17:07:03 WARN]: at java.lang.Thread.run(Thread.java:748)`

**To Reproduce**
enchant exactly as on image and try to add it in.

`slowpoke:
  display: '%group-color%Slowpoke'
  description: 'Travel very slow'
  applies-to: 'Armor'
  group: 'BAD'
  type: 'EFFECT_STATIC'
  applies:
    - 'ALL_ARMOR'
  levels:
    '1':
      effects:
        - 'POTION:SLOW:0 %victim%'
    '2':
      effects:
        - 'POTION:SLOW:1 %victim%'
    '3':
      effects:
        - 'POTION:SLOW:2 %victim%'
    '4':
      effects:
        - 'POTION:SLOW:3 %victim%'`

**Screenshots / Video**
![image](https://user-images.githubusercontent.com/12249763/94703925-a5896500-033f-11eb-8780-d8744946bb65.png)
1 sword, 

Edit:
 While the used enchant was put on a sword, it was also tested against armor(chestplate) same thing happend.

**Comment by GC-spigot** [comment]
Fixed
