### ISSUE TITLE
Item rename Tag Issue[Issue]

### ISSUE THREAD

**Issue by gyu6378** [GC-spigot/AdvancedEnchantments#1492]
Hi

First Issue

some issue with Item rename tags
can't use color codes with item rename tag

plugin version : 8.0.0-Pre7.1
my server version : 1.13.2 spigot

![2020-10-04_23 54 01](https://user-images.githubusercontent.com/72348517/95018811-eca78b00-069c-11eb-845e-ddd8ec6ec513.png)

![2020-10-04_23 54 00](https://user-images.githubusercontent.com/72348517/95018814-f0d3a880-069c-11eb-91f4-12c1ae35b526.png)

Second Issue

Error spam on 1.13.2 spigot

[22:01:54] [Server thread/INFO]: Failed to match 'CROSSBOW' material, check your configuration or use materials.txt to find needed material.
[22:01:54] [Server thread/INFO]: Further information has been pasted to console...
[22:01:54] [Server thread/WARN]: java.lang.IllegalArgumentException: Material cannot be null
[22:01:54] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[22:01:54] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:74)
[22:01:54] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:62)
[22:01:54] [Server thread/WARN]: 	at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:50)
[22:01:54] [Server thread/WARN]: 	at n3kas.ae.utils.AManager.matchMaterial(AManager.java:204)
[22:01:54] [Server thread/WARN]: 	at n3kas.ae.utils.AManager.matchMaterial(AManager.java:207)
[22:01:54] [Server thread/WARN]: 	at n3kas.ae.utils.AManager.matchMaterial(AManager.java:169)
[22:01:54] [Server thread/WARN]: 	at n3kas.ae.utils.AManager.isMaterialSimilar(AManager.java:87)
[22:01:54] [Server thread/WARN]: 	at n3kas.ae.enchanthandler.enchanttypes.BOW.onProjectileHitEvent(BOW.java:76)
[22:01:54] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1015.execute(Unknown Source)
[22:01:54] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[22:01:54] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[22:01:54] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66)
[22:01:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520)
[22:01:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104)
[22:01:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834)
[22:01:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:733)
[22:01:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:866)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1520)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity0(EntityHuman.java:904)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:993)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:817)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:704)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityArrow.b(EntityArrow.java:341)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityArrow.a(EntityArrow.java:284)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityArrow.tick(EntityArrow.java:209)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityTippedArrow.tick(EntityTippedArrow.java:85)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1561)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.g(World.java:1528)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1339)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
[22:01:54] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837)
[22:01:54] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by GC-spigot** [comment]
Color codes are controlled by your chat manager plugin

**Comment by gyu6378** [comment]
> Color codes are controlled by your chat manager plugin

what about error spam?
