### ISSUE TITLE
[Issue] NoCheatPlus issue with advancedenchantments error on console

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#1530]
**Describe the bug**
Errors are thrown on the console when having nocheatplus installed alongside advanced enchantments, can you at least provide a way to not connect them together, because your plugin is looking for nocheatplus for trench compatibility as I seen on updates, improve this feature please or at least suppress the warnings when the class is not found, ccuz the trench works anyway.
I have the errors here https://paste.dedimc.io/utibuxozek
[15:57:56 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v8.0.0-Pre11.1
java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/hooks/NCPExemptionManager
        at n3kas.ae.enchanthandler.hooks.anticheat.ExemptPlayer.forPlayer(ExemptPlayer.java:31) ~[?:?]
        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1209) ~[?:?]
        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:115) ~[?:?]
        at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:254) ~[?:?]
        at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:123) ~[?:?]
        at n3kas.ae.enchanthandler.enchanttypes.MINING.lambda$0(MINING.java:85) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_262]
        at n3kas.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:79) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor993.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-251]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-251]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-251]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:224) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1395) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
[15:57:56 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v8.0.0-Pre11.1
java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/hooks/NCPExemptionManager
        at n3kas.ae.enchanthandler.hooks.anticheat.ExemptPlayer.forPlayer(ExemptPlayer.java:31) ~[?:?]
        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1209) ~[?:?]
        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:115) ~[?:?]
        at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:254) ~[?:?]
        at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:123) ~[?:?]
        at n3kas.ae.enchanthandler.enchanttypes.MINING.lambda$0(MINING.java:85) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_262]
        at n3kas.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:79) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor993.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-251]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-251]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-251]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:224) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1395) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
[15:57:56 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v8.0.0-Pre11.1
java.lang.NoClassDefFoundError: fr/neatmonster/nocheatplus/hooks/NCPExemptionManager
        at n3kas.ae.enchanthandler.hooks.anticheat.ExemptPlayer.forPlayer(ExemptPlayer.java:31) ~[?:?]
        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1209) ~[?:?]
        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:115) ~[?:?]
        at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:254) ~[?:?]
        at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:123) ~[?:?]
        at n3kas.ae.enchanthandler.enchanttypes.MINING.lambda$0(MINING.java:85) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_262]
        at n3kas.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:79) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor993.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-251]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-251]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-251]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:324) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:283) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerInteractManager.a(PlayerInteractManager.java:224) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1395) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1264) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-251]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-251]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
**To Reproduce**
nothing just have them both installed.

**Screenshots / Video**

**Server Information (please complete the following information):**
 - Minecraft Version paper 1.16.3 build 251
- Plugin Version 8.0.0-Pre11.1

**Comment by antibitcoin** [comment]
I confirm error also still exist on 8.8.8-pre11.3
https://paste.dedimc.io/ogafixefud

**Comment by antibitcoin** [comment]
can you at least give us an option to disable exempt check with nocheatplus completely.

**Comment by GC-spigot** [comment]
What NoCheatPlus version are you running?

**Comment by antibitcoin** [comment]
This build
https://github.com/Updated-NoCheatPlus/NoCheatPlus/releases/tag/v1.5

**Comment by antibitcoin** [comment]
happening again
https://paste.dedimc.io/uqasapoxaq
I have noticed that it mainly happens if nocheatplus gets disabled than enabled, can u make an option where I don't want trench to be compatible with nocheatplus so we can just disable the checks on nocheat it self.

**Comment by GC-spigot** [comment]
Please use pastebin, it's the only proper platform that does not delete pastes instantly after
