### ISSUE TITLE
[Issue] Random error message

### ISSUE THREAD

**Issue by EkonC** [GC-spigot/AdvancedEnchantments#1551]
**Describe the bug**
This is an error I recently got in my console

**Error**
```
>.... [16:42:11 INFO]: AdvancedEnchantments caught an error with an action involving inventories
>.... [16:42:11 WARN]: java.lang.ArrayIndexOutOfBoundsException: -1
>.... [16:42:11 WARN]: at java.util.Arrays$ArrayList.get(Arrays.java:3841)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.NonNullList.get(SourceFile:46)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.PlayerInventory.getItem(PlayerInventory.java:541)
>.... [16:42:11 WARN]: at org.bukkit.craftbukkit.v1_16_R2.inventory.CraftInventory.getItem(CraftInventory.java:49)
>.... [16:42:11 WARN]: at n3kas.ae.enchanthandler.enchanttypes.HELD.onInvClick(HELD.java:35)
>.... [16:42:11 WARN]: at n3kas.ae.globallisteners.InventoryClicks.onInvClix(InventoryClicks.java:38)
>.... [16:42:11 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1047.execute(Unknown Source)
>.... [16:42:11 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [16:42:11 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [16:42:11 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [16:42:11 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2437)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:32)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.PacketPlayInWindowClick.a(SourceFile:10)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1202)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
>.... [16:42:11 WARN]: at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [16:42:11 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Server Information:**
- Server Version: [Paper-253 1.16.3]
- Plugin Version: [8.0.0-Pre12.4]

**Comment by GC-spigot** [comment]
Fixed
