### ISSUE TITLE
help

### ISSUE THREAD

**Issue by steynvaart** [GC-spigot/AdvancedEnchantments#1556]
ERROR]: Error occurred while enabling AdvancedEnchantments v8.0.0-Pre12.6 (Is it up to date?)
java.lang.NoClassDefFoundError: com/bgsoftware/wildstacker/api/WildStackerAPI
        at n3kas.ae.enchanthandler.hooks.CheckEnabled.init(CheckEnabled.java:30) ~[?:?]
        at n3kas.ae.enchanthandler.hooks.CheckEnabled.<init>(CheckEnabled.java:24) ~[?:?]
        at n3kas.ae.Core.onEnable(Core.java:455) ~[?:?]
on what side is the issue 
thanks

**Comment by GC-spigot** [comment]
Do you have an outdated WildStacker plugin?
