### ISSUE TITLE
[Issue] Could not pass event ArmorEquipEvent to AdvancedEnchantments

### ISSUE THREAD

**Issue by Kaisiq** [GC-spigot/AdvancedEnchantments#1571]
**Describe the bug**

A specific player joins in the game and the moment he joins this error appears on the console, the player says he has very high ping. I do not know if it is internet speed related or code related, so im posting this here.

[06:24:40] [Server thread/ERROR]: Could not pass event ArmorEquipEvent to AdvancedEnchantments v8.0.0-Pre15.3
java.lang.NullPointerException: null
	at n3kas.ae.enchanthandler.enchanttypes.EFFECT_STATIC.lambda$0(EFFECT_STATIC.java:149) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_272]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361) ~[?:1.8.0_272]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_272]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_272]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_272]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_272]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152) ~[?:1.8.0_272]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_272]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531) ~[?:1.8.0_272]
	at n3kas.ae.enchanthandler.enchanttypes.EFFECT_STATIC.onArmorChange(EFFECT_STATIC.java:149) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor435.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-204]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-204]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-204]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-204]
	at n3kas.ae.globallisteners.listeners.JoinEvent.onPlayerJoin(JoinEvent.java:25) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor467.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-204]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-204]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-204]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.PlayerList.postChunkLoadJoin(PlayerList.java:273) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.PlayerList.lambda$null$1(PlayerList.java:220) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.PlayerConnection.tick(PlayerConnection.java:154) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.NetworkManager.a(NetworkManager.java:385) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.ServerConnection.c(ServerConnection.java:145) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1383) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-204]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-1.16.3]
- Plugin Version: [e.g. 8.0.0 - Pre 15.3]

**Comment by Kaisiq** [comment]
[08:39:14] [Server thread/INFO]: lol was slain by Piglin

The same error appeared after a player was killed by a Piglin

**Comment by GC-spigot** [comment]
Fixed
