### ISSUE TITLE
[Issue] Plugin is not loading at all

### ISSUE THREAD

**Issue by useremre** [GC-spigot/AdvancedEnchantments#1611]
[05:24:12] [Server thread/INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v8.0.0-Pre14.1
[05:24:13] [Server thread/WARN]: java.lang.IllegalArgumentException: No enum constant n3kas.ae.features.sets.enums.SetPiece.LEGGİNGS
[05:24:13] [Server thread/WARN]: 	at java.lang.Enum.valueOf(Unknown Source)
[05:24:13] [Server thread/WARN]: 	at n3kas.ae.features.sets.enums.SetPiece.valueOf(SetPiece.java:1)
[05:24:13] [Server thread/WARN]: 	at n3kas.ae.features.sets.instances.ArmorSet.initSet(ArmorSet.java:64)
[05:24:13] [Server thread/WARN]: 	at n3kas.ae.features.sets.instances.ArmorSet.<init>(ArmorSet.java:54)
[05:24:13] [Server thread/WARN]: 	at n3kas.ae.features.sets.SetsManager.readSets(SetsManager.java:50)
[05:24:13] [Server thread/WARN]: 	at n3kas.ae.features.sets.SetsManager.<init>(SetsManager.java:40)
[05:24:13] [Server thread/WARN]: 	at n3kas.ae.Core.baseFiles(Core.java:229)
[05:24:13] [Server thread/WARN]: 	at n3kas.ae.Core.onEnable(Core.java:400)
[05:24:13] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[05:24:13] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[05:24:13] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[05:24:13] [Server thread/WARN]: 	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
[05:24:13] [Server thread/WARN]: 	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114)
[05:24:13] [Server thread/WARN]: 	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
[05:24:13] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[05:24:13] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[05:24:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761)
[05:24:13] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:723)
[05:24:13] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:470)
[05:24:13] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:432)
[05:24:13] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182)
[05:24:13] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971)
[05:24:13] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[05:24:13] [Server thread/INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[05:24:13] [Server thread/ERROR]: Error occurred while enabling AdvancedEnchantments v8.0.0-Pre14.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant n3kas.ae.handlers.enchantTable.PriceLevel.MİDDLE
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_271]
	at n3kas.ae.handlers.enchantTable.PriceLevel.valueOf(PriceLevel.java:1) ~[?:?]
	at n3kas.ae.handlers.enchantTable.EnchantTableHandler.<init>(EnchantTableHandler.java:41) ~[?:?]
	at n3kas.ae.Core.baseFiles(Core.java:233) ~[?:?]
	at n3kas.ae.Core.onEnable(Core.java:400) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-389]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-389]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-389]
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
	at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) ~[?:?]
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-389]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-389]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:761) ~[patched_1.15.2.jar:git-Paper-389]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:723) ~[patched_1.15.2.jar:git-Paper-389]
	at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:470) ~[patched_1.15.2.jar:git-Paper-389]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:432) ~[patched_1.15.2.jar:git-Paper-389]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1182) ~[patched_1.15.2.jar:git-Paper-389]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:971) ~[patched_1.15.2.jar:git-Paper-389]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[05:24:13] [Server thread/INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v8.0.0-Pre14.1

**Comment by GC-spigot** [comment]
Update
