### ISSUE TITLE
[Issue] Null Error

### ISSUE THREAD

**Issue by Shoutgun21** [GC-spigot/AdvancedEnchantments#1625]
**Describe the bug**
Everytime I try to Enchant Something on a server it comes up with a strange Error Message in the Console and the Item doesn't enchant

**To Reproduce**
Whenever I try to enchant something

**Screenshots / Video**
[04.01 06:29:02] [Server] [ERROR] Could not pass event InventoryClickEvent to AdvancedEnchantments v8.0.0-Pre17.1
[04.01 06:29:02] [Server] java.lang.NullPointerExceptionnull
[04.01 06:29:02] [Server] 	at java.util.ArrayList.addAll(ArrayList.java:701) ~[?:?]
[04.01 06:29:02] [Server] 	at n3kas.ae.api.AEAPI.applyEnchant(AEAPI.java:357) ~[?:?]
[04.01 06:29:02] [Server] 	at n3kas.ae.globallisteners.listeners.ClickListener.onClicks(ClickListener.java:770) ~[?:?]
[04.01 06:29:02] [Server] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor33.execute(Unknown Source) ~[?:?]
[04.01 06:29:02] [Server] 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2540) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1082) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-386]
[04.01 06:29:02] [Server] 	at java.lang.Thread.run(Thread.java:834) [?:?]

**Server Information (please complete the following information):**
- Server Version: Paperspigot-1.16.4
- Plugin Version: 8.0.0-Pre17.1

**Comment by GC-spigot** [comment]
Update
