### ISSUE TITLE
[Issue]weird null enchants

### ISSUE THREAD

**Issue by Doggggeh** [GC-spigot/AdvancedEnchantments#1681]
**Describe the bug**

**To Reproduce**
A way to reliability reproduce the bug.

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.
![image](https://user-images.githubusercontent.com/69886621/107132746-ca1ccb80-6935-11eb-918a-6e06c4de455d.png)

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.8.8]
- Plugin Version: [e.g. 6.7.8]

**Comment by Doggggeh** [comment]
[01:41:43 ERROR]: Could not pass event EnchantItemEvent to AdvancedEnchantments v8.0.0-Pre19.1
java.lang.NullPointerException: null
        at n3kas.ae.items.TransmogScroll.applyTransmog(TransmogScroll.java:155) ~[?:?]
        at n3kas.ae.api.AEAPI.applyEnchant(AEAPI.java:390) ~[?:?]
        at n3kas.ae.api.AEAPI.applyEnchant(AEAPI.java:325) ~[?:?]
        at gc.ae.enchantmentTable.EnchantmentTableClick.onEnchant(EnchantmentTableClick.java:83) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor776.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-443]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-443]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-443]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.ContainerEnchantTable.lambda$a$1(ContainerEnchantTable.java:246) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.ContainerAccess.lambda$a$0(ContainerAccess.java:59) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.ContainerAccess$2.a(ContainerAccess.java:46) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.ContainerAccess.a(ContainerAccess.java:58) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.ContainerEnchantTable.a(ContainerEnchantTable.java:230) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2664) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.PacketPlayInEnchantItem.a(SourceFile:22) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.PacketPlayInEnchantItem.a(SourceFile:8) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Paper-443]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-443]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]

**Comment by GC-spigot** [comment]
Issue with enchantment's group
