### ISSUE TITLE
Error occurred while enabling AdvancedEnchantments v8.0.0-Pre19.1 (Is it up to date?)

### ISSUE THREAD

**Issue by HxFreeZ** [GC-spigot/AdvancedEnchantments#1686]
While starting the Server i get this error

Error occurred while enabling AdvancedEnchantments v8.0.0-Pre19.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at n3kas.ae.Core.onEnable(Core.java:591) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:480) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:426) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:205) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:786) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:155) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[server_bukkit_1.16.4.jar:git-Bukkit-3af81c7]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_171]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_171]
        ... 11 more

**Comment by GC-spigot** [comment]
Use Spigot not Bukkit
