### ISSUE TITLE
[Issue] Trench bug

### ISSUE THREAD

**Issue by gwrijasdf** [GC-spigot/AdvancedEnchantments#1750]
**Describe the bug**
Sometimes errors appear when using and mining trench effect.

**To Reproduce**
trench on the pickaxe and break down the tree, and it will be triggered.

**Screenshots / Video**

this is console log: 
`[14:30:22 WARN]: java.lang.NullPointerException
[14:30:22 WARN]:        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:1919)
[14:30:22 WARN]:        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1324)
[14:30:22 WARN]:        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:121)
[14:30:22 WARN]:        at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:261)
[14:30:22 WARN]:        at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:126)
[14:30:22 WARN]:        at n3kas.ae.enchanthandler.enchanttypes.MINING.lambda$onBlockBreak$0(MINING.java:90)
[14:30:22 WARN]:        at java.util.ArrayList.forEach(Unknown Source)
[14:30:22 WARN]:        at n3kas.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:84)
[14:30:22 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor3541.execute(Unknown Source)
[14:30:22 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[14:30:22 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[14:30:22 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[14:30:22 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:357)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:310)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:245)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1473)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1161)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005)
[14:30:22 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:179)
[14:30:22 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:30:22 INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException:
[14:30:22 INFO]: [AdvancedEnchantments]    Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:1919)
[14:30:22 INFO]: [AdvancedEnchantments]    Extra info: effect[TRENCH:3]; enchant [detonate]; mc[116]; ae[8.0.0-Pre20.6]
[14:30:22 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.`

In-game error:
`Failed to parse effect 'TRENCH' for enchant 'atomicdetonate' Arguments included with effect: '[5]' Other information has been printed to console...`

enchant config:
`    5:
      chance: 100
      effects:
        - 'TRENCH:5'`

**Server Information (please complete the following information):**
- Server Version: [e.g. PaperSpigot-123 1.8.8] 
- bukkit : Tuinity 1.16.4
- Plugin Version: [e.g. 6.7.8]
- 8.0.0-Pre20.6

I am sorry that I am not good at English

**Comment by Sikatsu** [comment]
Same error!

**Comment by GC-spigot** [comment]
Fixed
