### ISSUE TITLE
[Issue] Console spammed with trench bugs

### ISSUE THREAD

**Issue by Weslly96** [GC-spigot/AdvancedEnchantments#1769]
[15:20:13] [Server thread/INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: 
[15:20:13] [Server thread/INFO]: [AdvancedEnchantments]    Class: 
[15:20:13] [Server thread/INFO]: [AdvancedEnchantments]    Extra info: effect[TRENCH:7]; enchant [atomicdetonate]; mc[116]; ae[8.0.0-Pre20.9]
[15:20:13] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.

[15:27:20] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to AdvancedEnchantments v8.0.0-Pre20.9
[15:27:20] [Server thread/ERROR]: Suspected Plugins: 
[15:27:20] [Server thread/ERROR]: 	AdvancedEnchantments{enabled,ver=8.0.0-Pre20.9,path=plugins/AdvancedEnchantments-8.0.0-Pre20.9.jar}
[15:27:20] [Server thread/ERROR]: Exception details below: 
java.lang.NullPointerException: null
	at n3kas.ae.items.TransmogScroll.applyTransmog(TransmogScroll.java:152) ~[?:?]
	at n3kas.ae.api.AEAPI.applyEnchant(AEAPI.java:401) ~[?:?]
	at n3kas.ae.api.AEAPI.applyEnchant(AEAPI.java:331) ~[?:?]
	at n3kas.ae.handlers.anvil.AnvilEvent.onAnvil(AnvilEvent.java:56) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor580.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at org.bukkit.event.Event.callEvent(Event.java:45) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1595) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:68) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:12) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.Slot.d(SourceFile:87) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.Slot.set(SourceFile:83) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.Container.b(Container.java:362) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.Container.a(Container.java:188) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2676) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:32) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.PacketPlayInWindowClick.a(SourceFile:10) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1218) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1211) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1286) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1016) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:176) ~[1.16.5-patched.jar:git-Yatopia-ver/1.16.5-31]
	at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Insprill** [comment]
I see the trench NPE at the top but it doesn't have any info. the error you sent is related to anvils and will be fixed in the next version. can you reproduce the trench issue?

**Comment by Insprill** [comment]
Assuming the actual error is the same as #1768, then it's fixed in the next update

**Comment by Insprill** [comment]
Will be fixed in 21.4, still present in 21.3.

**Comment by Weslly96** [comment]
Several enchantments such as the atomic detonate when applied comes out in the lore "nullAtomicdetonate" in purple color, quite apart from the TRENCH problem

**Comment by Insprill** [comment]
That's not related to this issue
