### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot drop air [Issue]

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#1787]
**Describe the bug**
Error on console when using alchemist
[13:01:00 INFO]: astroanas issued server command: /alchemist
[13:01:02 WARN]: java.lang.IllegalArgumentException: Cannot drop air
[13:01:02 WARN]:        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.EntityItem.setItemStack(EntityItem.java:455)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.EntityItem.<init>(EntityItem.java:43)
[13:01:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItem(CraftWorld.java:754)
[13:01:02 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItem(CraftWorld.java:748)
[13:01:02 WARN]:        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:1977)
[13:01:02 WARN]:        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1322)
[13:01:02 WARN]:        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:121)
[13:01:02 WARN]:        at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:261)
[13:01:02 WARN]:        at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:126)
[13:01:02 WARN]:        at n3kas.ae.enchanthandler.enchanttypes.MINING.lambda$onBlockBreak$0(MINING.java:85)
[13:01:02 WARN]:        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[13:01:02 WARN]:        at n3kas.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:79)
[13:01:02 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1091.execute(Unknown Source)
[13:01:02 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:01:02 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:01:02 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:01:02 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:325)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:284)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:225)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1489)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:40)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInBlockDig.a(SourceFile:10)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1140)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1133)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1094)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1008)
[13:01:02 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[13:01:02 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[13:01:02 INFO]: [AdvancedEnchantments ERROR] Could not pass IllegalArgumentException: Cannot drop air
[13:01:02 INFO]: [AdvancedEnchantments]    Class: n3kas.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:1977)
[13:01:02 INFO]: [AdvancedEnchantments]    Extra info: effect[TRENCH:3]; enchant [detonate]; mc[116]; ae[8.0.0-Pre21.1]
[13:01:02 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
**To Reproduce**
/alchemist

**Screenshots / Video**
If applicable, add screenshots or videos to help explain/ show your problem.

**Server Information (please complete the following information):**
- Server Version: paper-1.16.5-550.jar
- Plugin Version: AdvancedEnchantments-8.0.0-Pre21.2.jar

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by Insprill** [comment]
Will be fixed in 21.4, still present in 21.3.
