### ISSUE TITLE
SMELT error

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2147]
## Details

**Describe the bug**
Random error on console spamming it.
[17:22:37 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because the return value of "net.advancedplugins.ae.enchanthandler.effects.Smelt.material(org.bukkit.Material, boolean)" is null
[17:22:37 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2185)
[17:22:37 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1436)
[17:22:37 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:135)
[17:22:37 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:263)
[17:22:37 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:125)
[17:22:37 WARN]:        at net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:84)
[17:22:37 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1122.execute(Unknown Source)
[17:22:37 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[17:22:37 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:22:37 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:22:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[17:22:37 WARN]:        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:374)
[17:22:37 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:334)
[17:22:37 WARN]:        at net.minecraft.server.level.PlayerInteractManager.handleBlockBreakAction(PlayerInteractManager.java:275)
[17:22:37 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1662)
[17:22:37 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[17:22:37 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[17:22:37 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[17:22:37 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:22:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[17:22:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[17:22:37 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[17:22:37 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[17:22:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[17:22:37 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[17:22:37 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[17:22:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[17:22:37 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[17:22:37 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[17:22:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[17:22:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[17:22:37 INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because the return value of "net.advancedplugins.ae.enchanthandler.effects.Smelt.material(org.bukkit.Material, boolean)" is null
[17:22:37 INFO]: [AdvancedEnchantments]    Class: net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2185)
[17:22:37 INFO]: [AdvancedEnchantments]    Extra info: effect[TRENCH:7]; enchant [atomicdetonate]; mc[117]; ae[8.4.9]
[17:22:37 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 

**To Reproduce**
Just let players do their thing, it will popup randomly.

**Screenshots / Video**
Don't have any

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/yehepesilo
- Server log: https://mcpaste.io/7d925e23ae6119c2

**Comment by Insprill** [comment]
Fixed in the next update
