### ISSUE TITLE
EntityDamageByEntityEvent -v8.5.2

### ISSUE THREAD

**Issue by arceusxs2** [GC-spigot/AdvancedEnchantments#2170]
## Details

**Describe the bug**

After updating to v8.5.2 i satarted getting these errors in console.
[ERROR] Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.5.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftCreeper cannot be cast to class org.bukkit.entity.Projectile (org.bukkit.craftbukkit.v1_16_R3.entity.CraftCreeper and org.bukkit.entity.Projectile are in unnamed module of loader 'app')
at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.activate(DEFENSE_MOB.java:72) ~[?:?]
at net.advancedplugins.ae.e
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Purpur-1117]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1117]
at java.lang.Thread.run(Unknown Source) [?:?]

[ERROR] Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.5.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftPhantom cannot be cast to class org.bukkit.entity.Projectile (org.bukkit.craftbukkit.v1_16_R3.entity.CraftPhantom and org.bukkit.entity.Projectile are in unnamed module of loader 'app')
at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.activate(DEFENSE_MOB.java:72) ~[?:?]
at net.advancedplugins.ae.e
19:27:22[ERROR] Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.5.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftPhantom cannot be cast to class org.bukkit.entity.Projectile (org.bukkit.craftbukkit.v1_16_R3.entity.CraftPhantom and org.bukkit.entity.Projectile are in unnamed module of loader 'app')
at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.activate(DEFENSE_MOB.java:72) ~[?:?]
at net.advancedplugins.ae.e
**To Reproduce**

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: 
- Server log:

**Comment by Insprill** [comment]
Fixed in the next update
