### ISSUE TITLE
Please add support for BetterGiants

### ISSUE THREAD

**Issue by gmovd** [GC-spigot/AdvancedEnchantments#2189]
https://www.spigotmc.org/resources/better-giants.76505/
[18:46:44] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.5.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftZombie cannot be cast to class org.bukkit.entity.Projectile (org.bukkit.craftbukkit.v1_17_R1.entity.CraftZombie and org.bukkit.entity.Projectile are in unnamed module of loader 'app')
	at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.activate(DEFENSE_MOB.java:72) ~[?:?]
	at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.playerHitPlayer(DEFENSE_MOB.java:47) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor837.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper.jar:git-Airplane-"309e1df"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1085) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:971) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:927) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1117) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2055) ~[?:?]
	at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1018) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1352) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:925) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1000) ~[?:?]
	at net.minecraft.world.item.enchantment.ThornsEnchantment.doPostHurt(ThornsEnchantment.java:50) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.lambda$doPostHurtEffects$4(EnchantmentHelper.java:165) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.lambda$runIterationOnItem$1(EnchantmentHelper.java:128) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.runIterationOnItem(EnchantmentHelper.java:127) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.runIterationOnInventory(EnchantmentHelper.java:137) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.doPostHurtEffects(EnchantmentHelper.java:168) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1342) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2018) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.onAttack(ServerGamePacketListenerImpl.java:2475) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2402) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1419) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1397) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1390) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1366) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1277) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper.jar:git-Airplane-"309e1df"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[18:46:45] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.5.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftZombie cannot be cast to class org.bukkit.entity.Projectile (org.bukkit.craftbukkit.v1_17_R1.entity.CraftZombie and org.bukkit.entity.Projectile are in unnamed module of loader 'app')
	at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.activate(DEFENSE_MOB.java:72) ~[?:?]
	at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.playerHitPlayer(DEFENSE_MOB.java:47) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor837.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper.jar:git-Airplane-"309e1df"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1085) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:971) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:927) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1117) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2055) ~[?:?]
	at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1018) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1352) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:925) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1000) ~[?:?]
	at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1601) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.doHurtTarget(Zombie.java:361) ~[?:?]
	at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:142) ~[?:?]
	at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:134) ~[?:?]
	at net.minecraft.world.entity.ai.goal.ZombieAttackGoal.tick(ZombieAttackGoal.java:28) ~[?:?]
	at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:53) ~[?:?]
	at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:158) ~[?:?]
	at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:882) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3168) ~[?:?]
	at net.minecraft.world.entity.Mob.aiStep(Mob.java:654) ~[?:?]
	at net.minecraft.world.entity.monster.Monster.aiStep(Monster.java:43) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.aiStep(Zombie.java:266) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2894) ~[?:?]
	at net.minecraft.world.entity.Mob.tick(Mob.java:416) ~[?:?]
	at net.minecraft.world.entity.monster.Zombie.tick(Zombie.java:236) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1192) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:838) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:40) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:817) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1625) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:484) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1477) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1267) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper.jar:git-Airplane-"309e1df"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[18:46:45] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.5.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftZombie cannot be cast to class org.bukkit.entity.Projectile (org.bukkit.craftbukkit.v1_17_R1.entity.CraftZombie and org.bukkit.entity.Projectile are in unnamed module of loader 'app')
	at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.activate(DEFENSE_MOB.java:72) ~[?:?]
	at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.playerHitPlayer(DEFENSE_MOB.java:47) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor837.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper.jar:git-Airplane-"309e1df"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:242) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1085) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:971) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:927) ~[paper.jar:git-Airplane-"309e1df"]
	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1117) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2055) ~[?:?]
	at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1018) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1344) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:925) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1000) ~[?:?]
	at net.minecraft.world.item.enchantment.ThornsEnchantment.doPostHurt(ThornsEnchantment.java:50) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.lambda$doPostHurtEffects$4(EnchantmentHelper.java:165) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.lambda$runIterationOnItem$1(EnchantmentHelper.java:128) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.runIterationOnItem(EnchantmentHelper.java:127) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.runIterationOnInventory(EnchantmentHelper.java:137) ~[?:?]
	at net.minecraft.world.item.enchantment.EnchantmentHelper.doPostHurtEffects(EnchantmentHelper.java:168) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1342) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2018) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.onAttack(ServerGamePacketListenerImpl.java:2475) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2402) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1419) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:193) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1397) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1390) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1366) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1277) ~[paper.jar:git-Airplane-"309e1df"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper.jar:git-Airplane-"309e1df"]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by Insprill** [comment]
Update AE
