### ISSUE TITLE
Entity error spam in console on divert (possibly) enchantment

### ISSUE THREAD

**Issue by SlyyJacob** [GC-spigot/AdvancedEnchantments#2198]
## Details

The console gets spammed when a custom mob (mythicmobs) gets hit/hits a player with divert enchantment
```
[16:12:37 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.5.2
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftStray cannot be cast to class org.bukkit.entity.Projectile (org.bukkit.craftbukkit.v1_17_R1.entity.CraftStray and org.bukkit.entity.Projectile are in unnamed module of loader 'app')
        at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.activate(DEFENSE_MOB.java:72) ~[?:?]
        at net.advancedplugins.ae.enchanthandler.enchanttypes.DEFENSE_MOB.playerHitPlayer(DEFENSE_MOB.java:47) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor458.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-130]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-130]
        at io.lumine.xikage.mythicmobs.adapters.bukkit.BukkitSkillAdapter.doDamage(BukkitSkillAdapter.java:101) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.damage.DamagingMechanic.doDamage(DamagingMechanic.java:38) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.mechanics.DamageMechanic.castAtEntity(DamageMechanic.java:36) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.lambda$executeTargetedEntitySkill$5(SkillMechanic.java:453) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.executeTargetedEntitySkill(SkillMechanic.java:449) ~[?:?]
        at io.lumine.xikage.mythicmobs.skills.SkillMechanic.lambda$executeSkills$1(SkillMechanic.java:406) ~[?:?]
        at io.lumine.xikage.mythicmobs.utils.Delegates$RunnableToSupplier.get(Delegates.java:121) ~[?:?]
        at io.lumine.xikage.mythicmobs.utils.promise.LuminePromise$SupplyRunnable.run(LuminePromise.java:654) ~[?:?]
        at io.lumine.xikage.mythicmobs.utils.tasks.LumineExecutors$SchedulerWrappedRunnable.run(LumineExecutors.java:70) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-130]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1490) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-130]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-130]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**To Reproduce**
Have a custom mob (mythicmobs for example) and have divert ench on you. Get hit by the mob.

## Server Information
https://paste.md-5.net/xiceculadu

**Comment by Insprill** [comment]
Update AE
