### ISSUE TITLE
WorldGuard API updated

### ISSUE THREAD

**Issue by idubbbbz** [GC-spigot/AdvancedEnchantments#220]
| Name           | Version       |
|----------------|---------------|
| Java | 8 |
| Paper          | [#448 (1.13.2)](https://papermc.io/ci/job/Paper-1.13/448/) |
| WorldEdit      | 7.0.0-SNAPSHOT;3944-ee8602b |
| WorldGuard      | 7.0.0-SNAPSHOT;1756-015f192 |
| AsyncWorldEdit | 3.6.0-beta-9  |

https://blog.me4502.com/updating-worldguard-to-minecraft-113.html

```
[01:21:46 ERROR]: Could not pass event PlayerInteractEvent to AdvancedEnchantments v5.0.0
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.canBuild(Lorg/bukkit/entity/Player;Lorg/bukkit/block/Block;)Z
        at n3kas.ae.enchanttypes.p.a(p.java) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor206.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-458]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-458]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-458]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-458]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:314) ~[patched_1.13.2.jar:git-Paper-458]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:281) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1283) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-458]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_181]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-458]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-458]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by idubbbbz** [comment]
dupe #217

**Comment by idubbbbz** [comment]
This is not dupe of #217 sorry for mass

**Comment by GC-spigot** [comment]
Will be fixed in next update.
