### ISSUE TITLE
AE error spam and causing console to not display players chat - Could not pass NullPointerException

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2200]
## Details

**Describe the bug**
Random errors, also the console no longer display players chat somehow.
extreme lag is also present and wasn't present before whenever people are digging or pvping, my server have ryzen 9 core and 24 GB allocated of ram which half is empty with only 30 players online, and it's a dedicated with 128 GB of ram and NVME.
https://timings.aikar.co/?id=a188fd2f328442ea9d8bae9af7554f25

**To Reproduce**
Update and restart.
my server is on java 16, pterodactyl panel. was fine before update.
[23:51:29] [Server thread/INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: 
[23:51:29] [Server thread/INFO]: [AdvancedEnchantments]    Class: 
[23:51:29] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
also this
[00:45:32 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
[00:45:32 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:45:32 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:45:32 WARN]:        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)
[00:45:32 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330)
[00:45:32 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[00:45:32 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[00:45:32 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
[00:45:35 INFO]: Conicon_izz_da issued server command: /cf 50
[00:45:37 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
[00:45:37 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:45:37 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:45:37 WARN]:        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)
[00:45:37 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330)
[00:45:37 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[00:45:37 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[00:45:37 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/culaxusupe
- Server log: https://mclo.gs/LgXmiOI

**Comment by Insprill** [comment]
Do you know when the error is happening? For some reason the error is missing a reason

**Comment by Insprill** [comment]
Is this still an issue on new versions?
