### ISSUE TITLE
Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "drop" is null - Trench

### ISSUE THREAD

**Issue by SlyyJacob** [GC-spigot/AdvancedEnchantments#2203]
## Details

**Describe the bug**
An error pops up after using the trench enchantment on pickaxe mining regular underground blocks (uncertain which block(s) caused it, the player was just mining stone/ores).
```
[18:51:51 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "drop" is null
[18:51:51 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2080)
[18:51:51 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1397)
[18:51:51 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:140)
[18:51:51 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
[18:51:51 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:127)
[18:51:51 WARN]:        at net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:115)
[18:51:51 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor482.execute(Unknown Source)
[18:51:51 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[18:51:51 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:51:51 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[18:51:51 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[18:51:51 WARN]:        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)
[18:51:51 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330)
[18:51:51 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:296)
[18:51:51 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1656)
[18:51:51 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[18:51:51 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[18:51:51 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[18:51:51 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[18:51:51 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[18:51:51 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[18:51:51 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[18:51:51 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[18:51:51 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[18:51:51 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[18:51:51 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[18:51:51 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[18:51:51 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[18:51:51 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[18:51:51 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[18:51:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[18:51:51 INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "drop" is null
[18:51:51 INFO]: [AdvancedEnchantments]    Class: net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2080)
[18:51:51 INFO]: [AdvancedEnchantments]    Extra info: effect[TRENCH:3]; enchant [trench]; mc[117]; ae[8.5.6]
[18:51:51 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
```

**Screenshots**
![2021-07-26 19_02_55](https://user-images.githubusercontent.com/36818957/127029465-2c8c1767-04c3-4b44-a38f-66f22fc768c2.jpg)

**To Reproduce**
Mine with the trench IX enchantment on your pickaxe. I've tried to replicate it to no avail, all the enchants on the pickaxe: Efficiency V, Mending, Silk touch, Unbreaking III, Trench IX (diamond pickaxe).

## Server Information
https://paste.md-5.net/jowalowexo

**Comment by Insprill** [comment]
Fixed in the next update

**Comment by SlyyJacob** [comment]
@Insprill I am getting the error again
![2021-07-31 17_34_40](https://user-images.githubusercontent.com/36818957/127744952-3b85a3b3-6af5-492f-809f-60353a4f3885.jpg)
```
[17:28:46 INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "drop" is null
[17:28:46 INFO]: [AdvancedEnchantments]    Class: net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2080)
[17:28:46 INFO]: [AdvancedEnchantments]    Extra info: effect[TRENCH:3]; enchant [trench]; mc[117]; ae[8.5.6]
[17:28:46 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
[17:28:49 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "drop" is null
[17:28:49 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2080)
[17:28:49 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1397)
[17:28:49 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:140)
[17:28:49 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
[17:28:49 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:127)
[17:28:49 WARN]:        at net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:115)
[17:28:49 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor479.execute(Unknown Source)
[17:28:49 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[17:28:49 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:28:49 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:28:49 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[17:28:49 WARN]:        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)
[17:28:49 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330)
[17:28:49 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:296)
[17:28:49 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1656)
[17:28:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[17:28:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[17:28:49 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[17:28:49 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:28:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[17:28:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[17:28:49 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[17:28:49 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[17:28:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[17:28:49 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[17:28:49 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[17:28:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[17:28:49 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[17:28:49 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[17:28:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[17:28:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

https://paste.md-5.net/iseqonoqap

**Comment by Insprill** [comment]
@SlyyJacob update AE

**Comment by SlyyJacob** [comment]
@Insprill sorry to reopen once more but the issue popped up again, this time I figured out it was the snow block (minecraft:snow) causing the error. Makes sense I guess, since it has no drop.

```
[13:42:13 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
[13:42:14 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "drop" is null
[13:42:14 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2085)
[13:42:14 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1407)
[13:42:14 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:145)
[13:42:14 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
[13:42:14 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:127)
[13:42:14 WARN]:        at net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:115)
[13:42:14 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor479.execute(Unknown Source)
[13:42:14 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:42:14 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:42:14 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:42:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[13:42:14 WARN]:        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)
[13:42:14 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330)
[13:42:14 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:296)
[13:42:14 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1656)
[13:42:14 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[13:42:14 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[13:42:14 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[13:42:14 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:42:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[13:42:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[13:42:14 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[13:42:14 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[13:42:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[13:42:14 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[13:42:14 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[13:42:14 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[13:42:14 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1458)
[13:42:14 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[13:42:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:42:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[13:42:14 INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "drop" is null
[13:42:14 INFO]: [AdvancedEnchantments]    Class: net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2085)
[13:42:14 INFO]: [AdvancedEnchantments]    Extra info: effect[TRENCH:3]; enchant [trench]; mc[117]; ae[8.5.9]
[13:42:14 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
```
