### ISSUE TITLE
Bug with TRENCH enchant

### ISSUE THREAD

**Issue by gmovd** [GC-spigot/AdvancedEnchantments#2208]
My console is trowing this error, MC 1.17 last advancedenchantments version
[19:29:16 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "<local17>" is null
[19:29:16 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2080)
[19:29:16 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1397)
[19:29:16 WARN]:        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:140)
[19:29:16 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
[19:29:16 WARN]:        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:127)
[19:29:16 WARN]:        at net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:115)
[19:29:16 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor858.execute(Unknown Source)
[19:29:16 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[19:29:16 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[19:29:16 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[19:29:16 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[19:29:16 WARN]:        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402)
[19:29:16 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:356)
[19:29:16 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:316)
[19:29:16 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1746)
[19:29:16 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[19:29:16 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[19:29:16 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[19:29:16 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[19:29:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[19:29:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[19:29:16 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1419)
[19:29:16 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:193)
[19:29:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[19:29:16 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1397)
[19:29:16 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1390)
[19:29:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110)
[19:29:16 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1529)
[19:29:16 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1267)
[19:29:16 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[19:29:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by gmovd** [comment]
[19:29:16 INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "<local17>" is null
[19:29:16 INFO]: [AdvancedEnchantments]    Class: net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2080)
[19:29:16 INFO]: [AdvancedEnchantments]    Extra info: effect[CUSTOM_TRENCH:23, 1, 23]; enchant [trueminer]; mc[117]; ae[8.5.6]
[19:29:16 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report.

**Comment by Insprill** [comment]
Fixed for the next update
