### ISSUE TITLE
Bug console spam True Miner

### ISSUE THREAD

**Issue by gmovd** [GC-spigot/AdvancedEnchantments#2228]
Since 1.17 True miner giving this error:

[08:26:58] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "<local16>" is null
[08:26:58] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2085)
[08:26:58] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1407)
[08:26:58] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:145)
[08:26:58] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:304)
[08:26:58] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:127)
[08:26:58] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:115)
[08:26:58] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor882.execute(Unknown Source)
[08:26:58] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[08:26:58] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[08:26:58] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[08:26:58] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:402)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:151)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.tick(EntityPlayer.java:632)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.entityJoinedWorld(WorldServer.java:1142)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.lambda$tick$7(WorldServer.java:788)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:43)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:767)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1625)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:484)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1477)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1267)
[08:26:58] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[08:26:58] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[08:26:58] [Server thread/INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "<local16>" is null
[08:26:58] [Server thread/INFO]: [AdvancedEnchantments]    Class: net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2085)
[08:26:58] [Server thread/INFO]: [AdvancedEnchantments]    Extra info: effect[CUSTOM_TRENCH:23, 1, 23]; enchant [trueminer]; mc[117]; ae[8.5.9]
[08:26:58] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
[08:27:22] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "<local16>" is null

**Comment by Insprill** [comment]
We need the link from `/ae plinfo`.

**Comment by Insprill** [comment]
Fixed for the next update. In the future, your issue will be ignored if you don't provide a `ae plinfo` link.
