### ISSUE TITLE
Plugin breaking ERROR - Plugin Error forcing it to self disable v8.5.9 - No players on at time

### ISSUE THREAD

**Issue by EchocallingEarth** [GC-spigot/AdvancedEnchantments#2229]
**Describe the bug**This is a game-breaking error, in the fact that it disables the plugin making it useless to players and preventing the use of said items etc.
https://pastebin.com/em9QvS0i

It is IMPORANT to note that running ae plinfo throws an error because the plugin is broken.

Happens on its own so no way to reproduce This happened post me logging off and I am the only player who was one (see log for details)

> ae plinfo
[07:02:54 WARN]: Unexpected exception while parsing console command "ae plinfo"
org.bukkit.command.CommandException: Cannot execute command 'ae' in plugin AdvancedEnchantments v8.5.9 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.17.1.jar:git-Purpur-1287]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1287]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Purpur-1287]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:784) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:531) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1287]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1287]
        at java.lang.Thread.run(Thread.java:831) [?:?]

https://pastebin.com/em9QvS0i

Server 1.17.1 Purpur

Plugins:
AdvancedChests, AdvancedClaimGuardian, AntiCurse, ArmoredElytra, AureliumSkills, Bank, BigDoors, BlockParticles, ChestSort, Chunky, Citizens, CleanroomGenerator, CMI, CMIEInjector*, CMILib, ConsoleSpamFix, Core, CoreProtect, CustomCrafting, CustomEnderChest, CustomShop, Denizen, DisplayShops, dtlTradersPlus, EpicBackpacks, EpicFarming, EpicFurnaces, EpicHoppers, ExoticGarden, ExtraGear, ExtraTools, FastAsyncWorldEdit (WorldEdit), HeadDatabase, HolographicDisplays, HorseOverhaul, ImageOnMap, InfoBook, Item-Chest-Sorter, ItemsAdder, Jobs, LibsDisguises, LightAPI, LimitPillagers, LoneLibs, Lootin, LuckPerms, LWC, Multiverse-Core, NBTAPI, NetheriteShield, NoPlugins, PerWorldInventory, PlaceholderAPI, ProtocolLib, PublicCrafters, Sentinel, Slimefun, spark, SuperLuckyBlock, SurvivalInvisiframes, Terra, UltimateCatcher, UltimateFishing, UltimateRepairing, UltimateStacker, UltimateTimber, VanillaTweaks, Vault, WolfyUtilities

Disabled Plugin sees Log and error in this message.
AdvancedEnchantments(disabled)

Further info upon request.

**Comment by Insprill** [comment]
Not a bug, our auth servers were down for a couple hours. Should be resolved now.

**Comment by EchocallingEarth** [comment]
Just noting they were down for over 12 hours, not a couple. But okay. Glad that is fixed.
