### ISSUE TITLE
Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "drop" is null

### ISSUE THREAD

**Issue by SlyyJacob** [GC-spigot/AdvancedEnchantments#2240]
As mentioned #2203 , the bug still exists. I was able to pinpoint one of the blocks being snow. Since it has no drop it errors when using Trench on a pickaxe. It errors on other blocks too, leaves being some of them, not sure what are the other blocks (possibly falling gravel).

```
[10:56:46 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "drop" is null
[10:56:46 WARN]:        at AdvancedEnchantments-8.6.0.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2133)
[10:56:46 WARN]:        at AdvancedEnchantments-8.6.0.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1449)
[10:56:46 WARN]:        at AdvancedEnchantments-8.6.0.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:196)
[10:56:46 WARN]:        at AdvancedEnchantments-8.6.0.jar//net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:315)
[10:56:46 WARN]:        at AdvancedEnchantments-8.6.0.jar//net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:142)
[10:56:46 WARN]:        at AdvancedEnchantments-8.6.0.jar//net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:115)
[10:56:46 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor479.execute(Unknown Source)
[10:56:46 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[10:56:46 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[10:56:46 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[10:56:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[10:56:46 WARN]:        at net.minecraft.server.level.PlayerInteractManager.breakBlock(PlayerInteractManager.java:370)
[10:56:46 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:330)
[10:56:46 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:271)
[10:56:46 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1656)
[10:56:46 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:34)
[10:56:46 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:8)
[10:56:46 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[10:56:46 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:56:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[10:56:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[10:56:46 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[10:56:46 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[10:56:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[10:56:46 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[10:56:46 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[10:56:46 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[10:56:46 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1281)
[10:56:46 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1192)
[10:56:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[10:56:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[10:56:46 INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "drop" is null
[10:56:46 INFO]: [AdvancedEnchantments]    Class: AdvancedEnchantments-8.6.0.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.handleDrop(RunnableEffect.java:2133)
[10:56:46 INFO]: [AdvancedEnchantments]    Extra info: effect[TRENCH:3]; enchant [trench]; mc[117]; ae[8.5.7]
[10:56:46 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
```

https://paste.md-5.net/irahidihar

**Comment by Insprill** [comment]
Update AE
