### ISSUE TITLE
Trench enchantment isn't working

### ISSUE THREAD

**Issue by CaptainAmpersand** [GC-spigot/AdvancedEnchantments#225]
PaperSpigot 1.13.2
AE version 5.0.2
Issue: Can't get Trench, no matter what, to actually effectively work. It will only create an error, and fail to actually work.
Error log (When using Trench): 
```[22:04:20] [Server thread/WARN]: [AdvancedEnchantments] Task #12733212 for AdvancedEnchantments v5.0.2 generated an exception
java.lang.NoSuchMethodError: com.sk89q.worldguard.bukkit.WorldGuardPlugin.canBuild(Lorg/bukkit/entity/Player;Lorg/bukkit/Location;)Z
	at n3kas.ae.hooks.a.a(a.java) ~[?:?]
	at n3kas.ae.effectsreader.h.d(h.java) ~[?:?]
	at n3kas.ae.effectsreader.h.a(h.java) ~[?:?]
	at n3kas.ae.enchanthandler.c.run(c.java) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.13.2.jar:git-Paper-451]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.13.2.jar:git-Paper-451]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[patched_1.13.2.jar:git-Paper-451]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-451]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-451]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-451]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]```

**Comment by CaptainAmpersand** [comment]
Since it's a worldguard issue, my version is 7.0.0-SNAPSHOT;1756-015f192

**Comment by GC-spigot** [comment]
Will be fixed.

**Comment by CaptainAmpersand** [comment]
Error still persists 5.0.4
Worldguard version 7.0.0 1761, Worldedit version 7.0.0 beta 3
PaperSpigot 1.13.2 ver 469
Error log: http://paste.ddarkmafia.com/eridewosub.bash
