### ISSUE TITLE
Server crash on /enchants and Error thrown when doing /e

### ISSUE THREAD

**Issue by antibitcoin** [GC-spigot/AdvancedEnchantments#2254]
## Details
Downgrading to AdvancedEnchantments-8.6.2 brings back /e and don't crash when using /enchants.

**Describe the bug**
First of all here is how the server crash
https://mcpaste.io/f66502a48df46fc5

when doing /e error is thrown also after the update.
[11:05:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'e' in net.advancedplugins.ae.handlers.commands.EnchanterCommand(enchanter)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2170) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1981) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:1962) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:36) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1348) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.shouldRun(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1281) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.1.jar:git-Paper-172]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-172]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.toUpperCase(java.util.Locale)" because "<parameter1>" is null
        at net.advancedplugins.ae.enchanthandler.enchantments.AdvancedGroup.matchGroup(AdvancedGroup.java:44) ~[AdvancedEnchantments-8.6.3.jar:?]
        at net.advancedplugins.ae.features.enchanter.Enchanter.updateInventory(Enchanter.java:107) ~[AdvancedEnchantments-8.6.3.jar:?]
        at net.advancedplugins.ae.features.enchanter.Enchanter.openForPlayer(Enchanter.java:46) ~[AdvancedEnchantments-8.6.3.jar:?]
        at net.advancedplugins.ae.handlers.commands.EnchanterCommand.execute(EnchanterCommand.java:43) ~[AdvancedEnchantments-8.6.3.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-172]
        ... 20 more
**To Reproduce** 
type /e and hit enter

**Screenshots / Video**

## Server Information
- "/ae plinfo" link: https://paste.md-5.net/tawijiduba
- Server log: https://mcpaste.io/98b415b121543afe

**Comment by itslukemango** [comment]
Also getting this

**Comment by Insprill** [comment]
This looks like the crash is coming from internal Spigot material matching, can you guys try downgrading a few versions and see if the issue goes away?

**Comment by LordMick14** [comment]
It works fine with 8.6.2, but 8.6.3 create this error this also does it with /ce.

**Comment by Insprill** [comment]
Fixed for the next update

**Comment by NightLife-SG** [comment]
Issue still persist on lastest update
