### ISSUE TITLE
Console throw error when leave on join game with non equpment item in head slot.

### ISSUE THREAD

**Issue by notynote** [GC-spigot/AdvancedEnchantments#2349]
### Describe the bug

I had made a custom item that enchant to the End Rod and enchant it with the enchantment below.

`sparkle:
display: '&dSparkle'
description: 'Shine like a superstart when begin and stop from running'
applies-to: "Armor"
type: "SPRINT"
group: FABLED
applies:

ALL_ARMOR
levels:
'1':
chance: 50
effects:
PARTICLE:FIREWORKS_SPARK:20:1
WAIT:10
PARTICLE:FIREWORKS_SPARK:20:1
WAIT:10
PARTICLE:FIREWORKS_SPARK:20:1`

When player left the game with so call item in their head.

[12:49:26 ERROR]: Could not pass event PlayerQuitEvent to AdvancedEnchantments v8.6.11 java.lang.NullPointerException: Cannot invoke "net.advancedplugins.ae.utils.ArmorType.getRollItemType()" because "<local4>" is null at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.runCheck(EFFECT_STATIC.java:95) ~[?:?] at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.onPlayerQuit(EFFECT_STATIC.java:163) ~[?:?] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor550.execute(Unknown Source) ~[?:?] at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-788] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-788] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-788] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.PlayerList.disconnect(PlayerList.java:597) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1856) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.NetworkManager.handleDisconnection(NetworkManager.java:520) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:188) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1515) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788] at java.lang.Thread.run(Thread.java:831) [?:?]

and this when their reconnect

[12:49:38 WARN]: [AdvancedEnchantments] Task #10872 for AdvancedEnchantments v8.6.11 generated an exception java.lang.NullPointerException: Cannot invoke "net.advancedplugins.ae.utils.ArmorType.getRollItemType()" because "<local4>" is null at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.runCheck(EFFECT_STATIC.java:95) ~[?:?] at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.lambda$onPlayerJoin$2(EFFECT_STATIC.java:173) ~[?:?] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-788] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-788] at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788] at java.lang.Thread.run(Thread.java:831) [?:?]

### How to reproduce

Apply enchantment below to any non equipment item and leave/join the server while wearing item in head slot

`sparkle:
display: '&dSparkle'
description: 'Shine like a superstart when begin and stop from running'
applies-to: "Armor"
type: "SPRINT"
group: FABLED
applies:

ALL_ARMOR
levels:
'1':
chance: 50
effects:
PARTICLE:FIREWORKS_SPARK:20:1
WAIT:10
PARTICLE:FIREWORKS_SPARK:20:1
WAIT:10
PARTICLE:FIREWORKS_SPARK:20:1`

### "/ae plinfo" link

https://paste.md-5.net/verilebola

### Server Log

https://mcpaste.io/8ab82e46a88790a6

**Comment by notynote** [comment]
just saw the edited reply from https://github.com/GC-spigot/AdvancedEnchantments/issues/2347
