### ISSUE TITLE
Potion Effect does not get removed when remove non-armor item from armor slot

### ISSUE THREAD

**Issue by notynote** [GC-spigot/AdvancedEnchantments#2381]
### Describe the bug

the problem happens with non armor item with a enchantment that contains `EFFECT_STATIC` type which give permanent potion effect.

The potion effect will not be removed when player remove the item from their armor slot.

### How to reproduce

Enchant the `EFFECT_STATIC` enchantment that give permanent potion effect onto non armor item then equip it. After that, remove the item from armor slot and the potion effect will not be removed.

Meanwhile the console will throw this error (I'm using 8.6.14 but the log say it 8.6.13)

`
[20:23:00 WARN]: [AdvancedEnchantments] Task #6155 for AdvancedEnchantments v8.6.13 generated an exception
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.ae.utils.ArmorType.getRollItemType()" because "<parameter3>" is null
	at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.runCheck(EFFECT_STATIC.java:101) ~[?:?]
	at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.updateWornArmor(EFFECT_STATIC.java:56) ~[?:?]
	at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC.updateWornArmor(EFFECT_STATIC.java:51) ~[?:?]
	at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC$PaperArmorChangeListener.lambda$onArmorChange$0(EFFECT_STATIC.java:118) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-788]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1427) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-788]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-788]
	at java.lang.Thread.run(Thread.java:831) [?:?]`

### Screenshots / Videos

https://prnt.sc/1tl58ja

### "/ae plinfo" link

https://paste.md-5.net/ahiniwofen

### Server Log

https://mcpaste.io/2cf0e5417df155de

**Comment by Insprill** [comment]
Fixed in the next update
