### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xmakdwerd** [GC-spigot/AdvancedEnchantments#2385]
### Describe the bug

[22:02:18 ERROR]: Could not pass event InventoryClickEvent to AdvancedEnchantments v8.6.13
java.lang.ArrayIndexOutOfBoundsException: Index 13 out of bounds for length 9
        at java.util.Arrays$ArrayList.get(Arrays.java:4164) ~[?:?]
        at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventoryCustom$MinecraftInventory.getItem(CraftInventoryCustom.java:105) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventory.getItem(CraftInventory.java:49) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.advancedplugins.ae.features.alchemist.AlchemistInventory.isAlchemistInventory(AlchemistInventory.java:64) ~[AdvancedEnchantments-8.6.14.jar:?]
        at net.advancedplugins.ae.features.alchemist.AlchemistInventoryClicks.onClick(AlchemistInventoryClicks.java:49) ~[AdvancedEnchantments-8.6.14.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1005.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2793) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1407) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1385) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1378) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1354) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1265) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[patched_1.17.1.jar:git-Airplane-"ec7d3d0"]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[22:02:27 ERROR]: Could not pass event InventoryClickEvent to AdvancedEnchantments v8.6.13
java.lang.ArrayIndexOutOfBoundsException: null
[22:06:36 INFO]: [GoldenCrates] Auto-save: Saved 1 online users | 0 offline users.

### How to reproduce

it doesn't seem to affect anything, just spam into the console, when I added a command to the plugin, open the command bar for players on behalf of the "OP" alchemist menu, it looks like this:

panels:
  char3:
    perm: default
    rows: 1
    title: 'Объединение'
    empty: BLACK_STAINED_GLASS_PANE
    item:
      '4':
        material: ENDER_EYE
        stack: 1
        name: '&aОбъединение'
        lore:
        - '&fОбъединить книги чар'
        commands:
        - op= alchem %cp-player-name%

### "/ae plinfo" link

https://paste.md-5.net/yugahobugo

**Comment by Insprill** [comment]
Fixed in the next update
