### ISSUE TITLE
Error with the latest verison on Spigot 1.16.5

### ISSUE THREAD

**Issue by Shehzad777** [GC-spigot/AdvancedEnchantments#2387]
### Describe the bug

Here is the error I get with the latest version 8.6.13.

[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v8.6.13
[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] If you see a warning above this, ignore it. It is not not a bug.
[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into WorldGuard.
[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into WorldGuardExtraFlags.
[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into PlaceholderAPI.
[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into ProtocolLib.
[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into Essentials.
[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into BanItem.
[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] Loaded 7 armor sets.
[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[10:11:22] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R3$BlockData
[10:11:22] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[10:11:22] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
[10:11:22] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
[10:11:22] [Server thread/WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
[10:11:22] [Server thread/WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[10:11:22] [Server thread/WARN]:        at java.base/java.lang.Class.forName(Class.java:315)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.backend.ClassWrapper.<init>(ClassWrapper.java:67)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.backend.ClassWrapper.<clinit>(ClassWrapper.java:32)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.backend.ReflectionMethod.<clinit>(ReflectionMethod.java:15)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.backend.NBTItem.<init>(NBTItem.java)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.NBTapi.addNBTTag(NBTapi.java:235)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.features.usercommands.Enchantments.<init>(Enchantments.java:115)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.Core.onEnable(Core.java:388)
[10:11:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:11:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[10:11:22] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[10:11:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
[10:11:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
[10:11:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435)
[10:11:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218)
[10:11:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809)
[10:11:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[10:11:22] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[10:11:22] [Server thread/WARN]: java.lang.NullPointerException
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:115)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:128)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:132)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.backend.ReflectionMethod.<clinit>(ReflectionMethod.java:69)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.backend.NBTItem.<init>(NBTItem.java)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.utils.nbt.NBTapi.addNBTTag(NBTapi.java:235)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.features.usercommands.Enchantments.<init>(Enchantments.java:115)
[10:11:22] [Server thread/WARN]:        at net.advancedplugins.ae.Core.onEnable(Core.java:388)
[10:11:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:11:22] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[10:11:22] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[10:11:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:494)
[10:11:22] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:408)
[10:11:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:435)
[10:11:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:218)
[10:11:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809)
[10:11:22] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164)
[10:11:22] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[10:11:22] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into economy plugin (Vault)

### How to reproduce

Just run the latest version of the plugin 8.6.13 with Spigot 1.16.5.

### "/ae plinfo" link

https://paste.md-5.net/hosawukeno

**Comment by Insprill** [comment]
Fixed in the next update. The error is harmless so it can safely be ignored for the time being.
