### ISSUE TITLE
[error] (5.0.4)

### ISSUE THREAD

**Issue by Frostyeiz** [GC-spigot/AdvancedEnchantments#240]
No idea the causes, just see this errors spam my console

```

> [18:00:54] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AdvancedEnchantments v5.0.4
> org.bukkit.event.EventException: null
> 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:203) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(PlayerInteractManager.java:109) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:920) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at net.minecraft.server.v1_12_R1.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_181]
> 	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_181]
> 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1593]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
> Caused by: java.lang.NullPointerException
> 	at n3kas.ae.hooks.a.a(a.java) ~[?:?]
> 	at n3kas.ae.enchanttypes.p.a(p.java) ~[?:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor977.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.12.2.jar:git-Paper-1593]
> 	... 18 more

```

**Comment by GC-spigot** [comment]
Fixed.
