### ISSUE TITLE
NoClassDefFoundError: org/bukkit/inventory/meta/Damageable

### ISSUE THREAD

**Issue by nicklly** [GC-spigot/AdvancedEnchantments#2410]
### Describe the bug

have something custom Enchantment will take a error,this is testing video https://vimeo.com/628150203

Plugins version: 8.6.19
Server version:  paper-1.12.2-1618

### How to reproduce

when the player join my server, the console will take a error 

just like this
`[12:16:15] [Server thread/ERROR]: Could not pass event PlayerArmorChangeEvent to AdvancedEnchantments v8.6.19
org.bukkit.event.EventException: null
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.12.2.jar:git-Paper-1618]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.event.Event.callEvent(Event.java:44) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1988) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityHuman.B_(EntityHuman.java:146) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:343) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:145) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

Caused by: java.lang.NoClassDefFoundError: org/bukkit/inventory/meta/Damageable
	at net.advancedplugins.ae.utils.AManager.itemStackEquals(AManager.java:324) ~[?:?]
	at net.advancedplugins.ae.enchanthandler.enchanttypes.EFFECT_STATIC$PaperArmorChangeListener.onArmorChange(EFFECT_STATIC.java:117) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.12.2.jar:git-Paper-1618]
	... 15 more`

### "/ae plinfo" link

https://paste.md-5.net/omapuzuved

### Server Log

https://pastebin.com/dgPEsejB

**Comment by SwartZCoding** [comment]
Same issues
