### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments

### ISSUE THREAD

**Issue by SlyyJacob** [GC-spigot/AdvancedEnchantments#2412]
### Describe the bug

Found this error in the console, can't tell when it happened.
```
[17:54:18 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.6.15-SNAPSHOT
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow and org.bukkit.entity.LivingEntity are in unnamed module of loader 'app')
        at net.advancedplugins.ae.enchanthandler.enchanttypes.SHIELD_BLOCK.playerHitPlayer(SHIELD_BLOCK.java:39) ~[AdvancedEnchantments-8.6.17.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor484.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-323]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1108) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:992) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1140) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2042) ~[app:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1018) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350) ~[app:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:925) ~[app:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:998) ~[app:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:397) ~[app:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:181) ~[app:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[app:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[app:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1120) ~[app:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:988) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:775) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-323]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
[17:54:27 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.6.15-SNAPSHOT
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow and org.bukkit.entity.LivingEntity are in unnamed module of loader 'app')
        at net.advancedplugins.ae.enchanthandler.enchanttypes.SHIELD_BLOCK.playerHitPlayer(SHIELD_BLOCK.java:39) ~[AdvancedEnchantments-8.6.17.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor484.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-323]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1108) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:992) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948) ~[patched_1.17.1.jar:git-Paper-323]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1140) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2042) ~[app:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1018) ~[app:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350) ~[app:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:925) ~[app:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:998) ~[app:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:397) ~[app:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:181) ~[app:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[app:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[app:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[app:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1120) ~[app:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:988) ~[app:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:775) ~[app:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-323]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-323]
        at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

### How to reproduce

I am not sure, sorry. Found the error when searching through the log.

### "/ae plinfo" link

https://paste.md-5.net/weretaxoze

**Comment by GC-spigot** [comment]
Fixed
