### ISSUE TITLE
EntityDamageByEntity

### ISSUE THREAD

**Issue by lChrisjm** [GC-spigot/AdvancedEnchantments#2441]
### Describe the bug

I have this error since I bought the plugin, I joined another report from another user with the same problem, I'm tired of waiting, they always say "next update" and update after update remains the same and my server crashing and with that spam in the console.

If I don't get an answer to this, I would like my money back, because this was a disappointment. 

### How to reproduce

Everytime someone is fighting whit something.

### Screenshots / Videos

`>.... [06:02:46 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.7.3
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftShulkerBullet cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_17_R1.entity.CraftShulkerBullet and org.bukkit.entity.LivingEntity are in unnamed module of loader 'app')
at net.advancedplugins.ae.enchanthandler.enchanttypes.SHIELD_BLOCK.playerHitPlayer(SHIELD_BLOCK.java:39) ~[AdvancedEnchantments-8.7.3.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1003.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-327]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Paper-327]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-327]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Paper-327]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.17.1.jar:git-Paper-327]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1108) ~[patched_1.17.1.jar:git-Paper-327]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:992) ~[patched_1.17.1.jar:git-Paper-327]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:948) ~[patched_1.17.1.jar:git-Paper-327]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1140) ~[patched_1.17.1.jar:git-Paper-327]
at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2042) ~[app:?]
at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1018) ~[app:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1350) ~[app:?]
at net.minecraft.world.entity.player.Player.hurt(Player.java:925) ~[app:?]
at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:998) ~[app:?]
at net.minecraft.world.entity.projectile.ShulkerBullet.onHitEntity(ShulkerBullet.java:303) ~[app:?]
at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:181) ~[app:?]
at net.minecraft.world.entity.projectile.ShulkerBullet.onHit(ShulkerBullet.java:323) ~[app:?]
at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[app:?]
at net.minecraft.world.entity.projectile.ShulkerBullet.tick(ShulkerBullet.java:241) ~[app:?]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1120) ~[app:?]
at net.minecraft.world.level.Level.guardEntityTick(Level.java:988) ~[app:?]
at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:775) ~[app:?]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Paper-327]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:756) ~[app:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1619) ~[patched_1.17.1.jar:git-Paper-327]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-327]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-327]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-327]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-327]
at java.lang.Thread.run(Thread.java:831) ~[?:?] `

### "/ae plinfo" link

https://paste.md-5.net/hapawanivu

### Server Log

https://mcpaste.io/d67444ff5cbf9a38

**Comment by GC-spigot** [comment]
Fixed
