### ISSUE TITLE
Error In Console

### ISSUE THREAD

**Issue by Panhavisal** [GC-spigot/AdvancedEnchantments#2450]
### Describe the bug

It spam in console. And the Full Logs I Upload in one drive because it freeze on https://mcpaste.io/ (Logs Size 10MB)  

### How to reproduce

[21:22:56 WARN]: java.lang.ClassCastException: Cannot cast su.nightexpress.excellentenchants.manager.enchants.weapon.EnchantDoubleStrike to org.bukkit.craftbukkit.v1_17_R1.enchantments.CraftEnchantment
[21:22:56 WARN]:        at java.base/java.lang.Class.cast(Class.java:3818)
[21:22:56 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.getRarity(AnvilEvent.java:321)
[21:22:56 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.onAnvil(AnvilEvent.java:246)
[21:22:56 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1056.execute(Unknown Source)
[21:22:56 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:22:56 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:22:56 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:22:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633)
[21:22:56 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[21:22:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1626)
[21:22:56 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:81)
[21:22:56 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:25)
[21:22:56 WARN]:        at net.minecraft.world.InventorySubcontainer.setItem(InventorySubcontainer.java:198)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Slot.set(Slot.java:61)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:818)
[21:22:56 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.shiftClick(ContainerAnvilAbstract.java:125)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Container.b(Container.java:528)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:371)
[21:22:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2818)
[21:22:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55)
[21:22:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11)
[21:22:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[21:22:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:152)
[21:22:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:24)
[21:22:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:124)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1433)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1426)
[21:22:56 WARN]:        at net.minecraft.server.TickServ.flush(TickServ.java:235)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1583)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1301)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:22:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:22:56 WARN]: java.lang.ClassCastException: Cannot cast su.nightexpress.excellentenchants.manager.enchants.weapon.EnchantDoubleStrike to org.bukkit.craftbukkit.v1_17_R1.enchantments.CraftEnchantment
[21:22:56 WARN]:        at java.base/java.lang.Class.cast(Class.java:3818)
[21:22:56 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.getRarity(AnvilEvent.java:321)
[21:22:56 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.onAnvil(AnvilEvent.java:246)
[21:22:56 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1056.execute(Unknown Source)
[21:22:56 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:22:56 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:22:56 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:22:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633)
[21:22:56 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[21:22:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1626)
[21:22:56 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:81)
[21:22:56 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:25)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Slot.d(Slot.java:66)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Slot.set(Slot.java:62)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:818)
[21:22:56 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.shiftClick(ContainerAnvilAbstract.java:125)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Container.b(Container.java:528)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:371)
[21:22:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2818)
[21:22:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55)
[21:22:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11)
[21:22:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[21:22:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:152)
[21:22:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:24)
[21:22:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:124)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1433)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1426)
[21:22:56 WARN]:        at net.minecraft.server.TickServ.flush(TickServ.java:235)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1583)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1301)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:22:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:22:56 WARN]: java.lang.ClassCastException: Cannot cast su.nightexpress.excellentenchants.manager.enchants.weapon.EnchantDoubleStrike to org.bukkit.craftbukkit.v1_17_R1.enchantments.CraftEnchantment
[21:22:56 WARN]:        at java.base/java.lang.Class.cast(Class.java:3818)
[21:22:56 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.getRarity(AnvilEvent.java:321)
[21:22:56 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.onAnvil(AnvilEvent.java:246)
[21:22:56 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1056.execute(Unknown Source)
[21:22:56 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:22:56 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:22:56 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:22:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633)
[21:22:56 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[21:22:56 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1626)
[21:22:56 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:81)
[21:22:56 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:25)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Slot.d(Slot.java:66)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:821)
[21:22:56 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.shiftClick(ContainerAnvilAbstract.java:125)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Container.b(Container.java:528)
[21:22:56 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:371)
[21:22:56 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2818)
[21:22:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55)
[21:22:56 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11)
[21:22:56 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[21:22:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:152)
[21:22:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:24)
[21:22:56 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:124)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1433)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1426)
[21:22:56 WARN]:        at net.minecraft.server.TickServ.flush(TickServ.java:235)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1583)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1301)
[21:22:56 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:22:56 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:22:59 INFO]: KimSorng issued server command: /k fly
[21:23:03 INFO]: ObitoKH issued server command: /enchant unbreaking 3
[21:23:06 WARN]: java.lang.ClassCastException: Cannot cast su.nightexpress.excellentenchants.manager.enchants.weapon.EnchantDoubleStrike to org.bukkit.craftbukkit.v1_17_R1.enchantments.CraftEnchantment
[21:23:06 WARN]:        at java.base/java.lang.Class.cast(Class.java:3818)
[21:23:06 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.getRarity(AnvilEvent.java:321)
[21:23:06 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.onAnvil(AnvilEvent.java:246)
[21:23:06 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1056.execute(Unknown Source)
[21:23:06 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:23:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:23:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:23:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633)
[21:23:06 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[21:23:06 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1626)
[21:23:06 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:81)
[21:23:06 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:25)
[21:23:06 WARN]:        at net.minecraft.world.InventorySubcontainer.setItem(InventorySubcontainer.java:198)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Slot.set(Slot.java:61)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:818)
[21:23:06 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.shiftClick(ContainerAnvilAbstract.java:125)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Container.b(Container.java:528)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:371)
[21:23:06 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2818)
[21:23:06 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55)
[21:23:06 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11)
[21:23:06 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[21:23:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:152)
[21:23:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:24)
[21:23:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:124)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1433)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1426)
[21:23:06 WARN]:        at net.minecraft.server.TickServ.flush(TickServ.java:235)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1583)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1301)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:23:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:23:06 WARN]: java.lang.ClassCastException: Cannot cast su.nightexpress.excellentenchants.manager.enchants.weapon.EnchantDoubleStrike to org.bukkit.craftbukkit.v1_17_R1.enchantments.CraftEnchantment
[21:23:06 WARN]:        at java.base/java.lang.Class.cast(Class.java:3818)
[21:23:06 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.getRarity(AnvilEvent.java:321)
[21:23:06 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.onAnvil(AnvilEvent.java:246)
[21:23:06 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1056.execute(Unknown Source)
[21:23:06 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:23:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:23:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:23:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633)
[21:23:06 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[21:23:06 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1626)
[21:23:06 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:81)
[21:23:06 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:25)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Slot.d(Slot.java:66)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Slot.set(Slot.java:62)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:818)
[21:23:06 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.shiftClick(ContainerAnvilAbstract.java:125)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Container.b(Container.java:528)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:371)
[21:23:06 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2818)
[21:23:06 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55)
[21:23:06 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11)
[21:23:06 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[21:23:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:152)
[21:23:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:24)
[21:23:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:124)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1433)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1426)
[21:23:06 WARN]:        at net.minecraft.server.TickServ.flush(TickServ.java:235)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1583)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1301)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:23:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[21:23:06 WARN]: java.lang.ClassCastException: Cannot cast su.nightexpress.excellentenchants.manager.enchants.weapon.EnchantDoubleStrike to org.bukkit.craftbukkit.v1_17_R1.enchantments.CraftEnchantment
[21:23:06 WARN]:        at java.base/java.lang.Class.cast(Class.java:3818)
[21:23:06 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.getRarity(AnvilEvent.java:321)
[21:23:06 WARN]:        at AdvancedEnchantments-8.7.3.jar//net.advancedplugins.ae.handlers.anvil.AnvilEvent.onAnvil(AnvilEvent.java:246)
[21:23:06 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1056.execute(Unknown Source)
[21:23:06 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[21:23:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[21:23:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:23:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633)
[21:23:06 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[21:23:06 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPrepareResultEvent(CraftEventFactory.java:1626)
[21:23:06 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:81)
[21:23:06 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:25)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Slot.d(Slot.java:66)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:821)
[21:23:06 WARN]:        at net.minecraft.world.inventory.ContainerAnvilAbstract.shiftClick(ContainerAnvilAbstract.java:125)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Container.b(Container.java:528)
[21:23:06 WARN]:        at net.minecraft.world.inventory.Container.a(Container.java:371)
[21:23:06 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2818)
[21:23:06 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:55)
[21:23:06 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:11)
[21:23:06 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[21:23:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:152)
[21:23:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:24)
[21:23:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:124)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1433)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1426)
[21:23:06 WARN]:        at net.minecraft.server.TickServ.flush(TickServ.java:235)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1583)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1301)
[21:23:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[21:23:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

### "/ae plinfo" link

https://paste.md-5.net/iqopequhot

### Server Log

https://1drv.ms/t/s!Akzsr_DcTpqsjrZOU-B2ttROTxTvag?e=99NBEm

**Comment by GC-spigot** [comment]
excellentenchants are causing this - that plugin is not supported unfortunately.
