### ISSUE TITLE
Your license exceeded maximum number of unique IPs

### ISSUE THREAD

**Issue by Akusimus** [GC-spigot/AdvancedEnchantments#2491]
### Describe the bug

C:\Users\dan\Desktop\Minecraft Server>java -Xmx4096M -Xms4096M -jar paper.jar nogui
System Info: Java 17 (Java HotSpot(TM) 64-Bit Server VM 17.0.1+12-LTS-39) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[17:52:07 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:52:08 INFO]: Reloading ResourceManager: Default, bukkit
[17:52:09 INFO]: Loaded 7 recipes
[17:52:10 INFO]: Starting minecraft server version 1.17.1
[17:52:10 INFO]: Loading properties
[17:52:11 INFO]: This server is running Paper version git-Paper-388 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 22aaf91)
[17:52:11 INFO]: Server Ping Player Sample Count: 12
[17:52:11 INFO]: Using 4 threads for Netty based IO
[17:52:11 INFO]: Default game type: SURVIVAL
[17:52:11 INFO]: Generating keypair
[17:52:11 INFO]: Starting Minecraft server on *:25565
[17:52:11 INFO]: Using default channel type
[17:52:11 INFO]: Paper: Using Java 11 compression from Velocity.
[17:52:11 INFO]: Paper: Using Java cipher from Velocity.
[17:52:12 INFO]: [SimpleRename] Loading SimpleRename v13.9
[17:52:12 INFO]: [LuckPerms] Loading LuckPerms v5.3.74
[17:52:12 INFO]: [SkinsRestorer] Loading SkinsRestorer v14.1.6
[17:52:12 INFO]: [Vault] Loading Vault v1.7.3-b131
[17:52:12 INFO]: [WhitelistPlayers] Loading WhitelistPlayers v1.0.3
[17:52:12 INFO]: [SystemEnchants] Loading SystemEnchants v3.1.5
[17:52:12 INFO]: [WorldEdit] Loading WorldEdit v7.2.7+9f3e795
[17:52:13 INFO]: Got request to register class com.sk89q.worldedit.bukkit.BukkitServerInterface with WorldEdit [com.sk89q.worldedit.extension.platform.PlatformManager@28fa91de]
[17:52:13 INFO]: [Essentials] Loading Essentials v2.19.0
[17:52:13 INFO]: [EssentialsChat] Loading EssentialsChat v2.19.0
[17:52:13 INFO]: [WorldGuard] Loading WorldGuard v7.0.6+1cff55f
[17:52:13 INFO]: [AdvancedEnchantments] Loading AdvancedEnchantments v8.7.11
[17:52:13 INFO]: [WanderingTrades] Loading WanderingTrades v1.6.6
[17:52:13 INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:52:13 INFO]: [LuckPerms] Enabling LuckPerms v5.3.74
[17:52:13 INFO]:         __
[17:52:13 INFO]:   |    |__)   LuckPerms v5.3.74
[17:52:13 INFO]:   |___ |      Running on Bukkit - Paper
[17:52:13 INFO]:
[17:52:13 INFO]: [LuckPerms] Loading configuration...
[17:52:14 INFO]: [LuckPerms] Loading storage provider... [H2]
[17:52:14 INFO]: [LuckPerms] Loading internal permission managers...
[17:52:14 INFO]: [LuckPerms] Performing initial data load...
[17:52:15 INFO]: [LuckPerms] Successfully enabled. (took 1731ms)
[17:52:15 INFO]: [Vault] Enabling Vault v1.7.3-b131
[17:52:15 WARN]: [Vault] Loaded class com.earth2me.essentials.api.Economy from Essentials v2.19.0 which is not a depend, softdepend or loadbefore of this plugin.
[17:52:15 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[17:52:15 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[17:52:15 INFO]: [Vault] Enabled Version 1.7.3-b131
[17:52:15 INFO]: [LuckPerms] Registered Vault permission & chat hook.
[17:52:15 INFO]: [WorldEdit] Enabling WorldEdit v7.2.7+9f3e795
[17:52:15 INFO]: Registering commands with com.sk89q.worldedit.bukkit.BukkitServerInterface
[17:52:15 INFO]: WEPIF: Vault detected! Using Vault for permissions
[17:52:15 INFO]: Using com.sk89q.worldedit.bukkit.adapter.impl.v1_17_R1_2.PaperweightAdapter as the Bukkit adapter
[17:52:17 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[17:52:17 WARN]: The server will make no attempt to authenticate usernames. Beware.
[17:52:17 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[17:52:17 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[17:52:17 INFO]: Preparing level "world"
[17:52:17 INFO]: Preparing start region for dimension minecraft:overworld
[17:52:18 INFO]: Time elapsed: 300 ms
[17:52:18 INFO]: Preparing start region for dimension minecraft:the_nether
[17:52:18 INFO]: Time elapsed: 168 ms
[17:52:18 INFO]: Preparing start region for dimension minecraft:the_end
[17:52:18 INFO]: Time elapsed: 174 ms
[17:52:18 INFO]: [SimpleRename] Enabling SimpleRename v13.9
[17:52:18 INFO]: SimpleRename enabled!
[17:52:18 INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.1.6
[17:52:18 INFO]: [SkinsRestorer] Using PaperSkinRefresher
[17:52:18 INFO]: [SkinsRestorer] Detected Minecraft v1_17_R1, using PaperSkinRefresher.
[17:52:19 INFO]: [SkinsRestorer] [ACF] Enabled Asynchronous Tab Completion Support!
[17:52:20 INFO]: [WhitelistPlayers] Enabling WhitelistPlayers v1.0.3
[17:52:20 INFO]: [SystemEnchants] Enabling SystemEnchants v3.1.5
[17:52:20 INFO]: [Essentials] Enabling Essentials v2.19.0
[17:52:21 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[17:52:21 INFO]: [Essentials] No kits found to migrate.
[17:52:21 INFO]: [Essentials] Loaded 36837 items from items.json.
[17:52:21 INFO]: [Essentials] Using locale en_US
[17:52:21 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[17:52:21 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[17:52:21 INFO]: [Vault] [Economy] Essentials Economy hooked.
[17:52:21 INFO]: [Essentials] Using Vault based permissions (LuckPerms)
[17:52:21 INFO]: [EssentialsChat] Enabling EssentialsChat v2.19.0
[17:52:21 INFO]: [EssentialsChat] Starting Metrics. Opt-out using the global bStats config.
[17:52:21 INFO]: [WorldGuard] Enabling WorldGuard v7.0.6+1cff55f
[17:52:21 INFO]: [WorldGuard] (world) TNT ignition is PERMITTED.
[17:52:21 INFO]: [WorldGuard] (world) Lighters are PERMITTED.
[17:52:21 INFO]: [WorldGuard] (world) Lava fire is PERMITTED.
[17:52:21 INFO]: [WorldGuard] (world) Fire spread is UNRESTRICTED.
[17:52:21 INFO]: [WorldGuard] Loaded configuration for world 'world'
[17:52:21 INFO]: [WorldGuard] (world_nether) TNT ignition is PERMITTED.
[17:52:21 INFO]: [WorldGuard] (world_nether) Lighters are PERMITTED.
[17:52:21 INFO]: [WorldGuard] (world_nether) Lava fire is PERMITTED.
[17:52:21 INFO]: [WorldGuard] (world_nether) Fire spread is UNRESTRICTED.
[17:52:21 INFO]: [WorldGuard] Loaded configuration for world 'world_nether'
[17:52:21 INFO]: [WorldGuard] (world_the_end) TNT ignition is PERMITTED.
[17:52:21 INFO]: [WorldGuard] (world_the_end) Lighters are PERMITTED.
[17:52:21 INFO]: [WorldGuard] (world_the_end) Lava fire is PERMITTED.
[17:52:21 INFO]: [WorldGuard] (world_the_end) Fire spread is UNRESTRICTED.
[17:52:21 INFO]: [WorldGuard] Loaded configuration for world 'world_the_end'
[17:52:21 INFO]: [WorldGuard] Loading region data...
[17:52:21 INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v8.7.11
[17:52:22 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[17:52:27 INFO]: [AdvancedEnchantments] Successfully hooked into WorldGuard.
[17:52:27 INFO]: [AdvancedEnchantments] Successfully hooked into Essentials.
[17:52:27 INFO]: [AdvancedEnchantments] Loaded 7 armor sets.
[17:52:27 INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[17:52:27 INFO]: [AdvancedEnchantments] Successfully hooked into economy plugin (Vault)
[17:52:27 INFO]: [WanderingTrades] Enabling WanderingTrades v1.6.6
[17:52:28 INFO]: [WanderingTrades] Successfully registered Mojang Brigadier support for commands.
[17:52:28 INFO]: [WanderingTrades] Successfully registered asynchronous command completion listener.
[17:52:28 INFO]: Running delayed init tasks
[17:52:28 INFO]: [Essentials] Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
[17:52:28 INFO]: [Essentials] Fetching version information...
[17:52:28 INFO]: [Vault] Checking for Updates ...
[17:52:28 INFO]: Done (17.652s)! For help, type "help"
[17:52:28 INFO]: Timings Reset
[17:52:28 WARN]: [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.
[17:52:28 INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v8.7.11
[17:52:28 INFO]: [Vault] No new version available
[17:52:28 INFO]: [SkinsRestorer] ----------------------------------------------
[17:52:28 INFO]: [SkinsRestorer]     +==================+
[17:52:28 INFO]: [SkinsRestorer]     |   SkinsRestorer  |
[17:52:28 INFO]: [SkinsRestorer]     |------------------|
[17:52:28 INFO]: [SkinsRestorer]     |  Standalone Mode |
[17:52:28 INFO]: [SkinsRestorer]     +==================+
[17:52:28 INFO]: [SkinsRestorer] ----------------------------------------------
[17:52:28 INFO]: [SkinsRestorer]     Current version: 14.1.6
[17:52:28 INFO]: [SkinsRestorer]     This is the latest version!
[17:52:28 INFO]: [SkinsRestorer] ----------------------------------------------
[17:52:49 INFO]: UUID of player Akusimus is 36f0459b-9063-3fc1-83db-33cf17528fdc
[17:52:49 INFO]: Akusimus joined the game
[17:52:49 INFO]: Akusimus[/192.168.2.177:65433] logged in with entity id 162 at ([world_the_end]999680.5653899672, 235.0, 100116.42067215643)
[17:52:49 WARN]: [Essentials] Permissions lag notice with (LuckPermsHandler). Response took 30.940400ms. Summary: Getting prefix for Akusimus
[17:52:52 INFO]: Akusimus issued server command: /ae
[17:52:52 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ae' in plugin AdvancedEnchantments v8.7.11 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-388]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
> /ae
[17:53:08 INFO]: Unknown command. Type "/help" for help.
>

### How to reproduce

After a while I get this error. Help pls

### "/ae plinfo" link

An internal error occured

**Comment by GC-spigot** [comment]
Hi! Open a ticket on the discord server.
