### ISSUE TITLE
[02:46:40 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.6.16

### ISSUE THREAD

**Issue by AetasAurea** [GC-spigot/AdvancedEnchantments#2514]
### Describe the bug

[02:46:31 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.6.16
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow and org.bukkit.entity.LivingEntity are in unnamed module of loader 'app')
at net.advancedplugins.ae.enchanthandler.enchanttypes.SHIELD_BLOCK.playerHitPlayer(SHIELD_BLOCK.java:39) ~[AdvancedEnchantments-8.6.16.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor630.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1423]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1128) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1002) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:957) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1160) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2097) ~[app:?]
at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1058) ~[app:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1373) ~[app:?]
at net.minecraft.world.entity.player.Player.hurt(Player.java:965) ~[app:?]
at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1033) ~[app:?]
at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:409) ~[app:?]
at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:225) ~[app:?]
at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:216) ~[app:?]
at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[app:?]
at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[app:?]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1204) ~[app:?]
at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:802) ~[app:?]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:781) ~[app:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1649) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1423]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:46:33 INFO]: [] Comerciante MrSach » conterstine
[02:46:33 INFO]: ALEJKHEV issued server command: /kit emperador
[02:46:33 INFO]: Le dio 1x diamond_sword a ALEJKHEV!
[02:46:33 INFO]: Le dio 1x bow a ALEJKHEV!
[02:46:33 INFO]: Thiagomotta8787 issued server command: /warps
[02:46:34 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.6.16
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow and org.bukkit.entity.LivingEntity are in unnamed module of loader 'app')
at net.advancedplugins.ae.enchanthandler.enchanttypes.SHIELD_BLOCK.playerHitPlayer(SHIELD_BLOCK.java:39) ~[AdvancedEnchantments-8.6.16.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor630.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1423]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1128) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1002) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:957) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1160) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2097) ~[app:?]
at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1058) ~[app:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1373) ~[app:?]
at net.minecraft.world.entity.player.Player.hurt(Player.java:965) ~[app:?]
at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1033) ~[app:?]
at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:409) ~[app:?]
at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:225) ~[app:?]
at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:216) ~[app:?]
at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[app:?]
at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[app:?]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1204) ~[app:?]
at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:802) ~[app:?]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:781) ~[app:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1649) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1423]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:46:35 INFO]: [hogwarts] Esclavo jeanmirande12 » buenaso bro
[02:46:35 INFO]: Masquerade issued server command: /tp wir
[02:46:37 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.6.16
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow and org.bukkit.entity.LivingEntity are in unnamed module of loader 'app')
at net.advancedplugins.ae.enchanthandler.enchanttypes.SHIELD_BLOCK.playerHitPlayer(SHIELD_BLOCK.java:39) ~[AdvancedEnchantments-8.6.16.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor630.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1423]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1128) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1002) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:957) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1160) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2097) ~[app:?]
at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1058) ~[app:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1373) ~[app:?]
at net.minecraft.world.entity.player.Player.hurt(Player.java:965) ~[app:?]
at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1033) ~[app:?]
at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:409) ~[app:?]
at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:225) ~[app:?]
at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:216) ~[app:?]
at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[app:?]
at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[app:?]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1204) ~[app:?]
at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:802) ~[app:?]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:781) ~[app:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1649) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1423]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:46:38 INFO]: Thiagomotta8787 issued server command: /minas
[02:46:39 INFO]: [NC+] 64Lagger failed SurvivalFly: tried to perform an illegal move (Subchecks: walkspeed+hspeed) (VL1263)
[02:46:39 INFO]: ALEJKHEV issued server command: /invsee frank7410
[02:46:40 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.6.16
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow cannot be cast to class org.bukkit.entity.LivingEntity (org.bukkit.craftbukkit.v1_17_R1.entity.CraftTippedArrow and org.bukkit.entity.LivingEntity are in unnamed module of loader 'app')
at net.advancedplugins.ae.enchanthandler.enchanttypes.SHIELD_BLOCK.playerHitPlayer(SHIELD_BLOCK.java:39) ~[AdvancedEnchantments-8.6.16.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor630.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Purpur-1423]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1128) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1002) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:957) ~[patched_1.17.1.jar:git-Purpur-1423]
at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1160) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2097) ~[app:?]
at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1058) ~[app:?]
at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1373) ~[app:?]
at net.minecraft.world.entity.player.Player.hurt(Player.java:965) ~[app:?]
at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1033) ~[app:?]
at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:409) ~[app:?]
at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:225) ~[app:?]
at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:216) ~[app:?]
at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:241) ~[app:?]
at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[app:?]
at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1204) ~[app:?]
at net.minecraft.server.level.ServerLevel.lambda$tick$7(ServerLevel.java:802) ~[app:?]
at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:781) ~[app:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1649) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:528) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[patched_1.17.1.jar:git-Purpur-1423]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1423]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

I dont know

### "/ae plinfo" link

https://paste.md-5.net/asalatigil

**Comment by GC-spigot** [comment]
Already fixed, just update.
