### ISSUE TITLE
1.18 Trench 

### ISSUE THREAD

**Issue by XLCx** [GC-spigot/AdvancedEnchantments#2515]
### Describe the bug

Latest version of Paper/AE breaks the Trench enchant and sends this error to console every time a block is mined

```
[11:00:52 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v8.7.17
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_17_R1/util/CraftMagicNumbers
        at net.advancedplugins.ae.utils.AManager.isCorrectTool(AManager.java:159) ~[AdvancedEnchantments-8.7.17.jar:?]
        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1366) ~[AdvancedEnchantments-8.7.17.jar:?]
        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:232) ~[AdvancedEnchantments-8.7.17.jar:?]
        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:260) ~[AdvancedEnchantments-8.7.17.jar:?]
        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:90) ~[AdvancedEnchantments-8.7.17.jar:?]
        at net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:121) ~[AdvancedEnchantments-8.7.17.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor188.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-22]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:400) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:354) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:314) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1678) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1412) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1390) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1383) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1361) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1267) ~[paper-1.18.jar:git-Paper-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.jar:git-Paper-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers
        ... 31 more
```

### How to reproduce

Mine a block with a Trench enchant pickaxe or shovel on latest Advanced Enchantments version

### "/ae plinfo" link

https://paste.md-5.net/jekumevago

**Comment by GC-spigot** [comment]
Fixed
