### ISSUE TITLE
Startup Bug

### ISSUE THREAD

**Issue by Thereaperpeper** [GC-spigot/AdvancedEnchantments#2522]
### Describe the bug

I dont really know how i can explain this properly, but when i start the server up it tells me this: 

[12:05:25] [Server thread/ERROR]: Error occurred while enabling AdvancedEnchantments v8.7.19 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event org.bukkit.event.block.BlockEvent. Static getHandlerList method required!
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:724) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:722) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:722) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:661) ~[patched_1.17.1.jar:git-Paper-391]
	at net.advancedplugins.ae.enchanthandler.hooks.blockregen.BlockRegen.<init>(BlockRegen.java:19) ~[AdvancedEnchantments-8.7.19.jar:?]
	at net.advancedplugins.ae.Core.onEnable(Core.java:335) ~[AdvancedEnchantments-8.7.19.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Paper-391]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[patched_1.17.1.jar:git-Paper-391]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-391]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

As i said, i dont really know how to reproduce this. I dont even know what caused this. I think its a plugin / config that messes with the plugin.

### "/ae plinfo" link

i cant use the command because the plugin is disabled.

**Comment by GC-spigot** [comment]
Issue with BlockRegen, report this to that plugin's developers

**Comment by Thereaperpeper** [comment]
ok, thx!
