### ISSUE TITLE
License exceeded maximum number of unique IP

### ISSUE THREAD

**Issue by PorNetwork** [GC-spigot/AdvancedEnchantments#2561]
### Describe the bug

Hi, recently I have transferred my purchased AE plugin from my private server to dedicated server, which I have experienced with several IP changed. So this made the plugin become disabled in all of my hosted server.

Currently, AE gave me this message during server startup:
`[00:56:49 WARN]: [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.
[00:56:49 INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v8.7.6`

Since the plugin become unusable all command also got disabled and show error in the log when AE command is used.
`[00:57:30] [Server thread/WARN]: Unexpected exception while parsing console command "ae help"
org.bukkit.command.CommandException: Cannot execute command 'ae' in plugin AdvancedEnchantments v8.7.6 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[patched_1.17.1.jar:git-Paper-365]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-365]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-365]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:832) ~[patched_1.17.1.jar:git-Paper-365]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:529) ~[patched_1.17.1.jar:git-Paper-365]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:491) ~[patched_1.17.1.jar:git-Paper-365]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Paper-365]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Paper-365]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-365]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Spigot Profile Page: https://www.spigotmc.org/members/pornetwork.542516/

Server Information:
- paper-1.17.1-365
- paper-1.18.1-108
- AdvancedEnchantments-8.7.6 , 8.7.26 , and 8.7.27
- Java 17

### How to reproduce

-

### Screenshots / Videos

During server startup:
https://cdn.discordapp.com/attachments/876923904772440144/925816568414371870/unknown.png

When command is executed:
https://cdn.discordapp.com/attachments/876923904772440144/925816470380896296/unknown.png

### "/ae plinfo" link

-

### Server Log

https://mcpaste.io/48694ab4ac9693e7

**Comment by GC-spigot** [comment]
Hi, open a ticket on the discord server :)

**Comment by PorNetwork** [comment]
Alright, Thank You! :)
