### ISSUE TITLE
Error spam in console and crashing issues

### ISSUE THREAD

**Issue by Gilthunderx** [GC-spigot/AdvancedEnchantments#2607]
### Describe the bug

Theres been a spam in my console with errors. And I experience some crashing , I suspect its the AE.

this is the error in the console.
`[04:12:27] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v8.2.5
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.entity.CraftSkeleton cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_16_R3.entity.CraftSkeleton and org.bukkit.entity.Player are in unnamed module of loader 'app')
	at net.advancedplugins.ae.enchanthandler.enchanttypes.BOW_MOB.onProjectileHitEvent(BOW_MOB.java:41) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor872.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-12]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:257) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1091) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:978) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:934) ~[patched_1.16.5.jar:git-Airplane-12]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1123) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1948) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1263) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.EntityMonster.damageEntity(EntityMonster.java:74) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.EntityArrow.a(EntityArrow.java:371) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.IProjectile.a(IProjectile.java:150) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.IProjectile.preOnHit(IProjectile.java:141) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.EntityArrow.tick(EntityArrow.java:214) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.EntityTippedArrow.tick(EntityTippedArrow.java:108) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:1502) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:1132) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1557) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1407) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139) ~[patched_1.16.5.jar:git-Airplane-12]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Airplane-12]
	at java.lang.Thread.run(Thread.java:831) [?:?]`
	
	I Also placed the crash log and theres something ae related cause of crash

### How to reproduce

When a player kills a player with an custom enchant, there are some times it crashes. For the error spam in console is just random .

### "/ae plinfo" link

https://paste.md-5.net/kunoyokupu

### Server Log

https://mcpaste.io/f99ddc31d8066bca

**Comment by GC-spigot** [comment]
Update to a version not months old
