### ISSUE TITLE
Config Error [LEGACY BUILD]

### ISSUE THREAD

**Issue by Blazaddo** [GC-spigot/AdvancedEnchantments#2619]
### Describe the bug

Forces paper to use legacy version slowing everything down.

### How to reproduce

Run a paper server with debug mode on.

### Screenshots / Videos

[15:16:25 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[15:16:25 WARN]: java.lang.Exception
[15:16:25 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.legacy.CraftLegacy.<clinit>(CraftLegacy.java:260)
[15:16:25 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.util.CraftMagicNumbers.fromLegacy(CraftMagicNumbers.java:221)
[15:16:25 WARN]:        at org.bukkit.Material.getMaterial(Material.java:5205)
[15:16:25 WARN]:        at org.bukkit.Material.matchMaterial(Material.java:5250)
[15:16:25 WARN]:        at AdvancedEnchantments-8.7.24.jar//net.advancedplugins.ae.Core.onEnable(Core.java:285)
[15:16:25 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:16:25 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:16:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[15:16:25 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:563)
[15:16:25 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:477)
[15:16:25 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727)
[15:16:25 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503)
[15:16:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:313)
[15:16:25 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1202)
[15:16:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[15:16:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

### "/ae plinfo" link

https://paste.md-5.net/ezexehihal

### Server Log

https://mcpaste.io/deb4747d448c5d6f

**Comment by GC-spigot** [comment]
It's required for AE to run - it doesn't slow "everything down", just adds legacy material support
