### ISSUE TITLE
Error in console when shooting (mostly) flying mobs with HOMING effect

### ISSUE THREAD

**Issue by NeuTraLZero** [GC-spigot/AdvancedEnchantments#2635]
### Describe the bug

When an enchantment with HOMING effect homes in on (mostly) Phantoms and Ghasts the console prints out an error but the projectile still home in normally
```
[20:38:07] [Server thread/WARN]: [AdvancedEnchantments] Task #580322 for AdvancedEnchantments v8.8.9 generated an exception
--
java.lang.IllegalArgumentException: x not finite
at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.util.Vector.checkFinite(Vector.java:814) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.entity.CraftEntity.setVelocity(CraftEntity.java:444) ~[purpur-1.18.1.jar:git-Purpur-1551]
at net.advancedplugins.ae.enchanthandler.effects.Homing$1.run(Homing.java:51) ~[AdvancedEnchantments-8.8.9.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1551]
at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.18.1.jar:git-Purpur-1551]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1578) ~[purpur-1.18.1.jar:git-Purpur-1551]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1551]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1501) ~[purpur-1.18.1.jar:git-Purpur-1551]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1551]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1551]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### How to reproduce

Example enchantment
```
predator:
  display: "&7Predator"
  description: "Homes in on enemy"
  applies-to: "Crossbow"
  type: "BOW_SHOOT"
  group: "EPIC"
  applies:
    - CROSSBOW
  levels:
    1:
      effects:
        - "HOMING:48:1:2"
```
I've tried changing projectile speed from 2-3 already but the console still print out the same error

### "/ae plinfo" link

https://paste.md-5.net/izuvenibub

### Server Log

https://mcpaste.io/0f353e7444242118

**Comment by Burchard36** [comment]
https://user-images.githubusercontent.com/48583030/166232108-5c98b284-8bde-4296-8939-42a6f6767f93.mp4

Tried this enchantment and it seemed to work fine for me, can you try this on the most recent version of AE and see if the bug still persists?

Apologies for the late response! This issue was open long before i started working here :)

**Comment by Burchard36** [comment]
Side note: Also tried this with ghasts, no console errors

**Comment by Burchard36** [comment]
Closing due to no response, if you still have this issue please open a new ticket referancing this one :)
