### ISSUE TITLE
Error in console with villager

### ISSUE THREAD

**Issue by srfabric** [GC-spigot/AdvancedEnchantments#2662]
### Describe the bug

[14:52:21 INFO]: Failed to generate AdvancedEnchantments Random Loot for item RANDOM_ENCHANT_BOOK: error is located in console. 
[14:52:21 INFO]: It is most likely a configuration issue and this item's configuration should be checked before reporting.
[14:52:21 ERROR]: Could not pass event VillagerAcquireTradeEvent to AdvancedEnchantments v8.8.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because "<parameter1>" is null
        at net.advancedplugins.ae.handlers.lootPopulation.PopulationHandler.getVillagerTradeItem(PopulationHandler.java:138) ~[AdvancedEnchantments-8.8.8.jar:?]
        at net.advancedplugins.ae.handlers.lootPopulation.listeners.VillagerLootPopulator.onVillagerAcquireTradeEvent(VillagerLootPopulator.java:29) ~[AdvancedEnchantments-8.8.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1220.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1560]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.npc.AbstractVillager.addOffersFromItemListings(AbstractVillager.java:289) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.updateTrades(Villager.java:1077) ~[?:?]
        at net.minecraft.world.entity.npc.AbstractVillager.getOffers(AbstractVillager.java:130) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.needsToRestock(Villager.java:521) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.shouldRestock(Villager.java:559) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.WorkAtPoi.start(WorkAtPoi.java:58) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.WorkAtPoi.canStillUse(WorkAtPoi.java:18) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.Behavior.tryStart(Behavior.java:61) ~[purpur-1.18.1.jar:git-Purpur-1560]
        at net.minecraft.world.entity.ai.behavior.GateBehavior$RunningPolicy$1.apply(GateBehavior.java:120) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.GateBehavior.start(GateBehavior.java:56) ~[?:?]
        at net.minecraft.world.entity.ai.behavior.Behavior.tryStart(Behavior.java:61) ~[purpur-1.18.1.jar:git-Purpur-1560]
        at net.minecraft.world.entity.ai.Brain.startEachNonRunningBehavior(Brain.java:511) ~[?:?]
        at net.minecraft.world.entity.ai.Brain.tick(Brain.java:470) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.mobTick(Villager.java:355) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.customServerAiStep(Villager.java:336) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:900) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.aiStep(LivingEntity.java:3342) ~[?:?]
        at net.minecraft.world.entity.Mob.aiStep(Mob.java:659) ~[?:?]
        at net.minecraft.world.entity.AgeableMob.aiStep(AgeableMob.java:154) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:2992) ~[?:?]
        at net.minecraft.world.entity.Mob.tick(Mob.java:421) ~[?:?]
        at net.minecraft.world.entity.npc.Villager.tick(Villager.java:405) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1219) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:698) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:43) ~[purpur-1.18.1.jar:git-Purpur-1560]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:676) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1639) ~[purpur-1.18.1.jar:git-Purpur-1560]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:519) ~[purpur-1.18.1.jar:git-Purpur-1560]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1501) ~[purpur-1.18.1.jar:git-Purpur-1560]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1285) ~[purpur-1.18.1.jar:git-Purpur-1560]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1560]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

It produce with the activation of Villagers trade

### "/ae plinfo" link

https://paste.md-5.net/cezamewoma

**Comment by GC-spigot** [comment]
Fixed
