### ISSUE TITLE
Problem with bow enchantments

### ISSUE THREAD

**Issue by Fenor-NG** [GC-spigot/AdvancedEnchantments#2690]
### Describe the bug

My bows enchantments won't work since a week, i just have restart my server and then, it won't works (on myself, other player and mobs). I think that i have probably updated my AE before the restart. I tested on a fresh server without any plugin and it won't work. (bow full power is false on my config)

### How to reproduce

Enchants your bow with hellfire or explosive (i only have that two) and shoot yourself/a player or a mob.

### "/ae plinfo" link

https://paste.md-5.net/eribomovaf

### Server Log

https://mcpaste.io/dfcda8b8d18b30af

**Comment by Fenor-NG** [comment]
java.lang.Exception: Stack trace
[17:08:33 WARN]:        at java.lang.Thread.dumpStack(Thread.java:1336)
[17:08:33 WARN]:        at net.advancedplugins.ae.enchanthandler.enchanttypes.HELD.executeCheck(HELD.java:222)
[17:08:33 WARN]:        at net.advancedplugins.ae.enchanthandler.enchanttypes.HELD.executeCheck(HELD.java:187)
[17:08:33 WARN]:        at net.advancedplugins.ae.enchanthandler.enchanttypes.HELD.onItemSwitchEvent(HELD.java:141)
[17:08:33 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:08:33 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:08:33 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:08:33 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[17:08:33 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[17:08:33 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:08:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[17:08:33 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[17:08:33 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:931)
[17:08:33 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInHeldItemSlot.a(SourceFile:30)
[17:08:33 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInHeldItemSlot.a(SourceFile:8)
[17:08:33 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[17:08:33 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:08:33 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:08:33 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[17:08:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[17:08:33 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[17:08:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[17:08:33 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[17:08:33 WARN]:        at java.lang.Thread.run(Thread.java:748)

After update to the lastest version (8.9.4) i have this error

**Comment by Burchard36** [comment]
This bug is now fixed, update to the latest version

Sorry for the delay!
