### ISSUE TITLE
Error report of held items after updating to 8.9.3

### ISSUE THREAD

**Issue by MCTGE** [GC-spigot/AdvancedEnchantments#2693]
### Describe the bug

After updating to 8.9.3 I have started getting console reports that I do not fully understand, however, they seem to be related to enchants on help items. I have tried the latest version 8.9.4 and even reverted to 8.9.2-1, to see if that resolved the issue but it did not.

I have not touched any files in the plugin in ages and am using one of the provided enchant packs. 

`[17.03 11:31:02] [Server] [WARN] java.lang.Exception: Stack trace
[17.03 11:31:02] [Server] [WARN]     at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
[17.03 11:31:02] [Server] [WARN]     at AdvancedEnchantments-8.9.4.jar//net.advancedplugins.ae.enchanthandler.enchanttypes.HELD.executeCheck(HELD.java:222)
[17.03 11:31:02] [Server] [WARN]     at AdvancedEnchantments-8.9.4.jar//net.advancedplugins.ae.enchanthandler.enchanttypes.HELD.executeCheck(HELD.java:187)
[17.03 11:31:02] [Server] [WARN]     at AdvancedEnchantments-8.9.4.jar//net.advancedplugins.ae.enchanthandler.enchanttypes.HELD.onItemSwitchEvent(HELD.java:141)
[17.03 11:31:02] [Server] [WARN]     at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1215.execute(Unknown Source)
[17.03 11:31:02] [Server] [WARN]     at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75)
[17.03 11:31:02] [Server] [WARN]     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[17.03 11:31:02] [Server] [WARN]     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17.03 11:31:02] [Server] [WARN]     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:631)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2141)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.network.protocol.game.PacketPlayInHeldItemSlot.a(PacketPlayInHeldItemSlot.java:24)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.network.protocol.game.PacketPlayInHeldItemSlot.a(PacketPlayInHeldItemSlot.java:6)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.server.TickTask.run(TickTask.java:18)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1426)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1403)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1396)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1374)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1256)
[17.03 11:31:02] [Server] [WARN]     at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320)
[17.03 11:31:02] [Server] [WARN]     at java.base/java.lang.Thread.run(Thread.java:833)`

### How to reproduce

All I did was update.

### "/ae plinfo" link

https://paste.md-5.net/limuporele

### Server Log

https://mclo.gs/wNOrkaC

**Comment by GC-spigot** [comment]
Should be fixed
