### ISSUE TITLE
HELD error spam after updating to 8.9.4

### ISSUE THREAD

**Issue by mare-on** [GC-spigot/AdvancedEnchantments#2694]
### Describe the bug

**Server version:** Paper 1.18.2 build 259
**Issue:** Brutal spam in server console...

[17-03-2022 19:15:46] java.lang.Exception: Stack trace
[17-03-2022 19:15:46] at java.base/java.lang.Thread.dumpStack(Thread.java:1380)
[17-03-2022 19:15:46] at AdvancedEnchantments-8.9.4.jar//net.advancedplugins.ae.enchanthandler.enchanttypes.HELD.executeCheck(HELD.java:222)
[17-03-2022 19:15:46] at AdvancedEnchantments-8.9.4.jar//net.advancedplugins.ae.enchanthandler.enchanttypes.HELD.executeCheck(HELD.java:187)
[17-03-2022 19:15:46] at AdvancedEnchantments-8.9.4.jar//net.advancedplugins.ae.enchanthandler.enchanttypes.HELD.onInvClick(HELD.java:93)
[17-03-2022 19:15:46] at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[17-03-2022 19:15:46] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17-03-2022 19:15:46] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17-03-2022 19:15:46] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629)
[17-03-2022 19:15:46] at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2860)
[17-03-2022 19:15:46] at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[17-03-2022 19:15:46] at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:13)
[17-03-2022 19:15:46] at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[17-03-2022 19:15:46] at net.minecraft.server.TickTask.run(TickTask.java:18)
[17-03-2022 19:15:46] at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[17-03-2022 19:15:46] at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:23)
[17-03-2022 19:15:46] at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1399)
[17-03-2022 19:15:46] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[17-03-2022 19:15:46] at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[17-03-2022 19:15:46] at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1376)
[17-03-2022 19:15:46] at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1369)
[17-03-2022 19:15:46] at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[17-03-2022 19:15:46] at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1347)
[17-03-2022 19:15:46] at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1229)
[17-03-2022 19:15:46] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[17-03-2022 19:15:46] at java.base/java.lang.Thread.run(Thread.java:833)

### How to reproduce

Just update to version 8.9.4 and restart the server.

### "/ae plinfo" link

https://paste.md-5.net/sazakibahe

**Comment by Cheezelaweeze** [comment]
I am also having this issue.

**Comment by mare-on** [comment]
Should be fixed with the latest version :)
