### ISSUE TITLE
ADD_HARM not working for armorsets

### ISSUE THREAD

**Issue by Hermelijn15** [GC-spigot/AdvancedEnchantments#2717]
### Describe the bug

ADD_HARM not working for armorsets

### How to reproduce

have add harm as one of the efffects of an armor set, in my testing i tried "ATTACK" as the trigger

### Screenshots / Videos

[17:16:07] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getUniqueId()" because "targetList" is null
[17:16:07] [Server thread/WARN]: 	at AdvancedEnchantments-8.9.9(1).jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:340)
[17:16:07] [Server thread/WARN]: 	at AdvancedEnchantments-8.9.9(1).jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:238)
[17:16:07] [Server thread/WARN]: 	at AdvancedEnchantments-8.9.9(1).jar//net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:267)
[17:16:07] [Server thread/WARN]: 	at AdvancedEnchantments-8.9.9(1).jar//net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:93)
[17:16:07] [Server thread/WARN]: 	at AdvancedEnchantments-8.9.9(1).jar//net.advancedplugins.ae.features.sets.SetsManager.handleEffectTrigger(SetsManager.java:162)
[17:16:07] [Server thread/WARN]: 	at AdvancedEnchantments-8.9.9(1).jar//net.advancedplugins.ae.features.sets.SetsManager.triggerEvent(SetsManager.java:77)
[17:16:07] [Server thread/WARN]: 	at AdvancedEnchantments-8.9.9(1).jar//net.advancedplugins.ae.enchanthandler.enchanttypes.ATTACK.playerHitPlayer(ATTACK.java:51)
[17:16:07] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor483.execute(Unknown Source)
[17:16:07] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[17:16:07] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:16:07] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:16:07] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[17:16:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:248)
[17:16:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1121)
[17:16:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:997)
[17:16:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:953)
[17:16:07] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1153)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2042)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.damageEntity0(EntityHuman.java:1018)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.damageEntity(EntityLiving.java:1350)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.damageEntity(EntityHuman.java:925)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.damageEntity(EntityPlayer.java:998)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.attack(EntityHuman.java:1261)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.attack(EntityPlayer.java:2019)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2492)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2419)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[17:16:07] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:16:07] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[17:16:07] [Server thread/INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getUniqueId()" because "targetList" is null
[17:16:07] [Server thread/INFO]: [AdvancedEnchantments]    Class: AdvancedEnchantments-8.9.9(1).jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:340)
[17:16:07] [Server thread/INFO]: [AdvancedEnchantments]    Extra info: effect[ADD_HARM:1000]; Armor Set [Koth]; mc[1170]; ae[8.9.9]
[17:16:07] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 

### "/ae plinfo" link

https://paste.md-5.net/ohavuxiciz

### Server Log

https://mcpaste.io/2cdcb5b9b2a6763a

**Comment by Burchard36** [comment]
Hey there, can you send the ArmorSet configuration please so I can replicate this exactly please :)

**Comment by Hermelijn15** [comment]
yes ofc, here you go:

# Advanced Sets
# These sets are fully creatable, to create your own simply copy this file, rename it and edit it however you want!

# ** Set Materials:
# * LEATHER (change-able color) https://github.com/GC-spigot/AdvancedEnchantments/wiki/Æ-Colored-Leather-Armor
# * IRON
# * GOLD
# * CHAIN
# * DIAMOND

# ** Enchantment effects are supported - view enchantments.yml to see all effects available for sets.

#  ** Set Events
#    Change upon what event should sets trigger
#    - EFFECT_STATIC : Gives permanent potion effect (as long as armor piece is worn)
#    - ATTACK : Set Event run only when attacking another player
#    - DEFENSE : Set Event run only when being attacked
#    - DEFENSE_BOW : Set Event run only when player gets shot by a bow
#    - MINING : Gives effects when block is mined
#    - ATTACK_MOB : Gives effects when player attacks mob
#    - KILL_MOB : Effects given when attacked mob is killed
#    - BOW : Effects given when player is shot by another player
#    - KILL_PLAYER : Effects given when attacker kills a player
#    - DEATH : Runs when player dies due to another player.
#    - RIGHT_CLICK : Runs when player right clicks held item
#    - BOW_MOB : Effects given when mob is shot by player
#    - FIRE : Effects given when player is on fire
#    - EXPLOSION : Effects given when player gets hit by explosion
#    - SWING : Enchant runs when player swings
#    - FALL_DAMAGE : Set Event runs when player takes fall damage
#    - DEFENSE_MOB : Set Event runs when mob attacks a player
#    - SHIFT : Set Event runs when player toggles crouching (shifts)
#    - ITEM_BREAK : Set Event runs when player toggles crouching (shifts)
#    - CATCH_FISH : Set Event runs when player catches a fish
# Set Events & Enchant types are intercompatible together

# ** Creating set effects, this explains the system
#events:
#  <any of the effects from the list>:
#    chance: <chance of effects activating, 1-100> (Optional)
#    cooldown: <cooldown period after effects activate, in seconds> (Optional)
#    effects: <effects are available in enchantments.yml>
#    # E.g.: - 'INCREASED_DAMAGE:10'

name: '&d&lKOTH Armor'
material: DIAMOND
settings:
  equipped:
    - '&a&l(!) &aYou have activated the KOTH set!'
  unequipped:
    - '&c&l(!) &cYou have deactivated the KOTH set!'
items:
  helmet:
    name: '&f&l&ki &c&lK&6&l.&e&lO&2&l.&b&lT&5&l.&d&lH &f&l&nHelmet &f&l&ki'
    customModelData: 0
    itemFlags: []
    lore:
      - ''
      - '&d&lKOTH SET BONUS'
      - '&d&l* &d1 Damage each hit'
      - '&d&l* &dCure negative effects'
      - '&d&l* &dNo Fall Damage'
      - '&7&o(Requires all 4 koth items.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:6"
      - "unbreaking:3"
      - "aqua_affinity:1"
  chestplate:
    name: '&f&l&ki &c&lK&6&l.&e&lO&2&l.&b&lT&5&l.&d&lH &f&l&nChestplate &f&l&ki'
    customModelData: 0
    itemFlags: []
    lore:
      - ''
      - '&d&lKOTH SET BONUS'
      - '&d&l* &d1 Damage each hit'
      - '&d&l* &dCure negative effects'
      - '&d&l* &dNo Fall Damage'
      - '&7&o(Requires all 4 koth items.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:6"
      - "unbreaking:3"
  leggings:
    name: '&f&l&ki &c&lK&6&l.&e&lO&2&l.&b&lT&5&l.&d&lH &f&l&nLeggings &f&l&ki'
    customModelData: 0
    itemFlags: []
    #  - 'HIDE_POTION_EFFECTS' # An Example Item Flag
    lore:
      - ''
      - '&d&lKOTH SET BONUS'
      - '&d&l* &d1 Damage each hit'
      - '&d&l* &dCure negative effects'
      - '&d&l* &dNo Fall Damage'
      - '&7&o(Requires all 4 koth items.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:6"
      - "unbreaking:3"
  boots:
    name: '&f&l&ki &c&lK&6&l.&e&lO&2&l.&b&lT&5&l.&d&lH &f&l&nBoots &f&l&ki'
    customModelData: 0
    itemFlags: []
    lore:
      - ''
      - '&d&lKOTH SET BONUS'
      - '&d&l* &d1 Damage each hit'
      - '&d&l* &dCure negative effects'
      - '&d&l* &dNo Fall Damage'
      - '&7&o(Requires all 4 koth items.)'
    enchants: # Supports AdvancedEnchantments CE
      - "protection:6"
      - "unbreaking:3"
      - "feather_falling:4"
      - "depth_strider:3"
events:
  ATTACK:
    chance: 100
    effects:
      - 'ADD_HARM:1000 %victim%'
      - 'MESSAGE:&a&l** test **'
  FALL_DAMAGE:
    chance: 100
    effects:
      - 'STOP_ATTACK'
  SWING:
    chance: 100
    effects:
      - 'CURE_PERMANENT:SLOW %attacker%'
      - 'CURE_PERMANENT:CONFUSION %attacker%'
      - 'CURE_PERMANENT:BLINDNESS %attacker%'
      - 'CURE_PERMANENT:POISON %attacker%'
      - 'CURE_PERMANENT:WITHER %attacker%'
      - 'CURE_PERMANENT:HUNGER %attacker%'
      - 'CURE_PERMANENT:WEAKNESS %attacker%'
      - 'CURE_PERMANENT:SLOW_DIGGING %attacker%'

**Comment by Hermelijn15** [comment]
the msg part (test) does work

**Comment by Hermelijn15** [comment]
i also just saw that part of my msg got formatted a bit wierd, if i should send it in another way let me know
