### ISSUE TITLE
EXTINGUISH not working for armour

### ISSUE THREAD

**Issue by ryankayz7** [GC-spigot/AdvancedEnchantments#2719]
### Describe the bug

The extinguish enchantment seems to be failing to parse in the latest version (8.9.10). Console printed the information under here and chat showed the message I have attached in a picture. 

[01:42:15 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getUniqueId()" because "<local1>" is null
[01:42:15 WARN]:        at AdvancedEnchantments-8.9.10.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:340)
[01:42:15 WARN]:        at AdvancedEnchantments-8.9.10.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:234)
[01:42:15 WARN]:        at AdvancedEnchantments-8.9.10.jar//net.advancedplugins.ae.enchanthandler.ProcessEnchantment$1.run(ProcessEnchantment.java:276)
[01:42:15 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[01:42:15 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[01:42:15 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1578)
[01:42:15 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:519)
[01:42:15 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1501)
[01:42:15 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1285)
[01:42:15 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322)
[01:42:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[01:42:15 INFO]: [AdvancedEnchantments ERROR] Could not pass NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getUniqueId()" because "<local1>" is null
[01:42:15 INFO]: [AdvancedEnchantments]    Class: AdvancedEnchantments-8.9.10.jar//net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:340)
[01:42:15 INFO]: [AdvancedEnchantments]    Extra info: effect[EXTINGUISH:]; enchant [extinguish]; mc[1180]; ae[8.9.10]
[01:42:15 INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 

An example of the enchant that produces this on my server is:

extinguish:
  display: "%group-color%Extinguish"
  description: "Chance to extinguish yourself\nwhen on fire."
  applies-to: "Leggings"
  type: "DEFENSE;DEFENSE_MOB;FIRE"
  group: "NETHERITE"
  applies:
    - ALL_LEGGINGS
  levels:
    1:
      chance: 20
      effects:
        - "WAIT:1"
        - "EXTINGUISH %victim%"
    2:
      chance: 60
      effects:
        - "WAIT:1"
        - "EXTINGUISH %victim%"
    3:
      chance: 80
      effects:
        - "WAIT:1"
        - "EXTINGUISH %victim%"

### How to reproduce

Add an enchantment with the EXTINGUISH effect on it to an armour piece, try to wear the armour piece and light yourself on fire and the enchantment is unable to parse.

### Screenshots / Videos

https://gyazo.com/adb3d4e0c31ff85b7b505ed202aad1e7

### "/ae plinfo" link

https://paste.md-5.net/iniqobatay

**Comment by Burchard36** [comment]
Hello this issue is resolved in 8.9.11, but it hasnt been released as we are waiting for GC to push this to github/the website

Apologies for the inconvenience

**Comment by ryankayz7** [comment]
Appreciate it!
