### ISSUE TITLE
TRENCH Console error

### ISSUE THREAD

**Issue by juancruzdal** [GC-spigot/AdvancedEnchantments#2726]
### Describe the bug

[AdvancedEnchantments ERROR] Could not pass NullPointerException: 
[13:05:35] [Server thread/INFO]: [AdvancedEnchantments]    Class: net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1465)
[13:05:35] [Server thread/INFO]: [AdvancedEnchantments]    Extra info: effect[TRENCH:3]; enchant [explosion]; mc[183]; ae[8.9.10]
[13:05:35] [Server thread/INFO]: [AdvancedEnchantments] If you cannot indentify cause of this, contact developer providing this report. 
[13:05:35] [Server thread/WARN]: java.lang.NullPointerException
[13:05:35] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:1465)
[13:05:35] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:238)
[13:05:35] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:267)
[13:05:35] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:93)
[13:05:35] [Server thread/WARN]: 	at net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:134)
[13:05:35] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor496.invoke(Unknown Source)
[13:05:35] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[13:05:35] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[13:05:35] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[13:05:35] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
[13:05:35] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[13:05:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
[13:05:35] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502)
[13:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:295)
[13:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:189)
[13:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40)
[13:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10)
[13:05:35] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:05:35] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[13:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:741)
[13:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366)
[13:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:680)
[13:05:35] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:583)
[13:05:35] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)

### How to reproduce

Mine a block with a pickaxe with TRENCH

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/35972023/161588513-7fbe8621-40d3-447f-9e2c-b32e39f9dd75.png)

### "/ae plinfo" link

https://paste.md-5.net/iqicuwuhuh

### Server Log

https://pastebin.com/RdUBRDLm

**Comment by juancruzdal** [comment]
Solution: Issue with AutoSell drop2inv
