### ISSUE TITLE
SPAMMING slimefun connection problem

### ISSUE THREAD

**Issue by DextralityNetwork** [GC-spigot/AdvancedEnchantments#2738]
### Describe the bug

Hello guys, I have a problem with the plugin what happens is that it generates problems with the Slimefun plugin, I don't know if you could fix that instance.

### How to reproduce

Install the latest versions of Slimefun and AdvancedEnchantments add-on.
Run the server.
Spamming will appear.

### Screenshots / Videos

[22:40:49 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v8.9.10
java.lang.IllegalStateException: Cannot invoke static method, Slimefun instance is null.
        at io.github.thebusybiscuit.slimefun4.implementation.Slimefun.validateInstance(Slimefun.java:713) ~[Slimefun4 - DEV 966 (git ab8f2).jar:?]
        at io.github.thebusybiscuit.slimefun4.implementation.Slimefun.getBlockDataService(Slimefun.java:809) ~[Slimefun4 - DEV 966 (git ab8f2).jar:?]
        at me.mrCookieSlime.Slimefun.api.BlockStorage.checkID(BlockStorage.java:725) ~[Slimefun4 - DEV 966 (git ab8f2).jar:?]
        at me.mrCookieSlime.Slimefun.api.BlockStorage.check(BlockStorage.java:707) ~[Slimefun4 - DEV 966 (git ab8f2).jar:?]
        at net.advancedplugins.ae.enchanthandler.enchanttypes.MINING.onBlockBreak(MINING.java:76) ~[AdvancedEnchantments-8.9.10.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor997.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:402) ~[app:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:356) ~[app:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:291) ~[app:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1740) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1477) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1284) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1477) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1284) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1477) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1284) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1740) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:8) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1477) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1284) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### "/ae plinfo" link

https://paste.md-5.net/ijeyejirul

**Comment by Burchard36** [comment]
Hello, I am unable to reproduce this bug on my end.

Are you sure SlimeFun didn't have an error on startup? The only time that you would receive that null error is if slimefun isnt installed or it disabled itself due to a crash

**Comment by Burchard36** [comment]
Hey there, I ran into this bug randomly on my server, and when looking at the error there are 2 more lines that wasn't included in your error:

```YAML
[20:54:00] [Craft Scheduler Thread - 15/WARN]: [Slimefun] Attempted to refresh skin cache, got this response: TimeoutException: null
[20:54:00] [Craft Scheduler Thread - 15/WARN]: [Slimefun] This usually means mojang.com is temporarily down or started to rate-limit this connection, nothing to worry about!
```

This is a SlimeFun error, you'll need to contact them and figure out what the issue is on theyre end, though the error explains it quite well
