### ISSUE TITLE
Items cannot pass anvil enchant

### ISSUE THREAD

**Issue by QingSongYaya** [GC-spigot/AdvancedEnchantments#2765]
### Describe the bug

[02:52:33] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to AdvancedEnchantments v8.9.17
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1453) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.ContainerAnvil.l(ContainerAnvil.java:287) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:80) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:25) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.Slot.d(SourceFile:66) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.Slot.a(SourceFile:45) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.Container.lambda$5(Container.java:549) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.world.inventory.Container.b(Container.java:547) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.Container.a(Container.java:366) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2435) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:55) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:11) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1124) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: fr/andross/banitem/BanItemAPI
        at net.advancedplugins.ae.handlers.anvil.AnvilEvent.onAnvil(AnvilEvent.java:106) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor673.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        ... 28 more
[02:52:33] [Server thread/ERROR]: Could not pass event PrepareAnvilEvent to AdvancedEnchantments v8.9.17
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1453) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.ContainerAnvil.l(ContainerAnvil.java:287) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:80) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.ContainerAnvilAbstract$1.update(ContainerAnvilAbstract.java:25) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.Slot.d(SourceFile:66) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.Container.b(Container.java:570) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.world.inventory.Container.a(Container.java:366) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2435) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:55) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:11) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1148) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1141) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(SourceFile:110) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1124) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1054) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NoClassDefFoundError: fr/andross/banitem/BanItemAPI
        at net.advancedplugins.ae.handlers.anvil.AnvilEvent.onAnvil(AnvilEvent.java:106) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor673.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.17.1.jar:3284-Spigot-3892929-0ebef35]
        ... 25 more

### How to reproduce

There are errors in enchanting. Put the weapon on the iron felt and drag the enchant book

### "/ae plinfo" link

https://paste.md-5.net/laporiwiti

**Comment by Burchard36** [comment]
What do your players do to achieve this bug? I need some more information on how to replicate this

I'm not quite sure what put the weapon on the item felt and drag the enchanting book, Do you mean to apply a enchant book to an item in an anvil?

**Comment by QingSongYaya** [comment]
The problem has been solved, but there is a new problem that items cannot be taken out of the anvil

**Comment by QingSongYaya** [comment]
> 你的玩家做了什么来解决这个错误？我需要更多关于如何复制它的信息
> 
> 我不太清楚将武器放在物品上感觉并拖动附魔书，您的意思是在铁砧中将附魔书应用到物品上？
The problem has been solved, but there is a new problem that items cannot be taken out of the anvil

**Comment by Burchard36** [comment]
Can you send a video please?

**Comment by QingSongYaya** [comment]
[#](https://873753763.oss-cn-beijing.aliyuncs.com/shiping/2022-05-06%2016-43-13.mp4)

**Comment by QingSongYaya** [comment]
https://873753763.oss-cn-beijing.aliyuncs.com/shiping/2022-05-06%2016-43-13.mp4

**Comment by HikkaKun** [comment]
@Burchard36 same issue - item cannot be taken out of the anvil
https://paste.md-5.net/nojiqigodi
![image](https://user-images.githubusercontent.com/44067398/174403985-66e5422d-8de4-43e5-b8be-8c606a6d4d74.png)

**Comment by GC-spigot** [comment]
Issue with BanItem plugin - try removing it, it's no longer supported
