### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by dicepvp** [GC-spigot/AdvancedEnchantments#2891]
### Describe the bug

a issue on block break

### How to reproduce

install the plugin and protocallib latest version
possibly install winespigot
break a block

### Screenshots / Videos

none

### "/ae plinfo" link

https://paste.md-5.net/akadoteber

### Server Log

[15:53:00] [Server thread/ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v8.11.1 net.advancedplugins.ae.utils.nbt.backend.NbtApiException: Exception while getting an Itemstack's NBTCompound! 	at net.advancedplugins.ae.utils.nbt.backend.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:120) ~[?:?] 	at net.advancedplugins.ae.utils.nbt.backend.NBTItem.getCompound(NBTItem.java:18) ~[?:?] 	at net.advancedplugins.ae.utils.nbt.backend.NBTReflectionUtil.getData(NBTReflectionUtil.java:570) ~[?:?] 	at net.advancedplugins.ae.utils.nbt.backend.NBTCompound.hasKey(NBTCompound.java:131) ~[?:?] 	at net.advancedplugins.ae.utils.nbt.NBTapi.getInt(NBTapi.java:278) ~[?:?] 	at net.advancedplugins.ae.features.souls.SoulsAPI.getSoulsOnItem(SoulsAPI.java:36) ~[?:?] 	at net.advancedplugins.ae.features.souls.SoulsAPI.addSouls(SoulsAPI.java:62) ~[?:?] 	at net.advancedplugins.ae.items.item.BlockTrack.onBreak(BlockTrack.java:57) ~[?:?] 	at org.bukkit.plugin.DirectEventExecutor.execute(DirectEventExecutor.java:31) ~[server.jar:1_8_R3] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:1_8_R3] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:1_8_R3] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:569) ~[server.jar:1_8_R3] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:515) ~[server.jar:1_8_R3] 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:431) ~[server.jar:1_8_R3] 	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:253) ~[server.jar:1_8_R3] 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:768) ~[server.jar:1_8_R3] 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:28) ~[server.jar:1_8_R3] 	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:1) ~[server.jar:1_8_R3] 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:34) ~[server.jar:1_8_R3] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312] 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:11) [server.jar:1_8_R3] 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:944) [server.jar:1_8_R3] 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:371) [server.jar:1_8_R3] 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:869) [server.jar:1_8_R3] 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:759) [server.jar:1_8_R3] 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312] Caused by: java.lang.NullPointerException 	at net.advancedplugins.ae.utils.nbt.backend.ReflectionMethod.run(ReflectionMethod.java:237) ~[?:?] 	at net.advancedplugins.ae.utils.nbt.backend.NBTReflectionUtil.getItemRootNBTTagCompound(NBTReflectionUtil.java:117) ~[?:?] 	... 26 more

**Comment by GC-spigot** [comment]
Fixed
