### ISSUE TITLE
NPE while using enchanter command

### ISSUE THREAD

**Issue by TerrrorByte** [GC-spigot/AdvancedEnchantments#2892]
### Describe the bug

When holding an item, the /enchanter command does not work. When holding "air" you get a NPE. 
```
[15:53:29 INFO]: TerrorByte issued server command: /enchanter:enchanter
[15:53:29 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'enchanter:enchanter' in net.advancedplugins.ae.handlers.commands.EnchanterCommand(enchanter)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.18.2.jar:git-Paper-377]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2307) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2118) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2099) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-377]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-377]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-377]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-377]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-377]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.setDisplayName(String)" because "this.im" is null
        at net.advancedplugins.ae.utils.ItemBuilder.setName(ItemBuilder.java:196) ~[AdvancedEnchantments-8.11.4.jar:?]
        at net.advancedplugins.ae.utils.ConfigItemCreator.fromConfigSection(ConfigItemCreator.java:69) ~[AdvancedEnchantments-8.11.4.jar:?]
        at net.advancedplugins.ae.utils.ConfigItemCreator.fromConfigSection(ConfigItemCreator.java:181) ~[AdvancedEnchantments-8.11.4.jar:?]
        at net.advancedplugins.ae.features.enchanter.Enchanter.updateInventory(Enchanter.java:102) ~[AdvancedEnchantments-8.11.4.jar:?]
        at net.advancedplugins.ae.features.enchanter.Enchanter.openForPlayer(Enchanter.java:61) ~[AdvancedEnchantments-8.11.4.jar:?]
        at net.advancedplugins.ae.handlers.commands.EnchanterCommand.execute(EnchanterCommand.java:43) ~[AdvancedEnchantments-8.11.4.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```

### How to reproduce

Hold a sword or enchantable item in your hand. Run /enchanter. It does not work (Verified **enchanter** is enabled in config)
Hold nothing in your hand and do /enchanter. You will receive an error in console, and in game you will receive the "An internal error has occured" message.

### "/ae plinfo" link

https://paste.md-5.net/xacohekedo

**Comment by GC-spigot** [comment]
Fixed the error, but this is likely coming from an invalid enchanter configuration - check all the items and materials in the gui
