### ISSUE TITLE
Console error Spam

### ISSUE THREAD

**Issue by lChrisjm** [GC-spigot/AdvancedEnchantments#2946]
### Describe the bug

Got my console spammed by an error related whit InventoryClickEvent.

### How to reproduce

- Use advanced enchantments in a 1.18 server.
- Just startup the sever or click in /enchanter items

### Screenshots / Videos

![image](https://user-images.githubusercontent.com/43703371/178147197-ed614bb0-e1d3-43d5-b50a-e4a688880e1d.png)

### "/ae plinfo" link

https://paste.md-5.net/iyulaxezux

### Server Log

https://bin.bloom.host/sukujeruna

**Comment by Awpmeister2170** [comment]
Hello, can you please open a ticket Via our discord and send us over your Config file?

**Comment by Gabris060** [comment]
Having the same exact issue

```
16.07 16:24:24 [Server] ERROR Could not pass event PlayerInteractEvent to AdvancedEnchantments v8.12.4
16.07 16:24:24 [Server] INFO java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "<parameter1>" is null
16.07 16:24:24 [Server] INFO at net.advancedplugins.ae.utils.AManager.matchMaterial(AManager.java:308) ~[AdvancedEnchantments-8.12.4.jar:?]
16.07 16:24:24 [Server] INFO at net.advancedplugins.ae.utils.AManager.matchMaterial(AManager.java:302) ~[AdvancedEnchantments-8.12.4.jar:?]
16.07 16:24:24 [Server] INFO at net.advancedplugins.ae.utils.ItemBuilder.<init>(ItemBuilder.java:99) ~[AdvancedEnchantments-8.12.4.jar:?]
16.07 16:24:24 [Server] INFO at net.advancedplugins.ae.items.item.MobTracker.build(MobTracker.java:35) ~[AdvancedEnchantments-8.12.4.jar:?]
16.07 16:24:24 [Server] INFO at net.advancedplugins.ae.items.AEItem.onInteractEvent(AEItem.java:33) ~[AdvancedEnchantments-8.12.4.jar:?]
16.07 16:24:24 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor823.execute(Unknown Source) ~[?:?]
16.07 16:24:24 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
16.07 16:24:24 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
16.07 16:24:24 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
16.07 16:24:24 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:507) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:502) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:498) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at net.minecraft.server.network.ServerGamePacketListenerImpl.handleAnimate(ServerGamePacketListenerImpl.java:2345) ~[?:?]
16.07 16:24:24 [Server] INFO at net.minecraft.network.protocol.game.ServerboundSwingPacket.handle(ServerboundSwingPacket.java:25) ~[?:?]
16.07 16:24:24 [Server] INFO at net.minecraft.network.protocol.game.ServerboundSwingPacket.a(ServerboundSwingPacket.java:11) ~[?:?]
16.07 16:24:24 [Server] INFO at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
16.07 16:24:24 [Server] INFO at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
16.07 16:24:24 [Server] INFO at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
16.07 16:24:24 [Server] INFO at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
16.07 16:24:24 [Server] INFO at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
16.07 16:24:24 [Server] INFO at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1348) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1230) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
16.07 16:24:24 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Gabris060** [comment]
Tried the latest (8.12.8) and it still shows the same. It also spams this very frequently. Another thing to mention is that Magic Dust does not apply to a book by dragging and dropping.
```
22.07 18:52:49 [Server] ERROR Could not pass event PlayerInteractEvent to AdvancedEnchantments v8.12.8
22.07 18:52:49 [Server] INFO java.lang.NullPointerException: null
```

**Comment by Awpmeister2170** [comment]
Fixed please update
