### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by zidziyad** [GC-spigot/AdvancedEnchantments#2958]
### Describe the bug

[23:27:41 INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v8.12.6
[23:27:42 ERROR]: [STDERR] [org.bukkit.craftbukkit.v1_19_R1.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[23:27:46 ERROR]: Error occurred while enabling AdvancedEnchantments v8.12.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/advancedplugins/heads/Core
at net.advancedplugins.ae.utils.lang.Lang.init(Lang.java:40) ~[AdvancedEnchantments.jar:?]
at net.advancedplugins.ae.Core.onEnable(Core.java:289) ~[AdvancedEnchantments.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:594) ~[purpur-1.19.jar:git-Purpur-1715]
at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:508) ~[purpur-1.19.jar:git-Purpur-1715]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[purpur-1.19.jar:git-Purpur-1715]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[purpur-1.19.jar:git-Purpur-1715]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.19.jar:git-Purpur-1715]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[purpur-1.19.jar:git-Purpur-1715]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[purpur-1.19.jar:git-Purpur-1715]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.advancedplugins.heads.Core
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.19-R0.1-SNAPSHOT.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
... 13 more

### How to reproduce

while enable 

### "/ae plinfo" link

the plugin wan't enable to do this command

**Comment by Awpmeister2170** [comment]
Fixed update to latest version :)
