### ISSUE TITLE
NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs

### ISSUE THREAD

**Issue by PeterMa9621** [GC-spigot/AdvancedEnchantments#2993]
### Describe the bug

I got lots of errors from my console, it seems the latest version of MythicMobs is not supported correctly.
```
[03:43:03] [Server thread/ERROR]: Could not pass event EntityDeathEvent to AdvancedEnchantments v8.13.9
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
	at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:600) ~[AdvancedEnchantments-8.13.9.jar:?]
	at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:239) ~[AdvancedEnchantments-8.13.9.jar:?]
	at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:267) ~[AdvancedEnchantments-8.13.9.jar:?]
	at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:93) ~[AdvancedEnchantments-8.13.9.jar:?]
	at net.advancedplugins.ae.enchanthandler.enchanttypes.KILL_MOB.onMobDeath(KILL_MOB.java:70) ~[AdvancedEnchantments-8.13.9.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor896.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-379]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:876) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1726) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1624) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1452) ~[?:?]
	at net.minecraft.world.entity.player.Player.attack(Player.java:1278) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2040) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl$5.a(ServerGamePacketListenerImpl.java:2541) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2468) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-379]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
	... 36 more
```
=

### How to reproduce

I don't have a clear way to recreate this issue, but it's obvious that the latest version of MythicMob is not supported correctly.

### "/ae plinfo" link

https://paste.md-5.net/siwivayequ

**Comment by Awpmeister2170** [comment]
Updating the API for next update.
