### ISSUE TITLE
Commands issue

### ISSUE THREAD

**Issue by Restland** [GC-spigot/AdvancedEnchantments#3030]
### Describe the bug

when someone executes command any command of AE this is the outcome on the console
[19:23:21 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'enchanter' in net.advancedplugins.ae.handlers.commands.EnchanterCommand(enchanter)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:911) ~[paper-1.19.2.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.2.jar:git-Paper-131]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.2.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:305) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:289) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2298) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2252) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1360) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1337) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1330) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1464) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.2.jar:git-Paper-131]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-131]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.advancedplugins.ae.handlers.commands.EnchanterCommand.execute(EnchanterCommand.java:43) ~[AdvancedEnchantments-8.14.8.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 22 more

### How to reproduce

Use any AE command

### "/ae plinfo" link

Can't execute the command

### Server Log

https://mcpaste.io/9d43798bbff968f6

**Comment by Awpmeister2170** [comment]
open a ticket on discord - AdvancedEnchantments/WARN]: [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.
