### ISSUE TITLE
Console spam leading to server crash

### ISSUE THREAD

**Issue by TypicalShavonne** [GC-spigot/AdvancedEnchantments#3046]
### Describe the bug

The console spam this error continiously 
`[13:55:40 ERROR]: Could not pass event InventoryClickEvent to AdvancedEnchantments v8.15.4
java.lang.IndexOutOfBoundsException: Index 8114 out of bounds for length 46
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at net.minecraft.core.NonNullList.get(NonNullList.java:47) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.world.inventory.AbstractContainerMenu.getSlot(AbstractContainerMenu.java:362) ~[app:?]
        at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftInventoryView.getItem(CraftInventoryView.java:64) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at org.bukkit.event.inventory.InventoryClickEvent.getCurrentItem(InventoryClickEvent.java:102) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.advancedplugins.ae.items.AEItem.onInventoryClick(AEItem.java:61) ~[AdvancedEnchantments-8.15.4.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1071.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:2808) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:55) ~[app:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:11) ~[app:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1428) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1399) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[app:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1538) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1284) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[patched_1.17.1.jar:git-Pufferfish-22]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

### How to reproduce

Im not sure

### "/ae plinfo" link

https://paste.md-5.net/tonafugevu

**Comment by GC-spigot** [comment]
Could you post your whole server log?
