### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by SrT3ddy** [GC-spigot/AdvancedEnchantments#3127]
### Describe the bug

[13:51:28 ERROR]: Could not pass event EntityDeathEvent to AdvancedEnchantments v9.0.0b45
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:615) ~[AdvancedEnchantments-9.0.0b46.jar:?]
        at net.advancedplugins.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:244) ~[AdvancedEnchantments-9.0.0b46.jar:?]
        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:288) ~[AdvancedEnchantments-9.0.0b46.jar:?]
        at net.advancedplugins.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:111) ~[AdvancedEnchantments-9.0.0b46.jar:?]
        at net.advancedplugins.ae.enchanthandler.enchanttypes.KILL_MOB.onMobDeath(KILL_MOB.java:72) ~[AdvancedEnchantments-9.0.0b46.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1933.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:git-Purpur-1857]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:678) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:887) ~[purpur-1.19.2.jar:git-Purpur-1857]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1820) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1715) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1530) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:354) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1372) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2205) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:3081) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:3000) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1857]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1857]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1857]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1857]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1857]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1857]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1857]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1857]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
        ... 37 more

### How to reproduce

Use: https://prnt.sc/wB25vUCenH1g

### Screenshots / Videos

https://prnt.sc/wB25vUCenH1g

### "/ae plinfo" link

https://paste.md-5.net/iyozupizip

**Comment by reussy** [comment]
Hello @SrT3ddy  👋

You could try updating MythicMobs to the latest version and see if it still happens?

**Comment by SrT3ddy** [comment]
still happens

**Comment by hkkongou** [comment]
still happening v9.0.0b75
same thing as #2993
but seems not solved
