### ISSUE TITLE
AdvancedEnchantments API createEnchantmentBook method is broken.

### ISSUE THREAD

**Issue by goosBanny** [GC-spigot/AdvancedEnchantments#3175]
### Describe the bug

```java
org.bukkit.command.CommandException: Unhandled exception executing command 'disench' in plugin Disenchanter v1.0-SNAPSHOT
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[pufferfish-1.19.3.jar:git-Pufferfish-53]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[pufferfish-1.19.3.jar:git-Pufferfish-53]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[pufferfish-1.19.3.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2287) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2249) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.3.jar:git-Pufferfish-53]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1343) ~[pufferfish-1.19.3.jar:git-Pufferfish-53]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.19.3.jar:git-Pufferfish-53]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1320) ~[pufferfish-1.19.3.jar:git-Pufferfish-53]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1313) ~[pufferfish-1.19.3.jar:git-Pufferfish-53]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1291) ~[pufferfish-1.19.3.jar:git-Pufferfish-53]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[pufferfish-1.19.3.jar:git-Pufferfish-53]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[pufferfish-1.19.3.jar:git-Pufferfish-53]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'org.bukkit.inventory.ItemStack net.advancedplugins.ae.api.AEAPI.createEnchantmentBook(java.lang.String, int, int, int)'
	at me.goosbanny.disenchanter.commands.CommandHandler.removeEnchant(CommandHandler.java:95) ~[Disenchanter-1.0-SNAPSHOT.jar:?]
	at me.goosbanny.disenchanter.commands.CommandHandler.playerDisenchantCommand(CommandHandler.java:57) ~[Disenchanter-1.0-SNAPSHOT.jar:?]
	at me.goosbanny.disenchanter.commands.CommandHandler.onCommand(CommandHandler.java:36) ~[Disenchanter-1.0-SNAPSHOT.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[pufferfish-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more
```

### How to reproduce

Use the createEnchantmentBook() method.

### "/ae plinfo" link

https://paste.md-5.net/paxuwuhoya

**Comment by reussy** [comment]
Hey @goosBanny,

Please share the code with us to check for API misuse. These same methods are used by the **AdvanvedEnchantment** code base and do not throw these errors.

If the code is private, you can share it to my private `reussy#0877`

**Comment by goosBanny** [comment]
```java
int levels = AEAPI.getEnchantLevel(String, inHand);
ItemStack item = AEAPI.createEnchantmentBook(enchStr, levels, 100, 0);```

That's everything related to AEAPI used in the plugin. In an older ticket, GC said that the API's method required a 5th paramater "player". He never resolved that issue though.

**Comment by reussy** [comment]
> ```java
> int levels = AEAPI.getEnchantLevel(String, inHand);
> ItemStack item = AEAPI.createEnchantmentBook(enchStr, levels, 100, 0);
> ```
> 
> That's everything related to AEAPI used in the plugin. In an older ticket, GC said that the API's method required a 5th paramater "player". He never resolved that issue though.

Hey @goosBanny,

You seem to be missing the Player parameter at the end of the AEAPI#createEnchantmentBook method.
```java
ItemStack item = AEAPI.createEnchantmentBook(enchStr, levels, 100, 0, player);
```

I guess you are using the outdated API, there is really a lot of misinformation about the API usage tho, **could you please let me know how you use it**.

**Comment by goosBanny** [comment]
I resolved the issue by just using the AE jar instead of AEAPI. Adding 'player' worked. We good!

**Comment by reussy** [comment]
@Awpmeister2170 hey man, we're good, you can close this!
