### ISSUE TITLE
Console spammed with "Could not pass event PlayerInteractEvent to AdvancedEnchantments v9.0.0b75

### ISSUE THREAD

**Issue by hnair2001** [GC-spigot/AdvancedEnchantments#3200]
### Describe the bug

My console gets spammed with this error. It doesn't really cause any damage to the server but it is annoying while trying to look through the console logs.

[15:43:28 ERROR]: Could not pass event PlayerInteractEvent to AdvancedEnchantments v9.0.0b75
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.getType()" because the return value of "net.advancedplugins.ae.utils.AManager.matchMaterial(String, int, int)" is null
        at net.advancedplugins.ae.utils.ItemBuilder.<init>(ItemBuilder.java:90) ~[AdvancedEnchantments-9.0.0b75.jar:?]
        at net.advancedplugins.ae.items.item.SlotIncreaser.build(SlotIncreaser.java:83) ~[AdvancedEnchantments-9.0.0b75.jar:?]
        at net.advancedplugins.ae.items.AEItem.onInteractEvent(AEItem.java:33) ~[AdvancedEnchantments-9.0.0b75.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor221.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-386]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:528) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1959) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

From what I have seen this error code pops up when ever any tool is used.

### Screenshots / Videos

![Screenshot 2023-03-01 143155](https://user-images.githubusercontent.com/123564351/222260965-ae428751-ce52-47ab-9abb-0af87651331f.png)

![Screenshot 2023-03-01 144711](https://user-images.githubusercontent.com/123564351/222261409-20868cc6-d609-410f-ad25-d360d28f9ae2.png)

### "/ae plinfo" link

https://paste.md-5.net/mukukocefo

**Comment by reussy** [comment]
Hey @hnair2001,

This is possibly due to an error with the configuration (a missing value), the best thing to do is to save a backup of your current configuration and then let the plugin recreate the file. 
If you have more questions or need help, open a ticket in our Discord! 🙌
