### ISSUE TITLE
I used radmin so it happend 2 years ago and i can't find any help and i found the way to reply.

### ISSUE THREAD

**Issue by Xalfrost** [GC-spigot/AdvancedEnchantments#3210]
### Describe the bug

[AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs.
[12:26:51] [Craft Scheduler Thread - 4/INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v9.0.0b76
[12:26:51] [Craft Scheduler Thread - 4/ERROR]: Error occurred (in the plugin loader) while disabling AdvancedEnchantments v9.0.0b76 (Is it up to date?)
java.lang.IllegalStateException: PluginDisableEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.advancedplugins.ae.Core$2.run(Core.java:694) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3669-Spigot-454acb7-f150cfb]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3669-Spigot-454acb7-f150cfb]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:26:51] [Craft Scheduler Thread - 4/ERROR]: Error occurred (in the plugin loader) while unregistering services for AdvancedEnchantments v9.0.0b76 (Is it up to date?)
java.lang.IllegalStateException: ServiceUnregisterEvent cannot be triggered asynchronously from another thread.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimpleServicesManager.unregisterAll(SimpleServicesManager.java:100) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:513) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.advancedplugins.ae.Core$2.run(Core.java:694) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3669-Spigot-454acb7-f150cfb]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3669-Spigot-454acb7-f150cfb]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

I buy this plugin long ago and this is my user name is [Syn_Xalfrost]

### "/ae plinfo" link

(https://www.spigotmc.org/members/syn_xalfrost.1041959/)

**Comment by reussy** [comment]
@Awpmeister2170

**Comment by Awpmeister2170** [comment]
Hello, please join our discord and open a ticket, we can assist you there with this problem :)
