### ISSUE TITLE
unknown unary operator

### ISSUE THREAD

**Issue by kingakis2** [GC-spigot/AdvancedEnchantments#3247]
### Describe the bug

pickaxes with any enchantment will not drop items, the enchantments don't work and error or warning appears on console

### How to reproduce

use 9.0.3 enchant pickaxe and test it

### Screenshots / Videos

[16:27:40 WARN]: net.advancedplugins.ae.impl.utils.evalex.Expression$ExpressionException: Unknown unary operator % at character position 1
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.utils.evalex.Expression.shuntingYard(Expression.java:1321)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.utils.evalex.Expression.getRPN(Expression.java:1778)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.utils.evalex.Expression.eval(Expression.java:1411)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.utils.evalex.Expression.eval(Expression.java:1397)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.utils.ASManager.parseThroughCalculator(ASManager.java:561)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.functions.interval.MathFunction.parse(MathFunction.java:16)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.functions.FunctionsHandler.parseEffectLine(FunctionsHandler.java:41)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:142)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:112)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68)
[16:27:40 WARN]:        at AdvancedEnchantments-9.0.3.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.KillMobTrigger.onMobDeath(KillMobTrigger.java:56)
[16:27:40 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1060.execute(Unknown Source)
[16:27:40 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[16:27:40 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[16:27:40 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[16:27:40 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[16:27:40 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[16:27:40 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[16:27:40 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:895)
[16:27:40 WARN]:        at net.minecraft.world.entity.EntityLiving.dropAllDeathLoot(EntityLiving.java:1756)
[16:27:40 WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1653)
[16:27:40 WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1480)
[16:27:40 WARN]:        at net.minecraft.world.entity.monster.EntityZombie.a(EntityZombie.java:318)
[16:27:40 WARN]:        at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1319)
[16:27:40 WARN]:        at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2115)
[16:27:40 WARN]:        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2866)
[16:27:40 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[16:27:40 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[16:27:40 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2790)
[16:27:40 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[16:27:40 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[16:27:40 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[16:27:40 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:27:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:27:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:27:40 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1342)
[16:27:40 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[16:27:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[16:27:40 WARN]:        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1319)
[16:27:40 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1312)
[16:27:40 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[16:27:40 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1290)
[16:27:40 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1178)
[16:27:40 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[16:27:40 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:27:40 WARN]: Failed to calculate '%exp%*(1.0+0.25*%level%)': Invalid syntax or outcome

### "/ae plinfo" link

https://paste.md-5.net/zopesupiqa

**Comment by GC-spigot** [comment]
This error is not related to pickaxes at all, we'll fix this error - but that's why we ask for server logs, in your case we have nothing to help you with for pickaxes
