### ISSUE TITLE
Trench bug in 9.1.0

### ISSUE THREAD

**Issue by theabdel572** [GC-spigot/AdvancedEnchantments#3331]
### Describe the bug

hey, i have installed the 9.1.0 version of the plugin and now everytime someone uses trench the console throws this error

### How to reproduce

Just get a trench pickaxe and mine with it. I think it is related to the factions hook.

```java
[21:54:43 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.1.0
java.lang.NoSuchMethodError: 'com.massivecraft.factions.struct.Relation com.massivecraft.factions.FPlayer.getRelationToLocation()'
        at net.advancedplugins.ae.impl.utils.hooks.plugins.FactionsUUIDHook.getRelationOfLand(FactionsUUIDHook.java:30) ~[AdvancedEnchantments-9.1.0.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.protection.external.FactionsCheck.canBreak(FactionsCheck.java:24) ~[AdvancedEnchantments-9.1.0.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.protection.ProtectionHandler.lambda$canBreak$0(ProtectionHandler.java:45) ~[AdvancedEnchantments-9.1.0.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1800) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.protection.ProtectionHandler.canBreak(ProtectionHandler.java:45) ~[AdvancedEnchantments-9.1.0.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:131) ~[AdvancedEnchantments-9.1.0.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:71) ~[AdvancedEnchantments-9.1.0.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:78) ~[AdvancedEnchantments-9.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1732.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1908]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:266) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1952) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1472) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
``` 

### Screenshots / Videos

https://media.discordapp.net/attachments/1103785114175013034/1103785334652805241/image.png

https://media.discordapp.net/attachments/1103785114175013034/1103785373752107058/image.png

### "/ae plinfo" link

https://paste.md-5.net/iwanepoxej

**Comment by theabdel572** [comment]
I've just realised that the problem it's not only with the trench enchantment, but with some others too.
Water Walker doesn't work, almost the same error:
```java
[10:00:38 ERROR]: Could not pass event PlayerMoveEvent to AdvancedEnchantments v9.1.0
java.lang.NoSuchMethodError: 'com.massivecraft.factions.struct.Relation com.massivecraft.factions.FPlayer.getRelationToLocation()'
        at net.advancedplugins.ae.impl.utils.hooks.plugins.FactionsUUIDHook.getRelationOfLand(FactionsUUIDHook.java:30) ~[AdvancedEnchantments-9.1.0.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.effects.internal.WaterWalkerEffect.checkAndSet(WaterWalkerEffect.java:97) ~[AdvancedEnchantments-9.1.0.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.effects.internal.WaterWalkerEffect.scanBlocks(WaterWalkerEffect.java:92) ~[AdvancedEnchantments-9.1.0.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.effects.internal.WaterWalkerEffect.onMove(WaterWalkerEffect.java:61) ~[AdvancedEnchantments-9.1.0.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1181.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:git-Purpur-1908]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:680) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1661) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:66) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1908]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
