### ISSUE TITLE
Console error from more drops and mobs 9.1.8

### ISSUE THREAD

**Issue by CrystallizedAtrophy** [GC-spigot/AdvancedEnchantments#3374]
### Describe the bug

[22:46:50 ERROR]: Could not pass event EntityDeathEvent to AdvancedEnchantments v9.1.8
java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
        at net.advancedplugins.ae.impl.utils.hooks.plugins.MythicMobsHook.isMythicMob(MythicMobsHook.java:23) ~[AdvancedEnchantments-9.1.8.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.effects.internal.MoreDropsEffect.executeEffect(MoreDropsEffect.java:31) ~[AdvancedEnchantments-9.1.8.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:176) ~[AdvancedEnchantments-9.1.8.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:111) ~[AdvancedEnchantments-9.1.8.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54) ~[AdvancedEnchantments-9.1.8.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68) ~[AdvancedEnchantments-9.1.8.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.KillMobTrigger.onMobDeath(KillMobTrigger.java:57) ~[AdvancedEnchantments-9.1.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor894.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1967]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:904) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at net.minecraft.world.entity.LivingEntity.dropAllDeathLoot(LivingEntity.java:1814) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.die(LivingEntity.java:1709) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1524) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:355) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1359) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2232) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$6.a(ServerGamePacketListenerImpl.java:2962) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2884) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1967]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
        ... 41 more

### How to reproduce

Use diploid with 100% chance to proc and kill mobs. Also still not taking souls as currency....

### Screenshots / Videos

https://youtu.be/sLamPv1nLOE

### "/ae plinfo" link

https://paste.md-5.net/ruhowerexo

### Server Log

https://mcpaste.io/e55268b9cf88e2d9

**Comment by aXe18** [comment]
![Screenshot_1666](https://github.com/GC-spigot/AdvancedEnchantments/assets/26152540/eefe381c-b0ee-4cbc-8f56-38e4f03e334d)
![Screenshot_1665](https://github.com/GC-spigot/AdvancedEnchantments/assets/26152540/f02c6cfa-86a0-4e59-ba6e-058b8500f34b)

I got plus these on latest, all works still

**Comment by GC-spigot** [comment]
Fixed
