### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v9.1.9

### ISSUE THREAD

**Issue by justtos** [GC-spigot/AdvancedEnchantments#3379]
### Describe the bug

We updated AdvancedEnchantments from `9.0.0b76` to `9.1.9` and redid the enchantments, but the following error logged when a player hits a player.

```
[12:29:30] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v9.1.9
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.ae.impl.effects.effects.abilities.AdvancedAbility.getCooldown()" because "<local9>" is null
	at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.build(ActionExecution.java:127) ~[AdvancedEnchantments-9.1.9.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:67) ~[AdvancedEnchantments-9.1.9.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ShootTrigger.onProjectileHitEvent(ShootTrigger.java:78) ~[AdvancedEnchantments-9.1.9.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1010.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1976]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:252) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1192) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1049) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:992) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1226) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2220) ~[?:?]
	at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1098) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1427) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:1005) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1124) ~[?:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:403) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:214) ~[?:?]
	at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:205) ~[?:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:297) ~[?:?]
	at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:233) ~[?:?]
	at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1293) ~[?:?]
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:755) ~[?:?]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:732) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1575) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1976]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### How to reproduce

The steps we did as update:
1. Backup our enchantments
2. Full update of AdvancedEnchantments to 9.1.9
3. Redownload Basic and Cosmic premades and modify rarities and remove unneeded enchants per our backup

As for the error, just have a player hit another player.

### Screenshots / Videos

Test sword: https://prnt.sc/6AfKDzIOc6Z-
*please, disregard the double "Items Slots" message, this has been resolved*

### "/ae plinfo" link

https://paste.md-5.net/zonozufewu

### Server Log

Will provide if proven necessary.

**Comment by GC-spigot** [comment]
Are you using default config files? Cause misconfiguration / enchant not loading is the most likely reason of this issue

**Comment by justtos** [comment]
I have done some testing and figured out that this is caused if you have an item with a higher enchant level than available.
Could I a suggest for a proper error to be added telling you this is the case?

**Comment by GC-spigot** [comment]
Fixed next update
