### ISSUE TITLE
Could not pass event ProjectileHitEvent to AdvancedEnchantments v9.1.10

### ISSUE THREAD

**Issue by aXe18** [GC-spigot/AdvancedEnchantments#3383]
### Describe the bug

After 9.1.10 update, when ever i use fireworks, this error comes to console many times.

[18:49:59 ERROR]: Could not pass event ProjectileHitEvent to AdvancedEnchantments v9.1.10
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getWorld()" because the return value of "net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.getMain()" is null
        at net.advancedplugins.ae.abilities.ItemEnchantsReader.getRawAbilities(ItemEnchantsReader.java:31) ~[AdvancedEnchantments-9.1.10.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.build(ActionExecutionBuilder.java:75) ~[AdvancedEnchantments-9.1.10.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:57) ~[AdvancedEnchantments-9.1.10.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ArrowHitTrigger.onConsume(ArrowHitTrigger.java:48) ~[AdvancedEnchantments-9.1.10.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor913.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-538]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callProjectileHitEvent(CraftEventFactory.java:1469) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:172) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:296) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:232) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1210) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:926) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:731) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:711) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1546) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

Update to 9.1.10 and use my plugin list ?

### "/ae plinfo" link

https://paste.md-5.net/osaxexiror

**Comment by GC-spigot** [comment]
Resolved next update
