### ISSUE TITLE
Error on console

### ISSUE THREAD

**Issue by xcoolerboy** [GC-spigot/AdvancedEnchantments#3391]
### Describe the bug

[05:25:06 WARN]: [AdvancedEnchantments] Failed to parse 3<aoe>radius=4target=damageable</aoe> from String to Integer.
[05:25:06 WARN]: java.lang.NumberFormatException: For input string: "3<aoe>radius=4target=damageable</aoe>"
[05:25:06 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
[05:25:06 WARN]:        at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[05:25:06 WARN]:        at java.base/java.lang.Double.parseDouble(Double.java:556)
[05:25:06 WARN]:        at net.advancedplugins.ae.impl.utils.ASManager.parseInt(ASManager.java:529)
[05:25:06 WARN]:        at net.advancedplugins.ae.impl.utils.ASManager.parseInt(ASManager.java:519)
[05:25:06 WARN]:        at net.advancedplugins.ae.impl.effects.effects.effects.internal.BurnEffect.executeEffect(BurnEffect.java:18)
[05:25:06 WARN]:        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:176)
[05:25:06 WARN]:        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:111)
[05:25:06 WARN]:        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54)
[05:25:06 WARN]:        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68)
[05:25:06 WARN]:        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.JumpTrigger.onJump(JumpTrigger.java:38)
[05:25:06 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1414.execute(Unknown Source)
[05:25:06 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[05:25:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[05:25:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[05:25:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[05:25:06 WARN]:        at org.bukkit.event.Event.callEvent(Event.java:45)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1350)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[05:25:06 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[05:25:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
[05:25:06 ERROR]: Could not pass event ProjectileHitEvent to AdvancedEnchantments v9.1.10
java.lang.NullPointerException: null
[05:25:06 ERROR]: Could not pass event ProjectileHitEvent to AdvancedEnchantments v9.1.10
java.lang.NullPointerException: null
[05:25:06 ERROR]: Could not pass event ProjectileHitEvent to AdvancedEnchantments v9.1.10
java.lang.NullPointerException: null
[05:25:06 ERROR]: Could not pass event ProjectileHitEvent to AdvancedEnchantments v9.1.10
java.lang.NullPointerException: null
[05:25:06 ERROR]: Could not pass event ProjectileHitEvent to AdvancedEnchantments v9.1.10
java.lang.NullPointerException: null

### How to reproduce

its spamming

### "/ae plinfo" link

https://paste.md-5.net/ejateculov

**Comment by GC-spigot** [comment]
Check your configuration, this is definitely on it. Some `JUMP` trigger enchantment area of effect problem. You can find more info here: https://wiki.advancedplugins.net/abilities/targets @Aoe
