### ISSUE TITLE
Bug When Enable Plugin.

### ISSUE THREAD

**Issue by thinh2118** [GC-spigot/AdvancedEnchantments#3403]
### Describe the bug

java.lang.NoSuchMethodException: net.minecraft.world.entity.EntityInsentient.D()
[13:36:03] [Server thread/WARN]: 	at java.base/java.lang.Class.getMethod(Class.java:2227)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:173)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:186)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:191)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<clinit>(ReflectionMethod.java:142)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.setString(NBTCompound.java:36)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.impl.utils.nbt.NBTapi.addNBTTag(NBTapi.java:15)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.impl.utils.items.ItemBuilder.addNBTTag(ItemBuilder.java:384)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.items.item.RandomizationScroll.<init>(RandomizationScroll.java:19)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.items.ItemLoader.loadInternalItems(ItemLoader.java:52)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.items.ItemLoader.<init>(ItemLoader.java:26)
[13:36:03] [Server thread/WARN]: 	at AdvancedEnchantments.jar//net.advancedplugins.ae.Core.onEnable(Core.java:259)
[13:36:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:36:03] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:36:03] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[13:36:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[13:36:03] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[13:36:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[13:36:03] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[13:36:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[13:36:03] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[13:36:03] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

### How to reproduce

Papermc 1.17.1

### Screenshots / Videos

.

### "/ae plinfo" link

.

**Comment by GC-spigot** [comment]
Fixed!
