### ISSUE TITLE
Error occurred while enabling AdvancedEnchantments v9.2.1

### ISSUE THREAD

**Issue by BlueBlueO3O** [GC-spigot/AdvancedEnchantments#3409]
### Describe the bug

`[21:30:30 ERROR]: Error occurred while enabling AdvancedEnchantments v9.2.1 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:838) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:511) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:466) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:159) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:104) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:207) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:122) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.TriggerHandler.<init>(TriggerHandler.java:38) ~[?:?]
	at net.advancedplugins.ae.impl.effects.effects.EffectsHandler.<init>(EffectsHandler.java:65) ~[?:?]
	at net.advancedplugins.ae.Core.onEnable(Core.java:255) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.lenni0451.spm.utils.PluginUtils.enablePlugin(PluginUtils.java:131) ~[?:?]
	at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:262) ~[?:?]
	at net.lenni0451.spm.commands.subs.Load_Sub.execute(Load_Sub.java:55) ~[?:?]
	at net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94) ~[?:?]
	at net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:844) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:312) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:296) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1919) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1133) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1110) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3755-Spigot-7d7b241-b346a5f]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
`

### How to reproduce

Start the server with the plugin

### "/ae plinfo" link

none due to error

**Comment by GC-spigot** [comment]
Hey it seems like you are trying to load AE with a plugin manager plugin, try updating and restarting
