### ISSUE TITLE
Elytra Doesn't go with "REMOVE_ARMOR"

### ISSUE THREAD

**Issue by KingCueio** [GC-spigot/AdvancedEnchantments#3413]
### Describe the bug

I was thinking that Elytra should be included as "REMOVE_ARMOR:<ARMOR TYPE>"

Since Elytra is in the config of "chest-plate"
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/87959487/22cdd2df-89c0-4e05-8800-5e6b36e966ba)

### How to reproduce

[04:48:25 WARN]: java.lang.IllegalArgumentException: No enum constant net.advancedplugins.ae.impl.effects.armorutils.ArmorType.ELYTRA
[04:48:25 WARN]:        at java.base/java.lang.Enum.valueOf(Enum.java:273)
[04:48:25 WARN]:        at AdvancedEnchantments-9.1.9.jar//net.advancedplugins.ae.impl.effects.armorutils.ArmorType.valueOf(ArmorType.java:17)
[04:48:25 WARN]:        at AdvancedEnchantments-9.1.9.jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.RemoveArmorEffect.executeEffect(RemoveArmorEffect.java:25)
[04:48:25 WARN]:        at AdvancedEnchantments-9.1.9.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:176)
[04:48:25 WARN]:        at AdvancedEnchantments-9.1.9.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:111)
[04:48:25 WARN]:        at AdvancedEnchantments-9.1.9.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54)
[04:48:25 WARN]:        at AdvancedEnchantments-9.1.9.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68)
[04:48:25 WARN]:        at AdvancedEnchantments-9.1.9.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.AttackTrigger.playerHitMob(AttackTrigger.java:54)
[04:48:25 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1140.execute(Unknown Source)
[04:48:25 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[04:48:25 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[04:48:25 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[04:48:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[04:48:25 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:247)
[04:48:25 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1122)
[04:48:25 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:998)
[04:48:25 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:954)
[04:48:25 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1154)
[04:48:25 WARN]:        at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2064)
[04:48:25 WARN]:        at net.minecraft.world.entity.player.EntityHuman.damageEntity0(EntityHuman.java:1018)
[04:48:25 WARN]:        at net.minecraft.world.entity.EntityLiving.damageEntity(EntityLiving.java:1350)
[04:48:25 WARN]:        at net.minecraft.world.entity.player.EntityHuman.damageEntity(EntityHuman.java:925)
[04:48:25 WARN]:        at net.minecraft.server.level.EntityPlayer.damageEntity(EntityPlayer.java:998)
[04:48:25 WARN]:        at net.minecraft.world.entity.player.EntityHuman.attack(EntityHuman.java:1261)
[04:48:25 WARN]:        at net.minecraft.server.level.EntityPlayer.attack(EntityPlayer.java:2019)
[04:48:25 WARN]:        at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2492)
[04:48:25 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[04:48:25 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[04:48:25 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2419)
[04:48:25 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[04:48:25 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[04:48:25 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56)
[04:48:25 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[04:48:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[04:48:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[04:48:25 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1426)
[04:48:25 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192)
[04:48:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[04:48:25 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1404)
[04:48:25 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1397)
[04:48:25 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[04:48:25 WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1375)
[04:48:25 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1286)
[04:48:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[04:48:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[04:48:25 WARN]: [AdvancedEnchantments] Failed to activate effect 'REMOVE_ARMOR:ELYTRA '
[04:48:25 WARN]: [AdvancedEnchantments] Additional information: Error while activating effect

### "/ae plinfo" link

https://paste.md-5.net/mukekefovo

**Comment by ThomasWega** [comment]
Hello. You can just use 

"REMOVE_ARMOR:CHESTPLATE"

and ELYTRA will be removed as well :)
