### ISSUE TITLE
Advanced enchants not compatible with saberfactions

### ISSUE THREAD

**Issue by Hadimhz** [GC-spigot/AdvancedEnchantments#3471]
### Describe the bug

The plugin loads fine, although floods the console with errors

```
[16:43:36 ERROR]: Could not pass event PlayerMoveEvent to AdvancedEnchantments v9.2.9
java.lang.NoSuchMethodError: 'com.massivecraft.factions.perms.Relation com.massivecraft.factions.FPlayer.getRelationToLocation()'
        at net.advancedplugins.ae.impl.utils.hooks.plugins.FactionsUUIDHook.getRelationOfLand(FactionsUUIDHook.java:30) ~[AdvancedEnchantments-9.2.9.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.effects.internal.LavaWalkerEffect.checkAndSet(LavaWalkerEffect.java:97) ~[AdvancedEnchantments-9.2.9.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.effects.internal.LavaWalkerEffect.scanBlocks(LavaWalkerEffect.java:92) ~[AdvancedEnchantments-9.2.9.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.effects.internal.LavaWalkerEffect.onMove(LavaWalkerEffect.java:61) ~[AdvancedEnchantments-9.2.9.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor640.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1979]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1674) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:29) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$PosRot.handle(ServerboundMovePlayerPacket.java:88) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1416) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1979]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]```

### How to reproduce

run the latest version of saber and AE

### Screenshots / Videos

_No response_

### "/ae plinfo" link

https://paste.md-5.net/ebiluranod

### Server Log

https://mcpaste.io/5ec1c678e8d9b1fc

**Comment by reussy** [comment]
Fixed :)
