### ISSUE TITLE
Compatibility issue with ItemsAdder

### ISSUE THREAD

**Issue by mgmgmg-dev** [GC-spigot/AdvancedEnchantments#3472]
### Describe the bug

Enchanting an ItemsAdder item with the Telepathy enchantment seems to void some drops. In the linked video I tested it at level 4  (100% chance of working). If tested at a lower level, the item can still vanish, but it also sometimes drops on the floor (which would be the expected behaviour when lowering the level)

### How to reproduce

Enchant an ItemsAdder item with the Telepathy enchantment and mine some blocks.

### Screenshots / Videos

https://cdn.discordapp.com/attachments/752871354986135572/1125193576066863225/compatibility_issue.mp4

### "/ae plinfo" link

https://paste.md-5.net/azifadiruy

**Comment by SirJben** [comment]
Try now in [9.2.11](https://www.spigotmc.org/resources/%E2%AD%95-advancedenchantments-%E2%AD%90-450-custom-enchants-%E2%AD%90create-custom-enchantments-%E2%9C%85-25-sale.43058/update?update=506932).

**Comment by Agaloth** [comment]
I'm having this error:

[22:51:59 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.2.11
java.lang.NullPointerException: Cannot invoke "dev.lone.itemsadder.api.CustomStack.getMaxDurability()" because the return value of "dev.lone.itemsadder.api.CustomStack.byItemStack(org.bukkit.inventory.ItemStack)" is null
        at net.advancedplugins.ae.impl.utils.hooks.plugins.ItemsAdderHook.getCustomItemMaxDurability(ItemsAdderHook.java:36) ~[AdvancedEnchantments-9.2.11.jar:?]
        at net.advancedplugins.ae.impl.utils.ItemDurability.getMaxDurability(ItemDurability.java:124) ~[AdvancedEnchantments-9.2.11.jar:?]
        at net.advancedplugins.ae.impl.utils.ItemDurability.getDurability(ItemDurability.java:134) ~[AdvancedEnchantments-9.2.11.jar:?]
        at net.advancedplugins.ae.impl.utils.ItemDurability.isBroken(ItemDurability.java:86) ~[AdvancedEnchantments-9.2.11.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:272) ~[AdvancedEnchantments-9.2.11.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:71) ~[AdvancedEnchantments-9.2.11.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:78) ~[AdvancedEnchantments-9.2.11.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor899.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfishplus-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfishplus-api-1.20.1-R0.1-SNAPSHOT.jar:git-PufferfishPlus-7]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfishplus-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent() ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-7]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent() ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-7]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfishplus-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.a(ServerPlayerGameMode.java) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.a(ServerPlayerGameMode.java) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.a(ServerPlayerGameMode.java) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.a(ServerGamePacketListenerImpl.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-7]
        at net.minecraft.util.thread.BlockableEventLoop.d(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.d(ReentrantBlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-7]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-7]
        at net.minecraft.util.thread.BlockableEventLoop.x(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-7]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-7]
        at net.minecraft.util.thread.BlockableEventLoop.c(BlockableEventLoop.java) ~[?:?]
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-7]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-7]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java) ~[pufferfishplus-1.20.1.jar:git-PufferfishPlus-7]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
