### ISSUE TITLE
player can break block in claimed region (lands) (2)

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#3479]
### Describe the bug

i reported this bugs at #3470 , but still can break block.

### How to reproduce

1. make pickaxe

2. break glass.
글래스해머:
  display: '%group-color%글래스해머'
  description: |-
    유리를 즉시 파괴할 수 있게 됩니다.
    &7(수확은 적용되지 않습니다)
  applies-to: 
  type: SWING
  group: 레어
  applies:
  - ALL_AXE
  - ALL_PICKAXE
  - ALL_SPADE
  levels:
    '1':
      conditions:
      - '%block type% contains GLASS : %allow%'
      effects:
      - BREAK_BLOCK @Block
  settings:    
    disable-in-enchanter: true

### Screenshots / Videos

https://youtu.be/mdXGfj3pd6A

### "/ae plinfo" link

https://paste.md-5.net/xizahipevo

**Comment by ColdDragons81** [comment]
I have the same problem with lands

**Comment by GC-spigot** [comment]
Fixed next update!

**Comment by brendanjhnsn** [comment]
I'm having the same issue:

[22:53:17 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.2.18
java.lang.NoClassDefFoundError: com/gmail/nossr50/events/fake/FakeBlockBreakEvent
        at net.advancedplugins.ae.impl.utils.hooks.plugins.LandsHook.canBuild(LandsHook.java) ~[AdvancedEnchantments-9.2.18.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.protection.external.LandsCheck.canBreak(LandsCheck.java:25) ~[AdvancedEnchantments-9.2.18.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.protection.ProtectionHandler.lambda$canBreak$0(ProtectionHandler.java:53) ~[AdvancedEnchantments-9.2.18.jar:?]
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:?]
        at java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1800) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:?]
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637) ~[?:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.protection.ProtectionHandler.canBreak(ProtectionHandler.java:53) ~[AdvancedEnchantments-9.2.18.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.effects.internal.SetBlockEffect.executeEffect(SetBlockEffect.java:34) ~[AdvancedEnchantments-9.2.18.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:174) ~[AdvancedEnchantments-9.2.18.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:107) ~[AdvancedEnchantments-9.2.18.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54) ~[AdvancedEnchantments-9.2.18.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68) ~[AdvancedEnchantments-9.2.18.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:78) ~[AdvancedEnchantments-9.2.18.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor937.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-65]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-65]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-65]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:301) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1872) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-65]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.events.fake.FakeBlockBreakEvent
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 47 more
