### ISSUE TITLE
Not working on 1.17.1 (message on console) but working on 1.16.5

### ISSUE THREAD

**Issue by SharasGit** [GC-spigot/AdvancedEnchantments#3513]
### Describe the bug

I have an error when i start my server on 1.17.1. The plugin is working fine on 1.16.5.

14:02:58] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into PlaceholderAPI.
[14:02:58] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into ProtocolLib.
[14:02:58] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into GriefPrevention.
[14:02:58] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into CoreProtect.
[14:02:58] [Server thread/INFO]: [AdvancedEnchantments] Loaded 7 armor sets.
[14:02:58] [Server thread/INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[14:02:58] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.world.entity.EntityInsentient.D()
[14:02:58] [Server thread/WARN]:     at java.base/java.lang.Class.getMethod(Class.java:2227)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:176)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:189)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:194)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<clinit>(ReflectionMethod.java:145)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.setString(NBTCompound.java:36)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.utils.nbt.NBTapi.addNBTTag(NBTapi.java:15)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.impl.utils.items.ItemBuilder.addNBTTag(ItemBuilder.java:394)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.items.item.RandomizationScroll.<init>(RandomizationScroll.java:19)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.items.ItemLoader.loadInternalItems(ItemLoader.java:52)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.items.ItemLoader.<init>(ItemLoader.java:26)
[14:02:58] [Server thread/WARN]:     at AdvancedEnchantments-9.2.19.jar//net.advancedplugins.ae.Core.onEnable(Core.java:259)
[14:02:58] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:02:58] [Server thread/WARN]:     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[14:02:58] [Server thread/WARN]:     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[14:02:58] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561)
[14:02:58] [Server thread/WARN]:     at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475)
[14:02:58] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:733)
[14:02:58] [Server thread/WARN]:     at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:317)
[14:02:58] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1220)
[14:02:58] [Server thread/WARN]:     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[14:02:58] [Server thread/WARN]:     at java.base/java.lang.Thread.run(Thread.java:833)

### How to reproduce

Just launch the server in 1.17.1

### "/ae plinfo" link

https://paste.md-5.net/ukefeteyuj

### Server Log

https://mcpaste.io/a1eb0b305bd2314b

**Comment by GC-spigot** [comment]
Fixed!
