### ISSUE TITLE
Weird Issue

### ISSUE THREAD

**Issue by kingevolved** [GC-spigot/AdvancedEnchantments#3528]
### Describe the bug

Here is the issue coming up

[27.07 00:16:49] [Server] [WARN] [AdvancedEnchantments] §4Failed to activate effect '§fpotion:speed:0:600 '
[27.07 00:16:49] [Server] [WARN] [AdvancedEnchantments] §cAdditional information: §7Failed to activate effects as advancedEffect is null or invalid: 'potion', potion:speed:0:600 , trigger:FALL_DAMAGE, entity:Wratthew19

[27.07 00:18:55] [Server] [WARN] java.lang.NumberFormatException: For input string: "0<aoe>radius=3target=mobs</aoe>"
[27.07 00:18:55] [Server] [WARN] 	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
[27.07 00:18:55] [Server] [WARN] 	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
[27.07 00:18:55] [Server] [WARN] 	at java.base/java.lang.Float.parseFloat(Float.java:476)
[27.07 00:18:55] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.ParticleEffect.executeEffect(ParticleEffect.java:30)
[27.07 00:18:55] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.ParticleEffect.executeEffect(ParticleEffect.java:22)
[27.07 00:18:55] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:181)
[27.07 00:18:55] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:111)
[27.07 00:18:55] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54)
[27.07 00:18:55] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68)
[27.07 00:18:55] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.AttackMobTrigger.playerHitMob(AttackMobTrigger.java:56)
[27.07 00:18:55] [Server] [WARN] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor372.execute(Unknown Source)
[27.07 00:18:55] [Server] [WARN] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[27.07 00:18:55] [Server] [WARN] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[27.07 00:18:55] [Server] [WARN] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[27.07 00:18:55] [Server] [WARN] 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[27.07 00:18:55] [Server] [WARN] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[27.07 00:18:55] [Server] [WARN] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[27.07 00:18:55] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:258)
[27.07 00:18:55] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1189)
[27.07 00:18:55] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1044)
[27.07 00:18:55] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:988)
[27.07 00:18:55] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1223)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2184)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1423)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.world.entity.raid.EntityRaider.a(EntityRaider.java:299)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1320)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2162)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2882)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2806)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1386)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[27.07 00:18:55] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[27.07 00:18:55] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)
[27.07 00:18:55] [Server] [WARN] [AdvancedEnchantments] §4Failed to activate effect '§fPARTICLE:SPELL_MOB:5:0 <aoe> radius=3 target=mobs </aoe>'
[27.07 00:18:55] [Server] [WARN] [AdvancedEnchantments] §cAdditional information: §7Error while activating effect
[27.07 00:19:01] [Server] [WARN] java.lang.NumberFormatException: For input string: "0<aoe>radius=3target=mobs</aoe>"
[27.07 00:19:01] [Server] [WARN] 	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
[27.07 00:19:01] [Server] [WARN] 	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
[27.07 00:19:01] [Server] [WARN] 	at java.base/java.lang.Float.parseFloat(Float.java:476)
[27.07 00:19:01] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.ParticleEffect.executeEffect(ParticleEffect.java:30)
[27.07 00:19:01] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.ParticleEffect.executeEffect(ParticleEffect.java:22)
[27.07 00:19:01] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:181)
[27.07 00:19:01] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:111)
[27.07 00:19:01] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54)
[27.07 00:19:01] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68)
[27.07 00:19:01] [Server] [WARN] 	at AdvancedEnchantments-9.3.1.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.AttackMobTrigger.playerHitMob(AttackMobTrigger.java:56)
[27.07 00:19:01] [Server] [WARN] 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor372.execute(Unknown Source)
[27.07 00:19:01] [Server] [WARN] 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[27.07 00:19:01] [Server] [WARN] 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[27.07 00:19:01] [Server] [WARN] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[27.07 00:19:01] [Server] [WARN] 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[27.07 00:19:01] [Server] [WARN] 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[27.07 00:19:01] [Server] [WARN] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[27.07 00:19:01] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:258)
[27.07 00:19:01] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1189)
[27.07 00:19:01] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1044)
[27.07 00:19:01] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:988)
[27.07 00:19:01] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1223)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2184)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1431)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.world.entity.raid.EntityRaider.a(EntityRaider.java:299)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1320)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2162)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.network.PlayerConnection$5.a(PlayerConnection.java:2882)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2806)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1339)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1316)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1309)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1386)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1171)
[27.07 00:19:01] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318)
[27.07 00:19:01] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)
[27.07 00:19:01] [Server] [WARN] [AdvancedEnchantments] §4Failed to activate effect '§fPARTICLE:SPELL_MOB:5:0 <aoe> radius=3 target=mobs </aoe>'
[27.07 00:19:01] [Server] [WARN] [AdvancedEnchantments] §cAdditional information: §7Error while activating effect

### How to reproduce

Certain enchants on armor causing this

### "/ae plinfo" link

https://paste.md-5.net/ayovesaxoq

**Comment by GC-spigot** [comment]
Seems like you are using old format for enchants, this is how it should look like for killaura enchant:
```yaml
killaura:
  display: '%group-color%Kill Aura'
  description: |-
    Chance to kill multiple
    monsters in radius.
  applies-to: Swords
  group: LEGENDARY
  type: ATTACK_MOB
  applies:
    - ALL_SWORD
  levels:
    '1':
      chance: 5
      cooldown: 3
      effects:
        - PARTICLE:SPELL_MOB:5:0 @Aoe{radius=2,target=mobs}
        - KILL:1 @Aoe{radius=2,target=mobs}
