### ISSUE TITLE
error in console about more drops

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#3542]
### Describe the bug

[02:16:55 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.block.Block.hasMetadata(String)" because "<local6>" is null
[02:16:55 WARN]:        at AdvancedEnchantments-9.3.6 (1).jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.MoreDropsEffect.executeEffect(MoreDropsEffect.java:66)
[02:16:55 WARN]:        at AdvancedEnchantments-9.3.6 (1).jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:181)
[02:16:55 WARN]:        at AdvancedEnchantments-9.3.6 (1).jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:111)
[02:16:55 WARN]:        at AdvancedEnchantments-9.3.6 (1).jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54)
[02:16:55 WARN]:        at AdvancedEnchantments-9.3.6 (1).jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68)
[02:16:55 WARN]:        at AdvancedEnchantments-9.3.6 (1).jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.CatchFishTrigger.onPlayerFish(CatchFishTrigger.java:54)
[02:16:55 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1157.execute(Unknown Source)
[02:16:55 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[02:16:55 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[02:16:55 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:16:55 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[02:16:55 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[02:16:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[02:16:55 WARN]:        at net.minecraft.world.entity.projectile.EntityFishingHook.a(EntityFishingHook.java:516)
[02:16:55 WARN]:        at net.minecraft.world.item.ItemFishingRod.a(ItemFishingRod.java:32)
[02:16:55 WARN]:        at net.minecraft.world.item.ItemStack.a(ItemStack.java:544)
[02:16:55 WARN]:        at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:482)
[02:16:55 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2125)
[02:16:55 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:32)
[02:16:55 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8)
[02:16:55 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[02:16:55 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:16:55 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[02:16:55 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:16:55 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1366)
[02:16:55 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[02:16:55 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[02:16:55 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1343)
[02:16:55 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1336)
[02:16:55 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bp(IAsyncTaskHandler.java:114)
[02:16:55 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1452)
[02:16:55 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1192)
[02:16:55 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323)
[02:16:55 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[02:16:55 WARN]: [AdvancedEnchantments] §4Failed to activate effect '§fMORE_DROPS:1'
[02:16:55 WARN]: [AdvancedEnchantments] §cAdditional information: §7Error while activating effect

### How to reproduce

idk it just spams in console/ing-ame

### "/ae plinfo" link

https://paste.md-5.net/wixokivida

**Comment by GC-spigot** [comment]
Fixed!
