### ISSUE TITLE
Failed To Calculate EXP

### ISSUE THREAD

**Issue by MartiThaWizz** [GC-spigot/AdvancedEnchantments#3558]
### Describe the bug

[02:35:16 WARN]: net.advancedplugins.ae.impl.utils.evalex.Expression$ExpressionException: Unknown unary operator % at character position 1
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.utils.evalex.Expression.shuntingYard(Expression.java:1321)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.utils.evalex.Expression.getRPN(Expression.java:1778)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.utils.evalex.Expression.eval(Expression.java:1411)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.utils.evalex.Expression.eval(Expression.java:1397)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.utils.ASManager.parseThroughCalculator(ASManager.java:596)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.functions.internal.MathFunction.parse(MathFunction.java:16)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.functions.FunctionsHandler.parseEffectLine(FunctionsHandler.java:42)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:146)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:116)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:68)
[02:35:16 WARN]:        at AdvancedEnchantments-9.3.7.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.KillMobTrigger.onMobDeath(KillMobTrigger.java:57)
[02:35:16 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1003.execute(Unknown Source)
[02:35:16 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[02:35:16 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[02:35:16 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[02:35:16 WARN]:        at PerWorldPlugins-1.4.2.jar//net.tonimatasdev.perworldplugins.api.PerWorldRegisteredListener.callEvent(PerWorldRegisteredListener.java:64)
[02:35:16 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[02:35:16 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[02:35:16 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[02:35:16 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:906)
[02:35:16 WARN]:        at net.minecraft.world.entity.EntityLiving.dropAllDeathLoot(EntityLiving.java:1814)
[02:35:16 WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1709)
[02:35:16 WARN]:        at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1524)
[02:35:16 WARN]:        at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1359)
[02:35:16 WARN]:        at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2234)
[02:35:16 WARN]:        at net.minecraft.server.network.PlayerConnection$6.a(PlayerConnection.java:2969)
[02:35:16 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[02:35:16 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[02:35:16 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2891)
[02:35:16 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[02:35:16 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[02:35:16 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:51)
[02:35:16 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[02:35:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[02:35:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[02:35:16 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1369)
[02:35:16 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[02:35:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[02:35:16 WARN]:        at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1346)
[02:35:16 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1339)
[02:35:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[02:35:16 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1416)
[02:35:16 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1195)
[02:35:16 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325)
[02:35:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[02:35:16 WARN]: Failed to calculate '%exp%*(1.0+0.25*4)': Invalid syntax or outcome

### How to reproduce

Using Inquisitive Enchant

### "/ae plinfo" link

https://paste.md-5.net/ehoxocibos

**Comment by GC-spigot** [comment]
Resolved next update
