### ISSUE TITLE
Console errors 

### ISSUE THREAD

**Issue by ydu80** [GC-spigot/AdvancedEnchantments#356]
Paper(1593) 1.12.2-R0.1-SNAPSHOT
AE 5.2.8
Finally upgraded from 5.0 to 5.2.8. Can't say that something in-game goes wrong but having these errors is rather annoying. 
```
[00:07:56 WARN]: java.lang.NullPointerException
[00:07:56 WARN]:        at java.lang.String.replace(String.java:2240)
[00:07:56 WARN]:        at n3kas.ae.usercommands.Enchantments.a(Enchantments.java:201)
[00:07:56 WARN]:        at n3kas.ae.usercommands.Enchantments.a(Enchantments.java:121)
[00:07:56 WARN]:        at n3kas.ae.enchanter.InventoryEvent.a(InventoryEvent.java:89)
[00:07:56 WARN]:        at n3kas.ae.globallisteners.InventoryClicks.a(InventoryClicks.java:26)
[00:07:56 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1209.execute(Unknown Source)
[00:07:56 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[00:07:56 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[00:07:56 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[00:07:56 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[00:07:56 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1988)
[00:07:56 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
[00:07:56 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
[00:07:56 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[00:07:56 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[00:07:56 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[00:07:56 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[00:07:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[00:07:56 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[00:07:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[00:07:56 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[00:07:56 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by GC-spigot** [comment]
Changed so this error doesn't spam console - this is related to the preview inventory you get when right-clicking a category in enchanter.
