### ISSUE TITLE
API can't work beacause of NullPointerException

### ISSUE THREAD

**Issue by microvencn** [GC-spigot/AdvancedEnchantments#3632]
### Describe the bug

I am using the AdvancedEnchantmetns 9.3.14, and trying to use the API of it by adding it to the libraries. But all method of the AEAPI can't work because the NullPointerException.
```
[20:56:48 ERROR]: Error occurred while enabling EnchantmentMigrate v0.9a (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at net.advancedplugins.ae.api.AEAPI.getAllEnchantments(AEAPI.java:353) ~[EnchantmentMigrate-0.9a-all.jar:?]
	at cn.microven.enchantment_migrate.Main.onEnable(Main.java:31) ~[EnchantmentMigrate-0.9a-all.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-550]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.4.jar:git-Paper-550]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-550]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-550]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.TriggerHandler.getTriggers()" because the return value of "net.advancedplugins.ae.impl.effects.effects.EffectsHandler.getTriggerHandler()" is null
	at net.advancedplugins.ae.enchanthandler.enchantments.AEnchants.<clinit>(AEnchants.java:20) ~[EnchantmentMigrate-0.9a-all.jar:?]
	... 14 more
``` 
My code
```
List<String> es = AEAPI.getAllEnchantments();
```

### How to reproduce

Using the API of AdvancedEnchantmetns 9.3.14 by adding it to the libraries. Call the any method of AEAPI

### "/ae plinfo" link

https://paste.md-5.net/tituqiwigi

**Comment by ThomasWega** [comment]
Are you sure AE plugin is fully loaded before you call this method?

**Comment by microvencn** [comment]
Sure. I run the code in the listener of PlayerInteractEvent. I even run /ae reload before interacting but the exception remains.












吴博维
***@***.***


---Original---
From: ***@***.***&gt;
Date: Wed, Sep 6, 2023 15:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [GC-spigot/AdvancedEnchantments] API can't work beacause ofNullPointerException (Issue #3632)




 
Are you sure AE plugin is fully loaded before you call this method?

**Comment by microvencn** [comment]
> Are you sure AE plugin is fully loaded before calling this method?

Sure.I have added AdvancedEnchantment as the depend of my plugin. I run the code above in the listener of PlayerInteractEvent. I even run /ae reload before interacting but the exception remains.

**Comment by microvencn** [comment]
In addition, I have tried the version 9.3.16, but the exception remains.

My code:
```java
import net.advancedplugins.ae.api.AEAPI;
import org.bukkit.Bukkit;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.IOException;
import java.util.List;

public class Main extends JavaPlugin implements Listener {
    public static Main ins;

    @Override
    public void onEnable() {
        ins = this;
        saveDefaultConfig();
        Bukkit.getPluginManager().registerEvents(this, this);
    }

    @EventHandler
    public void onInteract(PlayerInteractEvent e) {
        List<String> es = AEAPI.getAllEnchantments();
        for (String s : es) {
            e.getPlayer().sendMessage(s);
        }
    }

    @Override
    public void onDisable() {
    }
}
```

**Comment by ThomasWega** [comment]
I've just tried the exact same code as you have and it runs just fine.
![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/82312488/78cf23f4-5c98-45e5-989b-fbc7f2940d21)
This needs to be an issue on your end. I will close this for now. Feel free to dm me on discord (thomaswega) and I can help you :)
