### ISSUE TITLE
Problem with org/bukkit/RegionAccessor (Plugin is not working)

### ISSUE THREAD

**Issue by Realexx** [GC-spigot/AdvancedEnchantments#3636]
### Describe the bug

I just updated my version of AdvancedEnchantments today and I now have the following error:

```
Error occurred while enabling AdvancedEnchantments v9.3.17 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/RegionAccessor
        at net.advancedplugins.ae.impl.effects.effects.effects.EffectStorage.<init>(EffectStorage.java:100) ~[?:?]
        at net.advancedplugins.ae.impl.effects.effects.EffectsHandler.<init>(EffectsHandler.java:58) ~[?:?]
        at net.advancedplugins.ae.Core.onEnable(Core.java:258) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.RegionAccessor
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:140) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot.jar:3096a-Spigot-9fb885e-af1a232]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 13 more
```

I'm in 1.16.5 and the plugin was working before the update.
I was in version 9.0.0b81 and I don't know where to download the old JARs. So I'm stuck with this error.

It's possible that the org.bukkit.RegionAccessor class was introduced with Spigot 1.20, which would explain the problem, but I'm not sure.

### How to reproduce

I think that running any spigot 1.16.5 server with the new version of AdvancedEnchantments should reproduce the problem.

### "/ae plinfo" link

not working

### Server Log

https://mcpaste.io/5fffc0f5483d1ce6

**Comment by ThomasWega** [comment]
Will be fixed in the next version :)
