### ISSUE TITLE
Could not pass event BlockBreakEvent to AdvancedEnchantments v9.4.3

### ISSUE THREAD

**Issue by Jimaie72** [GC-spigot/AdvancedEnchantments#3676]
### Describe the bug

Server version : PAPER 1.19.2 
Only premium member

[11:57:18 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.4.3
java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.TORCHFLOWER
at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
at org.bukkit.Material.valueOf(Material.java:112) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at net.advancedplugins.ae.impl.utils.CropUtils.isFullyGrown(CropUtils.java:143) ~[AdvancedEnchantments-9.4.3.jar:?]
at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:101) ~[AdvancedEnchantments-9.4.3.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor985.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-280]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at no.hyp.farmingupgrade.FarmingUpgradePlugin.harvestCrop(FarmingUpgradePlugin.java:490) ~[farmingupgrade-1.4.0.jar:?]
at no.hyp.farmingupgrade.FarmingUpgradePlugin.initiateHarvest(FarmingUpgradePlugin.java:447) ~[farmingupgrade-1.4.0.jar:?]
at no.hyp.farmingupgrade.FarmingUpgradePlugin.onFarm(FarmingUpgradePlugin.java:428) ~[farmingupgrade-1.4.0.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor252.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-280]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:369) ~[?:?]
at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:328) ~[?:?]
at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:266) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1883) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-280]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-280]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-280]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-280]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-280]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1389) ~[paper-1.19.2.jar:git-Paper-280]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.2.jar:git-Paper-280]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-280]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

I'm not doing anything special, it's spamming my console

### "/ae plinfo" link

https://paste.md-5.net/hufawewoqo

**Comment by ThomasWega** [comment]
Will be fixed in the next update
