### ISSUE TITLE
I reported an error when using version 1.18

### ISSUE THREAD

**Issue by 1821698021** [GC-spigot/AdvancedEnchantments#3679]
### Describe the bug

[18:27:31 INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v9.4.3
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into WorldGuard.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into AureliumSkills.
[18:27:32 INFO]: [PlaceholderAPI] Successfully registered expansion: advancedenchantments [1.0.0]
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into PlaceholderAPI.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into MythicMobs.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into ProtocolLib.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into SilkSpawners.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into CMI.
[18:27:32 INFO]: [AdvancedEnchantments] Loaded 7 armor sets.
[18:27:32 INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[18:27:32 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.entity.EntityInsentient.getNavigation()
[18:27:32 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:176)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:189)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:194)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<clinit>(ReflectionMethod.java:145)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.setString(NBTCompound.java:36)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.NBTapi.addNBTTag(NBTapi.java:15)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.items.ItemBuilder.addNBTTag(ItemBuilder.java:398)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.items.item.RandomizationScroll.<init>(RandomizationScroll.java:19)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.items.ItemLoader.loadInternalItems(ItemLoader.java:52)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.items.ItemLoader.<init>(ItemLoader.java:26)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.Core.onEnable(Core.java:263)
[18:27:32 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:27:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:27:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[18:27:32 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[18:27:32 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[18:27:32 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[18:27:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into economy plugin (Vault)

### How to reproduce

[18:27:31 INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v9.4.3
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into WorldGuard.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into AureliumSkills.
[18:27:32 INFO]: [PlaceholderAPI] Successfully registered expansion: advancedenchantments [1.0.0]
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into PlaceholderAPI.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into MythicMobs.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into ProtocolLib.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into SilkSpawners.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into CMI.
[18:27:32 INFO]: [AdvancedEnchantments] Loaded 7 armor sets.
[18:27:32 INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[18:27:32 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.entity.EntityInsentient.getNavigation()
[18:27:32 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:176)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:189)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:194)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<clinit>(ReflectionMethod.java:145)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.setString(NBTCompound.java:36)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.NBTapi.addNBTTag(NBTapi.java:15)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.items.ItemBuilder.addNBTTag(ItemBuilder.java:398)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.items.item.RandomizationScroll.<init>(RandomizationScroll.java:19)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.items.ItemLoader.loadInternalItems(ItemLoader.java:52)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.items.ItemLoader.<init>(ItemLoader.java:26)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.Core.onEnable(Core.java:263)
[18:27:32 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:27:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:27:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[18:27:32 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[18:27:32 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[18:27:32 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[18:27:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into economy plugin (Vault)

### Screenshots / Videos

[18:27:31 INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v9.4.3
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into WorldGuard.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into AureliumSkills.
[18:27:32 INFO]: [PlaceholderAPI] Successfully registered expansion: advancedenchantments [1.0.0]
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into PlaceholderAPI.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into MythicMobs.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into ProtocolLib.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into SilkSpawners.
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into CMI.
[18:27:32 INFO]: [AdvancedEnchantments] Loaded 7 armor sets.
[18:27:32 INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[18:27:32 WARN]: java.lang.NoSuchMethodException: net.minecraft.world.entity.EntityInsentient.getNavigation()
[18:27:32 WARN]:        at java.base/java.lang.Class.getMethod(Class.java:2227)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:176)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:189)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:194)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<clinit>(ReflectionMethod.java:145)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.setString(NBTCompound.java:36)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.nbt.NBTapi.addNBTTag(NBTapi.java:15)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.impl.utils.items.ItemBuilder.addNBTTag(ItemBuilder.java:398)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.items.item.RandomizationScroll.<init>(RandomizationScroll.java:19)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.items.ItemLoader.loadInternalItems(ItemLoader.java:52)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.items.ItemLoader.<init>(ItemLoader.java:26)
[18:27:32 WARN]:        at AdvancedEnchantments-9.4.3.jar//net.advancedplugins.ae.Core.onEnable(Core.java:263)
[18:27:32 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[18:27:32 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:27:32 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541)
[18:27:32 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560)
[18:27:32 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[18:27:32 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:352)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[18:27:32 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[18:27:32 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[18:27:32 INFO]: [AdvancedEnchantments] Successfully hooked into economy plugin (Vault)

### "/ae plinfo" link

1.18.2purpur

### Server Log

none

**Comment by ThomasWega** [comment]
When does this happen? Do you mind sending a video? Also send a list of plugins and server log please

**Comment by GC-spigot** [comment]
Fixed!
