### ISSUE TITLE
Console spam on new version

### ISSUE THREAD

**Issue by SamGamerYT** [GC-spigot/AdvancedEnchantments#3703]
### Describe the bug

[20:07:51 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v9.4.7
java.lang.ClassCastException: class org.bukkit.inventory.EquipmentSlot cannot be cast to class net.advancedplugins.ae.impl.effects.effects.actions.utils.RollItemType (org.bukkit.inventory.EquipmentSlot is in unnamed module of loader java.net.URLClassLoader @7e32c033; net.advancedplugins.ae.impl.effects.effects.actions.utils.RollItemType is in unnamed module of loader 'AdvancedEnchantments-9.4.7.jar' @2a009cb5)
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ShootMobTrigger.onProjectileHitEvent(ShootMobTrigger.java:47) ~[AdvancedEnchantments-9.4.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor844.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1227) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1080) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1023) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1261) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2260) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1479) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:403) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:233) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:224) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:297) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:233) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1435) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:896) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:873) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1585) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

Wait in console

### "/ae plinfo" link

https://paste.md-5.net/oyejayeriq

**Comment by ThomasWega** [comment]
Will be fixed in the new version. Very sorry, it was my typo
