### ISSUE TITLE
Console Errors AE 9.4.7

### ISSUE THREAD

**Issue by BboyZeroOne** [GC-spigot/AdvancedEnchantments#3712]
### Describe the bug

I'm not too sure what it is, but it says **"Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v9.4.7"**

Plugin version: AE 9.4.7
Server: Paper 1.20.1

Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v9.4.7
java.lang.ClassCastException: class org.bukkit.inventory.EquipmentSlot cannot be cast to class net.advancedplugins.ae.impl.effects.effects.actions.utils.RollItemType (org.bukkit.inventory.EquipmentSlot is in unnamed module of loader java.net.URLClassLoader @5ce65a89; net.advancedplugins.ae.impl.effects.effects.actions.utils.RollItemType is in unnamed module of loader 'AdvancedEnchantments-9.4.7.jar' @65cf7e6c)
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ShootTrigger.onProjectileHitEvent(ShootTrigger.java:45) ~[AdvancedEnchantments-9.4.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1049.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-196]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1215) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1070) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1014) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1249) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2184) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1060) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1431) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:967) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1128) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:402) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:203) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:194) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:296) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:232) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1352) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1004) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:872) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:852) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1556) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

### How to reproduce

Idk

### "/ae plinfo" link

Don't think this is needed

**Comment by ThomasWega** [comment]
fixed in 9.4.8
