### ISSUE TITLE
Loss of old books 9.5.5

### ISSUE THREAD

**Issue by SrT3ddy** [GC-spigot/AdvancedEnchantments#3758]
### Describe the bug

I have a problem, all the books that were generated by rcbook in version 9.5.3 don't work if I update to version 9.5.5 I had to go back to the version for my players not to lose their stored enchantments

### How to reproduce

I took books generated from version 9.5.3, put them in a chest, updated the plugin to 9.5.5 and all the books in the chest stopped working

### "/ae plinfo" link

https://paste.md-5.net/ucizahuxen

**Comment by ThomasWega** [comment]
This is true. We have changed the NBT in 9.5.5 for books. We are currently figuring out a solution which works for everyone. Update which will fix old support will be out in no time

**Comment by ThomasWega** [comment]
Will be fixed in the next update! Very sorry about this

**Comment by SrT3ddy** [comment]
Magic gems do not apply to old version 9.5.3 books.


And it started to appear this in the latest version 9.5.6:

[16:39:20] [Server thread/ERROR]: Could not pass event EntityDamageEvent to AdvancedEnchantments v9.5.6
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getLocation()" because "<local4>" is null
	at net.advancedplugins.ae.impl.effects.effects.variables.StaticVariable.getValue(StaticVariable.java:230) ~[AdvancedEnchantments-9.5.6.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.variables.Variables.replaceVariables(Variables.java:39) ~[AdvancedEnchantments-9.5.6.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:144) ~[AdvancedEnchantments-9.5.6.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:118) ~[AdvancedEnchantments-9.5.6.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:54) ~[AdvancedEnchantments-9.5.6.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:70) ~[AdvancedEnchantments-9.5.6.jar:?]
	at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.FireTrigger.onDamage(FireTrigger.java:38) ~[AdvancedEnchantments-9.5.6.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1188.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1227) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1200) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1023) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1261) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2260) ~[?:?]
	at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1099) ~[?:?]
	at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1479) ~[?:?]
	at net.minecraft.world.entity.player.Player.hurt(Player.java:1006) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1166) ~[?:?]
	at net.minecraft.world.entity.Entity.baseTick(Entity.java:902) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.world.entity.LivingEntity.baseTick(LivingEntity.java:412) ~[?:?]
	at net.minecraft.world.entity.Entity.tick(Entity.java:855) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.world.entity.LivingEntity.tick(LivingEntity.java:3056) ~[?:?]
	at net.minecraft.world.entity.player.Player.tick(Player.java:305) ~[?:?]
	at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:780) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:376) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:611) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1615) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
