### ISSUE TITLE
Slimefun BUG

### ISSUE THREAD

**Issue by SeptyIsHere** [GC-spigot/AdvancedEnchantments#3968]
### Describe the bug

Trench doesn't work.

### How to reproduce

Have latest slimefun dev build and latest ae plugin version

### Screenshots / Videos

[23:34:31 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.6.6
java.lang.ClassCastException: class net.advancedplugins.ae.impl.utils.hooks.PluginHookInstance cannot be cast to class net.advancedplugins.ae.impl.utils.hooks.plugins.SlimeFunHook (net.advancedplugins.ae.impl.utils.hooks.PluginHookInstance and net.advancedplugins.ae.impl.utils.hooks.plugins.SlimeFunHook are in unnamed module of loader 'AdvancedEnchantments-9.6.6.jar' @513f47d2)
        at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.internal.TrenchTarget.getTargets(TrenchTarget.java:98) ~[AdvancedEnchantments-9.6.6.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.Targets.handleTargets(Targets.java:46) ~[AdvancedEnchantments-9.6.6.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.updateMain(ExecutionTask.java:225) ~[AdvancedEnchantments-9.6.6.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:91) ~[AdvancedEnchantments-9.6.6.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:56) ~[AdvancedEnchantments-9.6.6.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[AdvancedEnchantments-9.6.6.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:128) ~[AdvancedEnchantments-9.6.6.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1577.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:git-Purpur-1985]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:377) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:336) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:300) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1953) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1369) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1346) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1339) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1317) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1205) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1985]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### "/ae plinfo" link

https://paste.md-5.net/avoliqoboq

**Comment by ThomasWega** [comment]
update and try again please

**Comment by ThomasWega** [comment]
Will be fixed next update
