### ISSUE TITLE
Event error EntityShootBowEvent 

### ISSUE THREAD

**Issue by Paceski** [GC-spigot/AdvancedEnchantments#4025]
### Describe the bug

[10:49:04 ERROR]: Could not pass event EntityShootBowEvent to AdvancedEnchantments v9.6.6
java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getType()" because "<parameter2>" is null
at [net.advancedplugins.ae](http://net.advancedplugins.ae/).impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:195) ~[AdvancedEnchantments-9.6.6.jar:?]
at [net.advancedplugins.ae](http://net.advancedplugins.ae/).impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:118) ~[AdvancedEnchantments-9.6.6.jar:?]
at [net.advancedplugins.ae](http://net.advancedplugins.ae/).impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:56) ~[AdvancedEnchantments-9.6.6.jar:?]
at [net.advancedplugins.ae](http://net.advancedplugins.ae/).impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[AdvancedEnchantments-9.6.6.jar:?]
at [net.advancedplugins.ae](http://net.advancedplugins.ae/).impl.effects.effects.mechanics.triggers.internal.BowFireTrigger.onShoot(BowFireTrigger.java:28) ~[AdvancedEnchantments-9.6.6.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor821.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[?:git-UniverseSpigot-"4cb60ef"]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[?:git-UniverseSpigot-"4cb60ef"]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[?:git-UniverseSpigot-"4cb60ef"]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:87) ~[?:git-UniverseSpigot-"4cb60ef"]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[?:git-UniverseSpigot-"4cb60ef"]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[?:git-UniverseSpigot-"4cb60ef"]
at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:657) ~[?:git-UniverseSpigot-"4cb60ef"]
at net.minecraft.world.item.BowItem.releaseUsing(BowItem.java:68) ~[?:?]
at net.minecraft.world.item.ItemStack.releaseUsing(ItemStack.java:825) ~[?:git-UniverseSpigot-"4cb60ef"]
at net.minecraft.world.entity.LivingEntity.releaseUsingItem(LivingEntity.java:4153) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1964) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:50) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:git-UniverseSpigot-"4cb60ef"]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1357) ~[?:git-UniverseSpigot-"4cb60ef"]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:196) ~[?:git-UniverseSpigot-"4cb60ef"]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[?:git-UniverseSpigot-"4cb60ef"]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[?:git-UniverseSpigot-"4cb60ef"]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[?:git-UniverseSpigot-"4cb60ef"]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1186) ~[?:git-UniverseSpigot-"4cb60ef"]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[?:git-UniverseSpigot-"4cb60ef"]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

I don't know, randomly spams console. Could you maybe know if this is config issue or AE issue?

### "/ae plinfo" link

https://paste.md-5.net/homawotafo

**Comment by ThomasWega** [comment]
You do probably have a misconfiguration. Possible missing a target. This error will be fixed though. Your enchantment still might not work due to misconfiguration, keep that in mind.
