### ISSUE TITLE
when I do any advanced enchantments related commands it says "An internal error occurred while attempting to perform this command"

### ISSUE THREAD

**Issue by Sleeponacouch** [GC-spigot/AdvancedEnchantments#4036]
### Describe the bug

When ever I do any advanced enchantments command they do not work it says this in console 

"[12:50:34 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'ae' in plugin AdvancedEnchantments v9.6.18 - plugin is disabled.
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1013) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:344) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:331) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2301) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2261) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1488) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1465) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1388) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1366) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1255) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2151]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]" ignore the ""

### How to reproduce

So I have these plugins TerraformGenerator, Witherspawn, Spark, Realistic Seasons, Protocolib, MyDog, Mcmmo, Luckperms, Levelled mobs, Gsit, GeyserSpigot, Floodgate, Essentialsx, CoreProtect, Antipopup, and Advanced Enchantments. This is a purpur server. When ever you do /ae in the server it doesn't work or any advanced enchantments related commands. It worked before but now it doesn't work now

it also says this "[12:44:49] [Server thread/WARN]: [AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs." I don't know what this means.

I cannot do /ae plinfo it doesn't work

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/127455535/739b85de-24cf-4a2f-b832-71e9f7cf4189)

### "/ae plinfo" link

I can't do that sorry it doesn't work

### Server Log

https://mcpaste.io/56dc59f177db96e8

**Comment by ThomasWega** [comment]
Go on our discord and open a ticket with info
```
[AdvancedEnchantments] Your license exceeded maximum number of unique IPs. Contact the developer for an enterprise license or connect using previously used IPs." I don't know what this means.
```

https://discord.com/invite/GzdQdMw
