### ISSUE TITLE
Error occured while enabling AdvancedEnchantments v9.7.6 (Is it up to date?)

### ISSUE THREAD

**Issue by AlemPROO** [GC-spigot/AdvancedEnchantments#4103]
### Describe the bug

When I try to run AE latest version on my server it doesn't work, it starts enabling and then disables itself because of some java zip file closed. Here are the logs regarding the plugin:

[11:48:12] [Server thread/INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v9.7.6
[11:48:12] [Server thread/INFO]: [Lands] [Integrations] 3rd party plugin hooking into Lands: AdvancedEnchantments
[11:48:12] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into WorldGuard.
[11:48:12] [Server thread/INFO]: [PlaceholderAPI] Successfully registered internal expansion: advancedenchantments [1.0.0]
[11:48:12] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into PlaceholderAPI.
[11:48:12] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into ProtocolLib.
[11:48:12] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into Essentials.
[11:48:12] [Server thread/INFO]: [AdvancedEnchantments] Successfully hooked into CoreProtect.
[11:48:12] [Server thread/INFO]: [AdvancedEnchantments] Loaded 7 armor sets.
[11:48:12] [Server thread/INFO]: [AdvancedEnchantments] Loaded 5 weapons.
[11:48:12] [Server thread/INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v9.7.6
[11:48:12] [Server thread/ERROR]: Error occurred while enabling AdvancedEnchantments v9.7.6 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.setString(NBTCompound.java:163) ~[AdvancedEnchantments-9.7.6.jar:?]
	at net.advancedplugins.ae.impl.utils.nbt.NBTapi.addNBTTag(NBTapi.java:15) ~[AdvancedEnchantments-9.7.6.jar:?]
	at net.advancedplugins.ae.impl.utils.items.ItemBuilder.addNBTTag(ItemBuilder.java:399) ~[AdvancedEnchantments-9.7.6.jar:?]
	at net.advancedplugins.ae.items.item.TransmogScroll.build(TransmogScroll.java:32) ~[AdvancedEnchantments-9.7.6.jar:?]
	at net.advancedplugins.ae.items.AEItem.isProperlyLoaded(AEItem.java:211) ~[AdvancedEnchantments-9.7.6.jar:?]
	at net.advancedplugins.ae.items.AEItem.<init>(AEItem.java:41) ~[AdvancedEnchantments-9.7.6.jar:?]
	at net.advancedplugins.ae.items.item.TransmogScroll.<init>(TransmogScroll.java:25) ~[AdvancedEnchantments-9.7.6.jar:?]
	at net.advancedplugins.ae.items.AEItemType$1.initialize(AEItemType.java:17) ~[AdvancedEnchantments-9.7.6.jar:?]
	at net.advancedplugins.ae.items.ItemLoader.loadInternalItems(ItemLoader.java:30) ~[AdvancedEnchantments-9.7.6.jar:?]
	at net.advancedplugins.ae.items.ItemLoader.<init>(ItemLoader.java:21) ~[AdvancedEnchantments-9.7.6.jar:?]
	at net.advancedplugins.ae.Core.onEnable(Core.java:220) ~[AdvancedEnchantments-9.7.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-455]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-455]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-455]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-455]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-455]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-455]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-455]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-455]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-455]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:831) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:330) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:518) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:473) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<clinit>(ReflectionMethod.java:24) ~[AdvancedEnchantments-9.7.6.jar:?]
	... 23 more

I use paper 1.20.4 latest, AE 9.7.6 I can list the rest of the plugins I use if needed.

### How to reproduce

Try to run the plugin on paper 1.20.4 I guess?

### "/ae plinfo" link

Doesn't work

**Comment by SirJben** [comment]
Update your plugin.
