### ISSUE TITLE
Cannot pass event inventory

### ISSUE THREAD

**Issue by abilalex** [GC-spigot/AdvancedEnchantments#4135]
### Describe the bug

Cannot add the custom enchanment book to the thing that desire after updating 9.7.8, basically you can upgrade the previous added enchanment to the next level but i can't add new enchanment to the weapons, tools and armor

### How to reproduce

just fix that already

### "/ae plinfo" link

https://paste.md-5.net/zelohoqolu

### Server Log

[05:03:02 ERROR]: Could not pass event InventoryClickEvent to AdvancedEnchantments v9.7.8 java.lang.IllegalArgumentException: Enchantment cannot be null         at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]         at org.bukkit.inventory.ItemStack.addEnchantment(ItemStack.java:398) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at net.advancedplugins.ae.impl.utils.ASManager.makeItemGlow(ASManager.java:1571) ~[AdvancedEnchantments-9.7.8.jar:?]         at net.advancedplugins.ae.utils.AManager.makeItemGlow(AManager.java:1438) ~[AdvancedEnchantments-9.7.8.jar:?]         at net.advancedplugins.ae.api.AEAPI.applyEnchant(AEAPI.java:798) ~[AdvancedEnchantments-9.7.8.jar:?]         at net.advancedplugins.ae.globallisteners.listeners.ClickListener.onClicks(ClickListener.java:810) ~[AdvancedEnchantments-9.7.8.jar:?]         at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor686.execute(Unknown Source) ~[?:?]         at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-446]         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-446]         at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-446]         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]         at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3106) ~[?:?]         at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]         at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]         at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]         at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-446]         at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]         at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]         at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-446]         at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-446]         at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]         at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-446]         at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-446]         at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]         at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[paper-1.20.4.jar:git-Paper-446]         at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[paper-1.20.4.jar:git-Paper-446]         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-446]         at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by GC-spigot** [comment]
Update to 9.7.9, already fixed
