### ISSUE TITLE
can't apply enchantment through ae book 

### ISSUE THREAD

**Issue by Ecilpse** [GC-spigot/AdvancedEnchantments#4181]
### Describe the bug

when player apply enchant through enchant book, console error has printed.

```
[11:03:12] [Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedEnchantments v9.7.13
java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: ae_enchantment-검성
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218) ~[guava-32.1.2-jre.jar:?]
	at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:117) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.advancedplugins.ae.impl.utils.pdc.PDCHandler.getNamespace(PDCHandler.java:102) ~[AdvancedEnchantments-9.7.13.jar:?]
	at net.advancedplugins.ae.impl.utils.pdc.PDCHandler.lambda$contains$0(PDCHandler.java:30) ~[AdvancedEnchantments-9.7.13.jar:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178) ~[?:?]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:1002) ~[?:?]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129) ~[?:?]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:647) ~[?:?]
	at net.advancedplugins.ae.impl.utils.pdc.PDCHandler.contains(PDCHandler.java:30) ~[AdvancedEnchantments-9.7.13.jar:?]
	at net.advancedplugins.ae.utils.nbt.NBTapi.containsEnchant(NBTapi.java:260) ~[AdvancedEnchantments-9.7.13.jar:?]
	at net.advancedplugins.ae.utils.nbt.NBTapi.hasEnchantment(NBTapi.java:103) ~[AdvancedEnchantments-9.7.13.jar:?]
	at net.advancedplugins.ae.api.AEAPI.hasCustomEnchant(AEAPI.java:929) ~[AdvancedEnchantments-9.7.13.jar:?]
	at net.advancedplugins.ae.globallisteners.listeners.ClickListener.onClicks(ClickListener.java:454) ~[AdvancedEnchantments-9.7.13.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1528.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2095]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3183) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2095]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### How to reproduce

just update 9.7.1 to 9.7.13

### "/ae plinfo" link

https://paste.md-5.net/nehonicoci

**Comment by GC-spigot** [comment]
Hi! We recently switched from NBT to PDC, and unfortunately the PersistentDataContainer is limited to latin alphabet only :/ You will have to switch up only enchant key names to latin alphabet, as explained here: https://ae.advancedplugins.net/enchantments/creating-enchantments#starting-out

We could not continue with NBT as it's planned to be removed in 1.20.5 of minecraft update.

**Comment by Ecilpse** [comment]
> Hi! We recently switched from NBT to PDC, and unfortunately the PersistentDataContainer is limited to latin alphabet only :/ You will have to switch up only enchant key names to latin alphabet, as explained here: https://ae.advancedplugins.net/enchantments/creating-enchantments#starting-out
> 
> We could not continue with NBT as it's planned to be removed in 1.20.5 of minecraft update.

so how to migrate lagacy enhantments?
There are already tens of thousands of player tools with enchment.

**Comment by Ecilpse** [comment]
> Hi! We recently switched from NBT to PDC, and unfortunately the PersistentDataContainer is limited to latin alphabet only :/ You will have to switch up only enchant key names to latin alphabet, as explained here: https://ae.advancedplugins.net/enchantments/creating-enchantments#starting-out
> 
> We could not continue with NBT as it's planned to be removed in 1.20.5 of minecraft update.

and PDC work works even if it is not a latin alphabet.
