### ISSUE TITLE
Trench doesn't work due to MCMMO

### ISSUE THREAD

**Issue by KingFouXx** [GC-spigot/AdvancedEnchantments#4202]
### Describe the bug

The trench enchantment doesn't work regardless of whether I enable or disable MCMMO with trench in the config, and there's an error.

enchantements:

detonate:
  display: '%group-color%Detonate'
  description: Chance de casser dans la zone 3x3.
  applies-to: Pickaxes and shovels
  type: MINING
  group: LEGENDARY
  applies:
  - ALL_PICKAXE
  - ALL_SPADE
  levels:
    '1':
      chance: 13
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '2':
      chance: 26
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '3':
      chance: 36
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '4':
      chance: 49
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '5':
      chance: 59
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '6':
      chance: 72
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '7':
      chance: 85
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '8':
      chance: 90
      effects:
      - BREAK_BLOCK @Trench{r=3}
    '9':
      chance: 100
      effects:
      - BREAK_BLOCK @Trench{r=3}
      
      
      
      erreur:
      
      [12:43:58 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.7.14
java.lang.NoClassDefFoundError: com/gmail/nossr50/util/random/ProbabilityUtil
        at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.miningCheck(McMMOHook.java:139) ~[AdvancedEnchantments-9.7.14 (1).jar:?]
        at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.processBlockBreakEvent(McMMOHook.java:128) ~[AdvancedEnchantments-9.7.14 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:205) ~[AdvancedEnchantments-9.7.14 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:83) ~[AdvancedEnchantments-9.7.14 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.7.14 (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1242.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-169]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-169]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-169]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:301) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1927) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1338) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1315) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1308) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1286) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-169]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.util.random.ProbabilityUtil
        ... 32 more
[12:44:39 INFO]: FireGame

### How to reproduce

Using the enchantment
[config.yml.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/15009835/config.yml.txt)

### "/ae plinfo" link

https://paste.md-5.net/ehimisufix

**Comment by KingFouXx** [comment]
and Haste:

[13:34:16 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.7.14
java.lang.NoClassDefFoundError: com/gmail/nossr50/util/random/ProbabilityUtil
        at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.miningCheck(McMMOHook.java:139) ~[AdvancedEnchantments-9.7.14 (1).jar:?]
        at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.processBlockBreakEvent(McMMOHook.java:128) ~[AdvancedEnchantments-9.7.14 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:205) ~[AdvancedEnchantments-9.7.14 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:83) ~[AdvancedEnchantments-9.7.14 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.7.14 (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1242.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-169]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-169]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-169]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.tick(ServerPlayerGameMode.java:139) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:714) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1352) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:920) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$12(ServerLevel.java:872) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:852) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1556) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1393) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1170) ~[paper-1.20.1.jar:git-Paper-169]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-169]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.util.random.ProbabilityUtil
        ... 26 more

**Comment by Yurkhun** [comment]
I get the same error:
https://mclo.gs/nYwwoXE

**Comment by Bali0531** [comment]
same for me with latest
