### ISSUE TITLE
Enchant Acitvation Bug

### ISSUE THREAD

**Issue by Vasito1** [GC-spigot/AdvancedEnchantments#4208]
### Describe the bug

The enchant doesnt work

### How to reproduce

Use the enchant on an item

### Screenshots / Videos

[00:27:19 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.entity.LivingEntity.getLocation()" because "<parameter2>" is null
[00:27:19 WARN]:        at AdvancedEnchantments-9.7.12.jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.FireballEffect.executeEffect(FireballEffect.java:21)
[00:27:19 WARN]:        at AdvancedEnchantments-9.7.12.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:204)
[00:27:19 WARN]:        at AdvancedEnchantments-9.7.12.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:122)
[00:27:19 WARN]:        at AdvancedEnchantments-9.7.12.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:65)
[00:27:19 WARN]:        at AdvancedEnchantments-9.7.12.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80)
[00:27:19 WARN]:        at AdvancedEnchantments-9.7.12.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.BowFireTrigger.onShoot(BowFireTrigger.java:28)
[00:27:19 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor836.execute(Unknown Source)
[00:27:19 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[00:27:19 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[00:27:19 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:27:19 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:85)
[00:27:19 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[00:27:19 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
[00:27:19 WARN]:        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityShootBowEvent(CraftEventFactory.java:657)
[00:27:19 WARN]:        at net.minecraft.world.item.ItemBow.a(ItemBow.java:68)
[00:27:19 WARN]:        at net.minecraft.world.item.ItemStack.a(ItemStack.java:805)
[00:27:19 WARN]:        at net.minecraft.world.entity.EntityLiving.fn(EntityLiving.java:4121)
[00:27:19 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1951)
[00:27:19 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:42)
[00:27:19 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInBlockDig.a(PacketPlayInBlockDig.java:15)
[00:27:19 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:50)
[00:27:19 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:27:19 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:151)
[00:27:19 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[00:27:19 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1348)
[00:27:19 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:202)
[00:27:19 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:124)
[00:27:19 WARN]:        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1325)
[00:27:19 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1318)
[00:27:19 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:134)
[00:27:19 WARN]:        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1296)
[00:27:19 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1184)
[00:27:19 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324)
[00:27:19 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[00:27:19 WARN]: [AdvancedEnchantments] §4Failed to activate effect '§fFIREBALL '
[00:27:19 WARN]: [AdvancedEnchantments] §cAdditional information: §7Error while activating effect
[00:27:20 WARN]: [AdvancedEnchantments] §4Failed to activate effect '§fINCREASE_DAMAGE:32'
[00:27:20 WARN]: [AdvancedEnchantments] §cAdditional information: §7activating location-based effect without a valid target (e.g. @Block), hunter, level 4

### "/ae plinfo" link

https://paste.md-5.net/icevetunaz

**Comment by ThomasWega** [comment]
Send your enchantment. It's most likely misconfigured
