### ISSUE TITLE
Arclight issues

### ISSUE THREAD

**Issue by SrT3ddy** [GC-spigot/AdvancedEnchantments#4242]
### Describe the bug

I'm using version 9.7.14 because I can't update from that version, as it gives the following error:

[06:51:36] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling AdvancedEnchantments v9.8.1 (Is it up to date?)
java.lang.NoClassDefFoundError: java/lang/constant/Constable
        at net.advancedplugins.ae.handlers.commands.MCI.<clinit>(MCI.java:53) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at net.advancedplugins.ae.features.sets.instances.ArmorSet.initSet(ArmorSet.java:49) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at net.advancedplugins.ae.features.sets.instances.ArmorSet.<init>(ArmorSet.java:44) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at net.advancedplugins.ae.features.sets.SetsManager.readSets(SetsManager.java:37) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at net.advancedplugins.ae.features.sets.SetsManager.<init>(SetsManager.java:26) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at net.advancedplugins.ae.Core.onEnable(Core.java:177) ~[?:?] {re:classloading,re:classloading,re:classloading}
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPluginMixin.java:263) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginMixin,pl:mixin:A,re:mixin}
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoaderMixin.java:342) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:JavaPluginLoaderMixin,pl:mixin:A}
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3] {re:classloading}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServerMixin.java:492) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServerMixin.java:406) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
        at net.minecraft.server.MinecraftServer.handler$zpo000$arclight$enablePlugins(MinecraftServerMixin.java:1995) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServerMixin.java:382) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServerMixin.java:308) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServerMixin.java:168) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1879) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:834) [?:?] {}
Caused by: java.lang.ClassNotFoundException: java.lang.constant.Constable
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoaderMixin.java:140) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoaderMixin.java:99) ~[arclight:arclight-1.16.5-1.0.25-7cf92be3] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:PluginClassLoaderMixin,pl:mixin:A}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
        ... 18 more

### How to reproduce

The error appears when starting the server

And when executing any AdvancedEnchantments command it returns: [Console/]: /AdvancedEnchantments

### "/ae plinfo" link

returns: [Console/]: /AdvancedEnchantments

### Server Log

https://mcpaste.io/e53d61b84abe7b0f

**Comment by GC-spigot** [comment]
Seems to be an archlight issue, looking into this
