### ISSUE TITLE
AOE

### ISSUE THREAD

**Issue by akiakyo** [GC-spigot/AdvancedEnchantments#4253]
### Describe the bug

I think this bug is on AOE something

### How to reproduce

I dont know

### Screenshots / Videos

[15:31:31 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v9.8.1
java.lang.NoClassDefFoundError: Could not initialize class net.advancedplugins.ae.impl.utils.AreaUtils
        at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.internal.AOETarget.getTargets(AOETarget.java:35) ~[AdvancedEnchantments-9.8.1.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.Targets.handleTargets(Targets.java:48) ~[AdvancedEnchantments-9.8.1.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.updateMain(ExecutionTask.java:242) ~[AdvancedEnchantments-9.8.1.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:96) ~[AdvancedEnchantments-9.8.1.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:65) ~[AdvancedEnchantments-9.8.1.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[AdvancedEnchantments-9.8.1.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.DefenseTrigger.playerHitPlayer(DefenseTrigger.java:58) ~[AdvancedEnchantments-9.8.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor977.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-409]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-409]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-409]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:265) ~[paper-1.20.4.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1254) ~[paper-1.20.4.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1109) ~[paper-1.20.4.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1053) ~[paper-1.20.4.jar:git-Paper-409]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1288) ~[paper-1.20.4.jar:git-Paper-409]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2222) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1061) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1471) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:968) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1135) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1321) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2283) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2787) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2711) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-409]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1455) ~[paper-1.20.4.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-409]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1432) ~[paper-1.20.4.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[paper-1.20.4.jar:git-Paper-409]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1506) ~[paper-1.20.4.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-409]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-409]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: LEASH_KNOT [in thread "Server thread"]
        at net.advancedplugins.ae.impl.utils.AreaUtils.<clinit>(AreaUtils.java:19) ~[AdvancedEnchantments-9.8.1.jar:?]
        ... 46 more

### "/ae plinfo" link

https://paste.md-5.net/fiyuzilose

### Server Log

https://mclo.gs/QJhgfLc

**Comment by GC-spigot** [comment]
Hi, will be sorted with an update later today

**Comment by Bali0531** [comment]
This is fixed in v9.8.2?
