### ISSUE TITLE
Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v9.8.2

### ISSUE THREAD

**Issue by serpentoi2** [GC-spigot/AdvancedEnchantments#4256]
### Describe the bug

(https://github.com/GC-spigot/AdvancedEnchantments/files/15221122/1.txt)

### How to reproduce

[1.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/15221146/1.txt

### Screenshots / Videos

[13:18:59 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v9.8.2
java.lang.NoClassDefFoundError: Could not initialize class net.advancedplugins.ae.impl.utils.AreaUtils
        at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.internal.AOETarget.getTargets(AOETarget.java:35) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.Targets.handleTargets(Targets.java:48) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.updateMain(ExecutionTask.java:242) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:96) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:65) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.AttackMobTrigger.playerHitMob(AttackMobTrigger.java:60) ~[Advanced Enchantments.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor844.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:268) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1255) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1110) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1054) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1289) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2223) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1471) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:319) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1354) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2181) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$3.a(ServerGamePacketListenerImpl.java:2778) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2702) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-318]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: Class org.bukkit.entity.EntityType does not have member field 'org.bukkit.entity.EntityType LEASH_KNOT' [in thread "Server thread"]
        at net.advancedplugins.ae.impl.utils.AreaUtils.<clinit>(AreaUtils.java:19) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.internal.AOETarget.getTargets(AOETarget.java:35) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.targets.Targets.handleTargets(Targets.java:48) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.updateMain(ExecutionTask.java:242) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:96) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:65) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[Advanced Enchantments.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.AttackMobTrigger.playerHitMob(AttackMobTrigger.java:60) ~[Advanced Enchantments.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor844.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-318]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-318]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:268) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1255) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1110) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1054) ~[paper-1.20.2.jar:git-Paper-318]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1289) ~[paper-1.20.2.jar:git-Paper-318]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2223) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1471) ~[?:?]
        at net.minecraft.world.entity.monster.piglin.PiglinBrute.hurt(PiglinBrute.java:103) ~[?:?]
        ... 22 more

### "/ae plinfo" link

https://paste.md-5.net/ixesetefuk

### Server Log

https://mcpaste.io/20f5d8efb141e6e7

**Comment by serpentoi2** [comment]
https://paste.md-5.net/ixesetefuk

**Comment by GC-spigot** [comment]
Solved next update
