### ISSUE TITLE
Failed to parse 5@victim from String to Integer. v9.8.2

### ISSUE THREAD

**Issue by serpentoi2** [GC-spigot/AdvancedEnchantments#4257]
### Describe the bug

[2.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/15221217/2.txt)

### How to reproduce

[AdvancedEnchantments] Failed to parse 5@victim from String to Integer.
[13:14:34] [Server thread/WARN]: java.lang.NumberFormatException: For input string: "5@victim"
[13:14:34] [Server thread/WARN]: 	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
[13:14:34] [Server thread/WARN]: 	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
[13:14:34] [Server thread/WARN]: 	at java.base/java.lang.Double.parseDouble(Double.java:792)
[13:14:34] [Server thread/WARN]: 	at Advanced Enchantments.jar//net.advancedplugins.ae.impl.utils.ASManager.parseInt(ASManager.java:646)
[13:14:34] [Server thread/WARN]: 	at Advanced Enchantments.jar//net.advancedplugins.ae.impl.utils.ASManager.parseInt(ASManager.java:636)
[13:14:34] [Server thread/WARN]: 	at Advanced Enchantments.jar//net.advancedplugins.ae.impl.effects.effects.effects.internal.DisableActivationEffect.executeEffect(DisableActivationEffect.java:28)
[13:14:34] [Server thread/WARN]: 	at Advanced Enchantments.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.activate(ExecutionTask.java:204)
[13:14:34] [Server thread/WARN]: 	at Advanced Enchantments.jar//net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:122)
[13:14:34] [Server thread/WARN]: 	at Advanced Enchantments.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:65)
[13:14:34] [Server thread/WARN]: 	at Advanced Enchantments.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80)
[13:14:34] [Server thread/WARN]: 	at Advanced Enchantments.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.AttackTrigger.playerHitMob(AttackTrigger.java:60)
[13:14:34] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor845.execute(Unknown Source)
[13:14:34] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[13:14:34] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81)
[13:14:34] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:14:34] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[13:14:34] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[13:14:34] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[13:14:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:268)
[13:14:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1255)
[13:14:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1110)
[13:14:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1054)
[13:14:34] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1289)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.damageEntity0(EntityLiving.java:2223)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.damageEntity0(EntityHuman.java:1066)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.world.entity.EntityLiving.a(EntityLiving.java:1471)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.a(EntityHuman.java:973)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.a(EntityPlayer.java:1130)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.world.entity.player.EntityHuman.d(EntityHuman.java:1326)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.level.EntityPlayer.d(EntityPlayer.java:2181)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection$3.a(PlayerConnection.java:2778)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity$1.a(PacketPlayInUseEntity.java:24)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:80)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2702)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:67)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$0(PlayerConnectionUtils.java:53)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(TickTask.java:18)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1324)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1301)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1294)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bp(IAsyncTaskHandler.java:114)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1410)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1156)
[13:14:34] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[13:14:34] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)

### Screenshots / Videos

[2.txt](https://github.com/GC-spigot/AdvancedEnchantments/files/15221220/2.txt)

### "/ae plinfo" link

https://paste.md-5.net/ixesetefuk

### Server Log

https://mcpaste.io/74b8a6b258311bed

**Comment by ThomasWega** [comment]
You are probably missing space in your enchantment config. 5@victim is your issue

**Comment by serpentoi2** [comment]
Same thinking but sadly.. there's no space all of them.. i cheked them one by one...

**Comment by serpentoi2** [comment]
Wait after months i just found the error... "5 @victim" no wonder why its giving a error on the console... it should be a capital V to work...

**Comment by ThomasWega** [comment]
Glad it's solved
