### ISSUE TITLE
Mcmmo Support Bug

### ISSUE THREAD

**Issue by Nch0001** [GC-spigot/AdvancedEnchantments#4306]
### Describe the bug

```java
20.05 19:24:46 [Server] [ERROR] Could not pass event BlockBreakEvent to AdvancedEnchantments v9.8.3
20.05 19:24:46 [Server] [INFO] java.lang.NoClassDefFoundError: com/gmail/nossr50/util/random/ProbabilityUtil
20.05 19:24:46 [Server] [INFO] at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.miningCheck(McMMOHook.java:139) ~[AdvancedEnchantments-9.8.3.jar:?]
20.05 19:24:46 [Server] [INFO] at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.processBlockBreakEvent(McMMOHook.java:128) ~[AdvancedEnchantments-9.8.3.jar:?]
20.05 19:24:46 [Server] [INFO] at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:205) ~[AdvancedEnchantments-9.8.3.jar:?]
20.05 19:24:46 [Server] [INFO] at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:83) ~[AdvancedEnchantments-9.8.3.jar:?]
20.05 19:24:46 [Server] [INFO] at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.8.3.jar:?]
20.05 19:24:46 [Server] [INFO] at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1045.execute(Unknown Source) ~[?:?]
20.05 19:24:46 [Server] [INFO] at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
20.05 19:24:46 [Server] [INFO] at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
20.05 19:24:46 [Server] [INFO] at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
20.05 19:24:46 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
20.05 19:24:46 [Server] [INFO] at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
20.05 19:24:46 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
20.05 19:24:46 [Server] [INFO] at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:375) ~[?:?]
20.05 19:24:46 [Server] [INFO] at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:334) ~[?:?]
```

### How to reproduce

Use `BLOCK_BREAK @trench{r=3}` with mcmmo

### "/ae plinfo" link

https://paste.md-5.net/sucoyowece

**Comment by ArmonicPvP** [comment]
Your mcMMO version is over 5 years old.

**Comment by ThomasWega** [comment]
> Your mcMMO version is over 5 years old.

Appreciate it, thank you <3

**Comment by Nch0001** [comment]
> Your mcMMO version is over 5 years old.

it is not

2.1.231 
was released Mar 10, 2024
