### ISSUE TITLE
ERROR: Could not pass event EffectsActivateEvent to AdvancedEnchantments v9.8.5

### ISSUE THREAD

**Issue by Adapineapple** [GC-spigot/AdvancedEnchantments#4307]
### Describe the bug

[14:12:13 ERROR]: Could not pass event EffectsActivateEvent to AdvancedEnchantments v9.8.5
java.lang.NullPointerException: null
        at java.io.Reader.<init>(Reader.java:168) ~[?:?]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:123) ~[?:?]
        at net.advancedplugins.ae.utils.lang.Lang.getInternalLocale(Lang.java:229) ~[AdvancedEnchantments-9.8.5.jar:?]
        at net.advancedplugins.ae.utils.lang.Lang.getRaw(Lang.java:134) ~[AdvancedEnchantments-9.8.5.jar:?]
        at net.advancedplugins.ae.utils.lang.Lang.get(Lang.java:112) ~[AdvancedEnchantments-9.8.5.jar:?]
        at net.advancedplugins.ae.globallisteners.listeners.UsedActionbarListener.onEffect(UsedActionbarListener.java:44) ~[AdvancedEnchantments-9.8.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor617.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:78) ~[AdvancedEnchantments-9.8.5.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:65) ~[AdvancedEnchantments-9.8.5.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[AdvancedEnchantments-9.8.5.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.ShootMobTrigger.onProjectileHitEvent(ShootMobTrigger.java:89) ~[AdvancedEnchantments-9.8.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor588.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:267) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1203) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1188) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1120) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1081) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1237) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.world.entity.LivingEntity.actuallyHurt(LivingEntity.java:2243) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1480) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.hurt(Zombie.java:319) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:411) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:211) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:202) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:304) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:240) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:113) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1409) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:1318) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$8(ServerLevel.java:916) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:896) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

when I shot a bow that that have AdvancedEnchantment. It will generate the error message in my console

### "/ae plinfo" link

https://paste.md-5.net/iregeyorag

### Server Log

https://mcpaste.io/99e64afcf280df50

**Comment by ArmonicPvP** [comment]
You should attach your enchantments.yml and the name of the enchantment you used

**Comment by GC-spigot** [comment]
Might be an invalid locale file set in config.yml - what locale do you have set?
