### ISSUE TITLE
giveitem command issue (Blackscroll)

### ISSUE THREAD

**Issue by OneRogue** [GC-spigot/AdvancedEnchantments#432]
When i try using the command in-game or in console to give myself a black scroll, i get this error.
All the other items work fine, just the black scroll.

[23:01:14 INFO]: OneRogueYT issued server command: /ae giveitem OneRogueYT blackscroll 1
[23:01:14 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ae' in plugin AdvancedEnchantments v5.5.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[spigot.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[spigot.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot.jar:git-Spigot-f09662d-f40143e]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot.jar:git-Spigot-f09662d-f40143e]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot.jar:git-Spigot-f09662d-f40143e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NumberFormatException: For input string: ""
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_191]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_191]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_191]
        at n3kas.ae.handlers.commands.MCI.e(MCI.java:283) ~[AdvancedEnchantments-5.5.6.jar:?]
        at n3kas.ae.handlers.commands.MainCommand.onCommand(MainCommand.java:186) ~[AdvancedEnchantments-5.5.6.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-f09662d-f40143e]
        ... 15 more

**Comment by GC-spigot** [comment]
Use `/ae giveitem OneRogueYT blackscroll 1 100`
