### ISSUE TITLE
Telepathy - McMMO hook bug

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4324]
### Describe the bug

When mining ores that AREN'T placed by hand with a telepathy pickaxe, it throws an McMMO error and the telepathy doesn't work 

```[13:47:05 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.8.7
java.lang.NoClassDefFoundError: com/gmail/nossr50/util/random/ProbabilityUtil
        at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.miningCheck(McMMOHook.java:139) ~[AdvancedEnchantments-9.8.7.jar:?]
        at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.processBlockBreakEvent(McMMOHook.java:128) ~[AdvancedEnchantments-9.8.7.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:205) ~[AdvancedEnchantments-9.8.7.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:83) ~[AdvancedEnchantments-9.8.7.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.8.7.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor635.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:git-Axolotl-"f699bcf"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:57) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:386) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:345) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:283) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1840) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1350) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:195) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1298) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1186) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.gmail.nossr50.util.random.ProbabilityUtil
        ... 32 more```

### How to reproduce

Mine ores with telepathy

### Screenshots / Videos

_No response_

### "/ae plinfo" link

https://paste.md-5.net/udubepazij

### Server Log

_No response_

**Comment by GC-spigot** [comment]
Update mcmmo, it is 2 years old. We dont support that one anymore.

**Comment by JHarris12345** [comment]
> Update mcmmo, it is 2 years old. We dont support that one anymore.

Ok but I just updated McMMO and now it's giving

```
[14:39:08 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.8.7
java.lang.NoSuchMethodError: 'org.bukkit.entity.Item com.gmail.nossr50.util.Misc.spawnItemNaturally(org.bukkit.entity.Player, org.bukkit.Location, org.bukkit.inventory.ItemStack, com.gmail.nossr50.api.ItemSpawnReason)'
        at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.miningCheck(McMMOHook.java:153) ~[AdvancedEnchantments-9.8.7 (1).jar:?]
        at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.processBlockBreakEvent(McMMOHook.java:128) ~[AdvancedEnchantments-9.8.7 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:205) ~[AdvancedEnchantments-9.8.7 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:83) ~[AdvancedEnchantments-9.8.7 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.8.7 (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor636.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:git-Axolotl-"f699bcf"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:57) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:386) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:345) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:283) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1840) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1350) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:195) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1298) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1186) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]```

**Comment by JHarris12345** [comment]
Which is a correct error as the latest McMMO doesn't have that method. So that's an AdvancedEnchantment error
