### ISSUE TITLE
Telepathy McMMO hook issue

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4375]
### Describe the bug

When mining a naturally generated ore with a telepathy pickaxe, it throws this error and doesn't work

```
[15:57:14 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.9.3
java.lang.NoSuchMethodError: 'org.bukkit.entity.Item com.gmail.nossr50.util.Misc.spawnItemNaturally(org.bukkit.entity.Player, org.bukkit.Location, org.bukkit.inventory.ItemStack, com.gmail.nossr50.api.ItemSpawnReason)'
        at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.miningCheck(McMMOHook.java:153) ~[AdvancedEnchantments-9.9.3.jar:?]
        at net.advancedplugins.ae.impl.utils.hooks.plugins.McMMOHook.processBlockBreakEvent(McMMOHook.java:128) ~[AdvancedEnchantments-9.9.3.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:205) ~[AdvancedEnchantments-9.9.3.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:83) ~[AdvancedEnchantments-9.9.3.jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.9.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1490.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:git-Axolotl-"f699bcf"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:57) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:386) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:345) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:221) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1840) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1350) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:195) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1298) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1186) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]```

### How to reproduce

Steps above

### Screenshots / Videos

_No response_

### "/ae plinfo" link

https://paste.md-5.net/jiwonirowi

### Server Log

_No response_

**Comment by ThomasWega** [comment]
Just tried it and all seems to work fine. Are you sure you are on latest on everything?

**Comment by ThomasWega** [comment]
Actually, I see now

**Comment by ThomasWega** [comment]
Will be fixed in the next update. When 2.2.013 actually comes out oficially
