### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by wundertraume** [GC-spigot/AdvancedEnchantments#4384]
### Describe the bug

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/118831819/26f623b6-5de1-4f6d-9e48-3e378a458624)

### How to reproduce

[17:11:12] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to AdvancedEnchantments v9.9.4
java.lang.NoClassDefFoundError: Could not initialize class net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.hasTag(NBTCompound.java:654) ~[AdvancedEnchantments-9.9.4.jar:?]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.hasKey(NBTCompound.java:641) ~[AdvancedEnchantments-9.9.4.jar:?]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.utils.nbt.NBTapi.contains(NBTapi.java:291) ~[AdvancedEnchantments-9.9.4.jar:?]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.items.AEItem.onInteractEvent(AEItem.java:59) ~[AdvancedEnchantments-9.9.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor609.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2244-21ec259]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:550) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:204) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1863) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1513) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1484) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1593) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1275) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:332) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception net.advancedplugins.ae.impl.utils.nbt.utils.NbtApiException: No fitting mapping found for version Unknown. This is a bug! [in thread "Server thread"]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.impl.utils.nbt.utils.MojangToMapping.getMapping(MojangToMapping.java:205) ~[AdvancedEnchantments-9.9.4.jar:?]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:272) ~[AdvancedEnchantments-9.9.4.jar:?]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<init>(ReflectionMethod.java:291) ~[AdvancedEnchantments-9.9.4.jar:?]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.<clinit>(ReflectionMethod.java:24) ~[AdvancedEnchantments-9.9.4.jar:?]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.hasTag(NBTCompound.java:654) ~[AdvancedEnchantments-9.9.4.jar:?]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.impl.utils.nbt.backend.NBTCompound.hasKey(NBTCompound.java:641) ~[AdvancedEnchantments-9.9.4.jar:?]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.utils.nbt.NBTapi.contains(NBTapi.java:291) ~[AdvancedEnchantments-9.9.4.jar:?]
	at AdvancedEnchantments-9.9.4.jar/net.advancedplugins.ae.items.AEItem.onInteractEvent(AEItem.java:59) ~[AdvancedEnchantments-9.9.4.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor609.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2244-21ec259]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1949) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1513) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1491) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1484) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1443) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1450) ~[purpur-1.21.jar:1.21-2244-21ec259]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.21.jar:1.21-2244-21ec259]
	... 2 more

### "/ae plinfo" link

https://paste.md-5.net/ihaboloned

**Comment by ThomasWega** [comment]
Fixed in latest
