### ISSUE TITLE
Could not pass event BlockBreakEvent to AdvancedEnchantments v9.9.7

### ISSUE THREAD

**Issue by SrMonsterYT** [GC-spigot/AdvancedEnchantments#4407]
### Describe the bug

I updated the plugin and it started generating errors in the console, I don't know how this is happening

error: https://mclo.gs/xaXwsIm

server: git-Pufferfish-47 (MC: 1.20.4)

### How to reproduce

update for 9.9.7

### "/ae plinfo" link

AdvancedEnchantments 9.9.7

**Comment by MiddleSand** [comment]
i've spotted this same error with 9.97 on paper 1.21 with the same stack trace

**Comment by MiddleSand** [comment]
found steps to reproduce with this setup https://paste.md-5.net/fiducukika

- enchant pickaxe with Trench 9 and Veinminer 3
- break a stone block
- observe error

[17:49:11 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.9.7
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "<parameter1>" is null
	at AdvancedEnchantments-9.9.7.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.targets.TargetType.classifyTarget(TargetType.java:58) ~[AdvancedEnchantments-9.9.7.jar:?]
	at AdvancedEnchantments-9.9.7.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.targets.internal.VeinTarget.getTargets(VeinTarget.java:27) ~[AdvancedEnchantments-9.9.7.jar:?]
	at AdvancedEnchantments-9.9.7.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.targets.Targets.handleTargets(Targets.java:48) ~[AdvancedEnchantments-9.9.7.jar:?]
	at AdvancedEnchantments-9.9.7.jar/net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.updateMain(ExecutionTask.java:243) ~[AdvancedEnchantments-9.9.7.jar:?]
	at AdvancedEnchantments-9.9.7.jar/net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:96) ~[AdvancedEnchantments-9.9.7.jar:?]
	at AdvancedEnchantments-9.9.7.jar/net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:65) ~[AdvancedEnchantments-9.9.7.jar:?]
	at AdvancedEnchantments-9.9.7.jar/net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[AdvancedEnchantments-9.9.7.jar:?]
	at AdvancedEnchantments-9.9.7.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.9.7.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor57.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-38-1f5db50]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-38-1f5db50]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-38-1f5db50]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:383) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:306) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1785) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:36) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1478) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1456) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1449) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1408) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1415) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1260) ~[paper-1.21.jar:1.21-38-1f5db50]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-38-1f5db50]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
	
best of luck y'all

**Comment by GC-spigot** [comment]
Solved next update!
