### ISSUE TITLE
[AdvancedEnchantments] Task #1152 for AdvancedEnchantments

### ISSUE THREAD

**Issue by IAmRiven** [GC-spigot/AdvancedEnchantments#4412]
### Describe the bug

I have this crash:
[04:51:38 WARN]: [AdvancedEnchantments] Task #1152 for AdvancedEnchantments v9.9.6 generated an exception
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.ae.impl.effects.armorutils.ArmorType.getEquipmentSlot()" because the return value of "net.advancedplugins.ae.impl.effects.armorutils.ArmorEquipEvent.getType()" is null
        at net.advancedplugins.ae.impl.effects.armorutils.ArmorListener.lambda$runEventQueue$0(ArmorListener.java:57) ~[AdvancedEnchantments-9.9.6.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-496]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-496]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

A user was mining Netherrack with Smelting II and these errors appear in the console

### Screenshots / Videos

![image](https://github.com/GC-spigot/AdvancedEnchantments/assets/108624285/dd46260f-bdcd-454f-a106-b23dc8bed623)

### "/ae plinfo" link

https://paste.md-5.net/yakusarilo

### Server Log

https://mcpaste.io/95a9ba1a2aa21772

**Comment by IAmRiven** [comment]
The user had the pickaxe with an old Smelting, before I updated/changed the enchantments
