### ISSUE TITLE
BlockBreakEvent

### ISSUE THREAD

**Issue by dzakwaniqbal** [GC-spigot/AdvancedEnchantments#4413]
### Describe the bug

[22:30:41 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.9.8
java.lang.NullPointerException: Cannot invoke "String.split(String)" because "<parameter1>" is null
        at AdvancedEnchantments-9.9.8.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.targets.TargetType.classifyTarget(TargetType.java:58) ~[AdvancedEnchantments-9.9.8.jar:?]
        at AdvancedEnchantments-9.9.8.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.targets.internal.VeinTarget.getTargets(VeinTarget.java:27) ~[AdvancedEnchantments-9.9.8.jar:?]
        at AdvancedEnchantments-9.9.8.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.targets.Targets.handleTargets(Targets.java:48) ~[AdvancedEnchantments-9.9.8.jar:?]
        at AdvancedEnchantments-9.9.8.jar/net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.updateMain(ExecutionTask.java:243) ~[AdvancedEnchantments-9.9.8.jar:?]
        at AdvancedEnchantments-9.9.8.jar/net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask.init(ExecutionTask.java:96) ~[AdvancedEnchantments-9.9.8.jar:?]
        at AdvancedEnchantments-9.9.8.jar/net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.run(ActionExecution.java:65) ~[AdvancedEnchantments-9.9.8.jar:?]
        at AdvancedEnchantments-9.9.8.jar/net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:80) ~[AdvancedEnchantments-9.9.8.jar:?]
        at AdvancedEnchantments-9.9.8.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.9.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor610.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-147-e41d44f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:378) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:337) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:301) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1845) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1562) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-147-e41d44f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

Please FIX

### "/ae plinfo" link

https://paste.md-5.net/guzefevisu

**Comment by GC-spigot** [comment]
Solved next update, thanks for reporting!
