### ISSUE TITLE
1.21 Startup Error

### ISSUE THREAD

**Issue by Rexmen1** [GC-spigot/AdvancedEnchantments#4424]
### Describe the bug

[07:44:04 INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v9.9.9
[07:44:04 INFO]: [AdvancedEnchantments] Loading Minecraft Version MC1_21_R1
[07:44:04 INFO]: [AdvancedEnchantments] Loaded 0 armor sets.
[07:44:04 INFO]: [AdvancedEnchantments] Loaded 0 weapons.
[07:44:04 WARN]: [org.bukkit.craftbukkit.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[07:44:04 WARN]: java.lang.Exception
[07:44:04 WARN]:        at org.bukkit.craftbukkit.legacy.CraftLegacy.<clinit>(CraftLegacy.java:270)
[07:44:04 WARN]:        at org.bukkit.craftbukkit.util.CraftMagicNumbers.fromLegacy(CraftMagicNumbers.java:238)
[07:44:04 WARN]:        at org.bukkit.Material.getMaterial(Material.java:4926)
[07:44:04 WARN]:        at org.bukkit.Material.matchMaterial(Material.java:4971)
[07:44:04 WARN]:        at AdvancedEnchantments-9.9.9.jar//net.advancedplugins.ae.utils.AManager.matchMaterial(AManager.java:317)
[07:44:04 WARN]:        at AdvancedEnchantments-9.9.9.jar//net.advancedplugins.ae.utils.AManager.addMaterial(AManager.java:1332)
[07:44:04 WARN]:        at AdvancedEnchantments-9.9.9.jar//net.advancedplugins.ae.utils.AManager.initMaterials(AManager.java:1298)
[07:44:04 WARN]:        at AdvancedEnchantments-9.9.9.jar//net.advancedplugins.ae.Core.onEnable(Core.java:187)
[07:44:04 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
[07:44:04 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[07:44:04 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[07:44:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
[07:44:04 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629)
[07:44:04 WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578)
[07:44:04 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:752)
[07:44:04 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:514)
[07:44:04 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327)
[07:44:04 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1219)
[07:44:04 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[07:44:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[07:44:10 INFO]: [AdvancedEnchantments] Successfully hooked into economy plugin (Vault)

### How to reproduce

getting this startup error

### "/ae plinfo" link

https://paste.md-5.net/gijadubawe

**Comment by GC-spigot** [comment]
Do you use a modified configuration? From this error it sounds like there's numbers as materials, which hasnt been valid in 10+ years

**Comment by ThomasWega** [comment]
Try with fresh files please
