### ISSUE TITLE
Trench is broken in 9.9.14

### ISSUE THREAD

**Issue by KevinAlexZhao** [GC-spigot/AdvancedEnchantments#4461]
### Describe the bug

Trench does not work when applied to the appropriate tools no matter the tier.

### How to reproduce

Apply any Trench book to the appropriate tool, it will not work.

### Screenshots / Videos

https://streamable.com/m3b4pm

### "/ae plinfo" link

https://paste.md-5.net/wihetunawa

**Comment by ThomasWega** [comment]
Hey! I have just tried it out and it works completely fine? We'd need more info to figure out what's wrong

**Comment by svyoshi** [comment]
[18:50:20 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.9.17
java.lang.NullPointerException: Cannot invoke "java.lang.Class.cast(Object)" because "net.advancedplugins.ae.impl.utils.ReallyFastBlockHandler.b" is null
        at AdvancedEnchantments-9.9.17.jar/net.advancedplugins.ae.impl.utils.ReallyFastBlockHandler.<init>(ReallyFastBlockHandler.java:72) ~[AdvancedEnchantments-9.9.17.jar:?]
        at AdvancedEnchantments-9.9.17.jar/net.advancedplugins.ae.impl.utils.ReallyFastBlockHandler.getForWorld(ReallyFastBlockHandler.java:27) ~[AdvancedEnchantments-9.9.17.jar:?]
        at AdvancedEnchantments-9.9.17.jar/net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.breakBlock(DropsHandler.java:626) ~[AdvancedEnchantments-9.9.17.jar:?]
        at AdvancedEnchantments-9.9.17.jar/net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.breakAndDropExp(DropsHandler.java:554) ~[AdvancedEnchantments-9.9.17.jar:?]
        at AdvancedEnchantments-9.9.17.jar/net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:509) ~[AdvancedEnchantments-9.9.17.jar:?]
        at AdvancedEnchantments-9.9.17.jar/net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:84) ~[AdvancedEnchantments-9.9.17.jar:?]
        at AdvancedEnchantments-9.9.17.jar/net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.9.17.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor250.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:84) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-108-73a863b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-108-73a863b]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-108-73a863b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:383) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:342) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:306) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1785) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:51) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:20) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1536) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1513) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1506) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1465) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1472) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1317) ~[paper-1.21.jar:1.21-108-73a863b]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.jar:1.21-108-73a863b]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

I am also encountering issues with Trench enchant. Throwing a nullpointer in BlockBreakEvent everytime I use a pickaxe with the enchant applied.

**Comment by GC-spigot** [comment]
Solved this error next update
