### ISSUE TITLE
NullPointerException broken pickaxes

### ISSUE THREAD

**Issue by JHarris12345** [GC-spigot/AdvancedEnchantments#4489]
### Describe the bug

There is an NPE error thrown when mining with a pickaxe that has Telepathy and Auto Smelt on (not sure if it's just 1 that's causing it). This is likely linked to the recent McMMO compatability fix in my other issue. Here is the error:

`
[00:28:03 ERROR]: Could not pass event BlockBreakEvent to AdvancedEnchantments v9.9.17
java.lang.NullPointerException: Cannot invoke "java.lang.Class.cast(Object)" because "net.advancedplugins.ae.impl.utils.ReallyFastBlockHandler.b" is null
        at net.advancedplugins.ae.impl.utils.ReallyFastBlockHandler.<init>(ReallyFastBlockHandler.java:72) ~[AdvancedEnchantments-9.9.17 (1).jar:?]
        at net.advancedplugins.ae.impl.utils.ReallyFastBlockHandler.getForWorld(ReallyFastBlockHandler.java:27) ~[AdvancedEnchantments-9.9.17 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.breakBlock(DropsHandler.java:626) ~[AdvancedEnchantments-9.9.17 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.breakAndDropExp(DropsHandler.java:554) ~[AdvancedEnchantments-9.9.17 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.handlers.DropsHandler.handle(DropsHandler.java:509) ~[AdvancedEnchantments-9.9.17 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:84) ~[AdvancedEnchantments-9.9.17 (1).jar:?]
        at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.MiningTrigger.onBlockBreak(MiningTrigger.java:130) ~[AdvancedEnchantments-9.9.17 (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1482.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:git-Axolotl-"f699bcf"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:57) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[axolotl-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:386) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:345) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:283) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1840) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:42) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1350) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.wrapRunnable(MinecraftServer.java:195) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1327) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1320) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1298) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1186) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[axolotl-1.20.2.jar:git-Axolotl-"f699bcf"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]`

### How to reproduce

Mine with a telepathy & auto smelt pick (or just 1 of them, it might not be both)

### "/ae plinfo" link

https://paste.md-5.net/gosetufobo

**Comment by GC-spigot** [comment]
Solved
