### ISSUE TITLE
Repeating Effect

### ISSUE THREAD

**Issue by Cryptics1999** [GC-spigot/AdvancedEnchantments#4542]
### Describe the bug

1.21 Issue

aquaman:
  display: '%group-color%Aquaman'
  description: Breath under water
  applies-to: Helmets
  type: REPEATING
  group: ADMIN
  applies:
    - ALL_HELMET
  levels:
    '1':
      time: 2
      conditions:
        - '%is under water% = TRUE : %allow%'
        - '%is under water% = FALSE : %stop%'
      effects:
        - POTION:WATER_BREATHING:0:200

Works on older versions

[22:56:42 WARN]: java.lang.ClassCastException: class net.advancedplugins.ae.impl.utils.hooks.plugins.AdvancedSkillsHook cannot be cast to class net.advancedplugins.ae.impl.utils.hooks.plugins.AdvancedEnchantmentsHook (net.advancedplugins.ae.impl.utils.hooks.plugins.AdvancedSkillsHook and net.advancedplugins.ae.impl.utils.hooks.plugins.AdvancedEnchantmentsHook are in unnamed module of loader 'AdvancedEnchantments-9.10.2.jar' @5d828153)
[22:56:42 WARN]:        at AdvancedEnchantments-9.10.2.jar//net.advancedplugins.ae.impl.effects.effects.variables.DynamicVariable.getValue(DynamicVariable.java:182)
[22:56:42 WARN]:        at AdvancedEnchantments-9.10.2.jar//net.advancedplugins.ae.impl.effects.effects.variables.Variables.replaceVariables(Variables.java:45)
[22:56:42 WARN]:        at AdvancedEnchantments-9.10.2.jar//net.advancedplugins.ae.impl.effects.effects.conditions.Fractor.parseCondition(Fractor.java:89)
[22:56:42 WARN]:        at AdvancedEnchantments-9.10.2.jar//net.advancedplugins.ae.impl.effects.effects.conditions.Fractor.getResult(Fractor.java:66)
[22:56:42 WARN]:        at AdvancedEnchantments-9.10.2.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecution.build(ActionExecution.java:171)
[22:56:42 WARN]:        at AdvancedEnchantments-9.10.2.jar//net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:83)
[22:56:42 WARN]:        at AdvancedEnchantments-9.10.2.jar//net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.RepeatingTrigger$1.run(RepeatingTrigger.java:155)
[22:56:42 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86)
[22:56:42 WARN]:        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475)
[22:56:42 WARN]:        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1740)
[22:56:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:499)
[22:56:42 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1612)
[22:56:42 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1312)
[22:56:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:335)
[22:56:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[22:56:42 INFO]: [AdvancedEnchantments ERROR] Could not pass ClassCastException: class net.advancedplugins.ae.impl.utils.hooks.plugins.AdvancedSkillsHook cannot be cast to class net.advancedplugins.ae.impl.utils.hooks.plugins.AdvancedEnchantmentsHook (net.advancedplugins.ae.impl.utils.hooks.plugins.AdvancedSkillsHook and net.advancedplugins.ae.impl.utils.hooks.plugins.AdvancedEnchantmentsHook are in unnamed module of loader 'AdvancedEnchantments-9.10.2.jar' @5d828153)
[22:56:42 INFO]:    Class: AdvancedEnchantments-9.10.2.jar//net.advancedplugins.ae.impl.effects.effects.variables.DynamicVariable.getValue(DynamicVariable.java:182)
[22:56:42 INFO]:    Extra info: Invalid condition: %is under water% = true : %allow%; mc[1210];
[22:56:42 INFO]: If you cannot indentify cause of this, contact developer providing this report. 

### How to reproduce

Server on 1.21
Newest AE version
Use the helmet under water
no effect

### "/ae plinfo" link

https://paste.md-5.net/cesixofevi

**Comment by xProMDFKx** [comment]
Tested by me: The enchant works on 1.20.4 but not on 1.21

**Comment by xProMDFKx** [comment]
**also: on 1.20.4 is spamming that error as well, but the enchant work**

**Comment by GC-spigot** [comment]
Solved next update!
