### ISSUE TITLE
How do i use the api to create custom effects

### ISSUE THREAD

**Issue by Mardssss** [GC-spigot/AdvancedEnchantments#4586]
### Describe the bug

https://www.spigotmc.org/resources/advancedenchantments-api.76819/
this is prety much outdated... can you guys tell me how do i use the api 
```java
package org.github.mardssss.aeaddon.effects;


import net.advancedplugins.ae.impl.effects.effects.actions.execution.ExecutionTask;
import net.advancedplugins.ae.impl.effects.effects.effects.AdvancedEffect;
import org.bukkit.ChatColor;
import org.bukkit.entity.LivingEntity;
import org.bukkit.plugin.java.JavaPlugin;

public class NewBleed extends AdvancedEffect {
    public NewBleed(JavaPlugin javaPlugin) {
        super(javaPlugin, "NEWBLEED");
    }

    @Override
    public boolean executeEffect(ExecutionTask task, LivingEntity player, String[] args) {
        // Damage the entity
        player.damage(5.0); // adjust the damage amount as needed

        // Send a message to the player
        player.sendMessage(ChatColor.RED + "You're bleeding!");

        return true; // indicate that the effect was executed successfully
    }
}
```
```java
package org.github.mardssss.aeaddon;

import net.advancedplugins.ae.api.AEAPI;
import org.bukkit.plugin.java.JavaPlugin;
import org.github.mardssss.aeaddon.effects.NewBleed;

public final class AEAddon extends JavaPlugin {

    @Override
    public void onEnable() {
        // Plugin startup logic
        AEAPI.registerEffect(this,new NewBleed(this));
    }

    @Override
    public void onDisable() {
        // Plugin shutdown logic
    }
}
```
keep in mind that i am using the plugin internal api 

### How to reproduce

```
[19:27:07 INFO]: [AEAddon] Enabling AEAddon v1.0
[19:27:08 ERROR]: Error occurred while enabling AEAddon v1.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.ae.impl.effects.effects.effects.EffectStorage.register(org.bukkit.plugin.java.JavaPlugin, net.advancedplugins.ae.impl.effects.effects.effects.AdvancedEffect)" because the return value of "net.advancedplugins.ae.impl.effects.effects.EffectsHandler.getEffectStorage()" is null
        at net.advancedplugins.ae.api.AEAPI.registerEffect(AEAPI.java:74) ~[AEAddon.jar:?]
        at org.github.mardssss.aeaddon.AEAddon.onEnable(AEAddon.java:12) ~[AEAddon.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[sakura-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[sakura-1.20.4.jar:git-Sakura-"54879e8"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[sakura-1.20.4.jar:git-Sakura-"54879e8"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[sakura-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[sakura-1.20.4.jar:git-Sakura-"54879e8"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[sakura-1.20.4.jar:git-Sakura-"54879e8"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:676) ~[sakura-1.20.4.jar:git-Sakura-"54879e8"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[sakura-1.20.4.jar:git-Sakura-"54879e8"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:314) ~[sakura-1.20.4.jar:git-Sakura-"54879e8"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1137) ~[sakura-1.20.4.jar:git-Sakura-"54879e8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[sakura-1.20.4.jar:git-Sakura-"54879e8"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:27:08 INFO]: [AEAddon] Disabling AEAddon v1.0
```

### "/ae plinfo" link

https://paste.md-5.net/caduyexefi

**Comment by ThomasWega** [comment]
Is AdvancedEnchantments set as depend in your plugin.yml?

**Comment by Mardssss** [comment]
i already figured out how to do it
```
public class DoHarmMard extends AdvancedEffect {
    public DoHarmMard(JavaPlugin javaPlugin) {
        super(javaPlugin, "DO_HARM_MARD");
    }
    public boolean executeEffect(ExecutionTask task, LivingEntity player, String[] args) {
        EntityDamageEvent event = (EntityDamageEvent) task.getBuilder().getEvent();
        if (event instanceof EntityDamageByEntityEvent) {
            EntityDamageByEntityEvent entityEvent = (EntityDamageByEntityEvent) event;
            Entity damager = entityEvent.getDamager();
            Entity target = entityEvent.getEntity();

            if (target instanceof LivingEntity && !target.isDead()) { // <--- Add this check
                double damage = Double.parseDouble(args[0]);
                DamageHandler.damageIgnoringArmor((LivingEntity) target, damage);
                return true; // indicate that the effect was executed successfully
            }
            return false;
        }
        return false; // indicate that the effect was not executed successfully
    }

    /*public boolean executeEffect(ExecutionTask task, LivingEntity player, String[] args) {
        // Damage the target
        double damage = Double.parseDouble(args[0]);

        LivingEntity target = this.getOtherEntity(player, task);
        if (target == null || target.isDead()) {
            // Target is invalid or dead, don't attempt to damage
            return false; // indicate that the effect was not executed successfully
        }

        DamageHandler.damageIgnoringArmor(target,damage);
        return true; // indicate that the effect was executed successfully
    }*/
}
``` is this ok? keep in mind that i am using my own damagehandler... why when the entities dies i causes an error? not actualy a error but it print out a message to the console saying like "failed to execute effect EFFECTNAME"...

**Comment by ThomasWega** [comment]
You probably don't set a killer to the entity if it dies. Glad you were able to figure it out. Closing
