### ISSUE TITLE
1.17.1 compatibility issue.

### ISSUE THREAD

**Issue by axeldupuy** [GC-spigot/AdvancedEnchantments#4649]
### Describe the bug

![image](https://github.com/user-attachments/assets/3e5a04c2-440f-438f-8026-0b6e5402b127)
[00:17:36 INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v9.11.6
[00:17:37 ERROR]: [AdvancedEnchantments] AdvancedEnchantments only supports 1.17 or newer Minecraft versions.
[00:17:37 ERROR]: [AdvancedEnchantments] Last plugin's version to support 1.8.8: 9.0.0b81, 1.17 or lower: 9.8.0 - download it from previous versions.
[00:17:37 INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v9.11.6
[00:17:37 ERROR]: Error occurred while disabling AdvancedEnchantments v9.11.6 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.ae.impl.effects.effects.EffectsHandler.unload()" because "net.advancedplugins.ae.Core.U" is null
        at net.advancedplugins.ae.Core.onDisable(Core.java:567) ~[AdvancedEnchantments-9.11.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at net.advancedplugins.ae.Core.onEnable(Core.java:156) ~[AdvancedEnchantments-9.11.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:561) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:475) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:737) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:330) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:323) ~[patched_1.17.1.jar:git-Pufferfish-8]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

### How to reproduce

start server

### "/ae plinfo" link

none

**Comment by ThomasWega** [comment]
Will be fixed in the next update
