### ISSUE TITLE
Plugin is disabled

### ISSUE THREAD

**Issue by AliAga41** [GC-spigot/AdvancedEnchantments#4663]
### Describe the bug

[02:35:56] [Server thread/ERROR]: Error occurred while enabling AdvancedEnchantments v9.8.0 (Is it up to date?)
java.lang.NullPointerException: null
	at net.advancedplugins.ae.utils.nbt.NBTapi.addNBTTag(NBTapi.java:242) ~[?:?]
	at net.advancedplugins.ae.features.alchemist.AlchemistInventory.build(AlchemistInventory.java:133) ~[?:?]
	at net.advancedplugins.ae.features.alchemist.AlchemistInventory.<init>(AlchemistInventory.java:58) ~[?:?]
	at net.advancedplugins.ae.Core.onEnable(Core.java:223) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:832) [?:?]

### How to reproduce

Java 14
Mc version 1.15.2

### "/ae plinfo" link

ae

**Comment by SirJben** [comment]
Update your plugin and open a ticket in our Discord if the problem still occurs.
