### ISSUE TITLE
player event issue

### ISSUE THREAD

**Issue by AliAga41** [GC-spigot/AdvancedEnchantments#4667]
### Describe the bug

[14:10:31] [Server thread/ERROR]: Could not pass event PlayerItemHeldEvent to AdvancedEnchantments v9.8.0
java.lang.NoSuchMethodError: 'java.util.Set org.bukkit.persistence.PersistentDataContainer.getKeys()'
	at net.advancedplugins.ae.impl.utils.pdc.PDCHandler.getKeys(PDCHandler.java:140) ~[?:?]
	at net.advancedplugins.ae.utils.nbt.NBTapi.getEnchantPDCKeys(NBTapi.java:161) ~[?:?]
	at net.advancedplugins.ae.utils.nbt.NBTapi.getEnchantments(NBTapi.java:132) ~[?:?]
	at net.advancedplugins.ae.utils.nbt.NBTapi.getEnchantments(NBTapi.java:165) ~[?:?]
	at net.advancedplugins.ae.utils.nbt.NBTapi.hasEnchantments(NBTapi.java:126) ~[?:?]
	at net.advancedplugins.ae.enchanthandler.enchantments.LocalAPI.isValidForEnchantments(LocalAPI.java:32) ~[?:?]
	at net.advancedplugins.ae.abilities.ItemEnchantsReader.getRawAbilities(ItemEnchantsReader.java:54) ~[?:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.build(ActionExecutionBuilder.java:87) ~[?:?]
	at net.advancedplugins.ae.impl.effects.effects.actions.ActionExecutionBuilder.buildAndExecute(ActionExecutionBuilder.java:69) ~[?:?]
	at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.HoldItemTrigger.runCheck(HoldItemTrigger.java:114) ~[?:?]
	at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.HoldItemTrigger.executeCheck(HoldItemTrigger.java:75) ~[?:?]
	at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.HoldItemTrigger.executeCheck(HoldItemTrigger.java:57) ~[?:?]
	at net.advancedplugins.ae.impl.effects.effects.mechanics.triggers.internal.HoldItemTrigger.onItemSwitchEvent(HoldItemTrigger.java:227) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1031.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-387]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1608) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.PacketPlayInHeldItemSlot.a(SourceFile:30) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.PacketPlayInHeldItemSlot.a(SourceFile:8) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1106) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1099) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1060) ~[patched_1.15.2.jar:git-Paper-387]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:975) ~[patched_1.15.2.jar:git-Paper-387]
	at java.lang.Thread.run(Thread.java:832) [?:?]

### How to reproduce

cant recognize Held And InvClick event

### "/ae plinfo" link

https://paste.md-5.net/mazozeviku

### Server Log

https://mcpaste.io/eebc57184d16d8aa

**Comment by KanielOutisx** [comment]
@AliAga41 Update your plugin and that will resolve your issue....

**Comment by ThomasWega** [comment]
Thanks @KanielOutisx
