### ISSUE TITLE
Method not loaded! 'ITEMSTACK_SET_GLINT_OVERRIDE'

### ISSUE THREAD

**Issue by FourNineRugz** [GC-spigot/AdvancedEnchantments#4675]
### Describe the bug

[00:37:13 WARN]: net.advancedplugins.ae.impl.utils.nbt.backend.NbtApiException: Method not loaded! 'ITEMSTACK_SET_GLINT_OVERRIDE'
[00:37:13 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.run(ReflectionMethod.java:307)
[00:37:13 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.impl.utils.ASManager.makeItemGlow(ASManager.java:1720)
[00:37:13 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.impl.utils.ASManager.makeItemGlow(ASManager.java:1731)
[00:37:13 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.impl.utils.items.ItemBuilder.toItemStack(ItemBuilder.java:451)
[00:37:13 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.items.item.BlackScroll.build(BlackScroll.java:38)
[00:37:13 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.items.AEItem.onInventoryClick(AEItem.java:112)
[00:37:13 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1908.execute(Unknown Source)
[00:37:13 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[00:37:13 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:37:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:37:13 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[00:37:13 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[00:37:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[00:37:13 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3224)
[00:37:13 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[00:37:13 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[00:37:13 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[00:37:13 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:37:13 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[00:37:13 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[00:37:13 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535)
[00:37:13 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[00:37:13 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[00:37:13 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512)
[00:37:13 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505)
[00:37:13 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[00:37:13 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464)
[00:37:13 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471)
[00:37:13 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316)
[00:37:13 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[00:37:13 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[00:37:14 WARN]: net.advancedplugins.ae.impl.utils.nbt.backend.NbtApiException: Method not loaded! 'ITEMSTACK_SET_GLINT_OVERRIDE'
[00:37:14 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.impl.utils.nbt.backend.ReflectionMethod.run(ReflectionMethod.java:307)
[00:37:14 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.impl.utils.ASManager.makeItemGlow(ASManager.java:1720)
[00:37:14 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.impl.utils.ASManager.makeItemGlow(ASManager.java:1731)
[00:37:14 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.impl.utils.items.ItemBuilder.toItemStack(ItemBuilder.java:451)
[00:37:14 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.items.item.BlackScroll.build(BlackScroll.java:38)
[00:37:14 WARN]:        at AdvancedEnchantments-9.12.2.jar//net.advancedplugins.ae.items.AEItem.onInventoryClick(AEItem.java:112)
[00:37:14 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1908.execute(Unknown Source)
[00:37:14 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[00:37:14 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[00:37:14 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[00:37:14 WARN]:        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[00:37:14 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
[00:37:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
[00:37:14 WARN]:        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3224)
[00:37:14 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69)
[00:37:14 WARN]:        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33)
[00:37:14 WARN]:        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56)
[00:37:14 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[00:37:14 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151)
[00:37:14 WARN]:        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24)
[00:37:14 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535)
[00:37:14 WARN]:        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201)
[00:37:14 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125)
[00:37:14 WARN]:        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512)
[00:37:14 WARN]:        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505)
[00:37:14 WARN]:        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135)
[00:37:14 WARN]:        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464)
[00:37:14 WARN]:        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471)
[00:37:14 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316)
[00:37:14 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329)
[00:37:14 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)

### How to reproduce

This error is reproduced when I click into DeluxeMenus. Like any button at all...

### "/ae plinfo" link

https://paste.md-5.net/uzaqonoxex

**Comment by GC-spigot** [comment]
Solved next update
