### ISSUE TITLE
error in console [latest]

### ISSUE THREAD

**Issue by GG-MD** [GC-spigot/AdvancedEnchantments#4763]
### Describe the bug

```
[04:19:13 ERROR]: Could not pass event PlayerInteractEvent to AdvancedEnchantments v9.14.3
java.lang.NullPointerException: Cannot invoke "net.advancedplugins.ae.impl.effects.armorutils.ArmorType.get(org.bukkit.entity.LivingEntity)" because "<local6>" is null
        at AdvancedEnchantments-9.14.3.jar/net.advancedplugins.ae.impl.effects.armorutils.ArmorListener.playerInteractEvent(ArmorListener.java:314) ~[AdvancedEnchantments-9.14.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor701.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:71) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:629) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:538) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:2026) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:55) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1572) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:189) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1491) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1501) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1345) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.1.jar:1.21.1-DEV-d6b323a]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

### How to reproduce

unknown

### "/ae plinfo" link

https://paste.md-5.net/gasezajaku

### Filled out form correct and using latest version

I confirm

**Comment by GG-MD** [comment]
@GC-spigot

**Comment by GG-MD** [comment]
@GC-spigot

**Comment by GC-spigot** [comment]
Solved
