### ISSUE TITLE
5.6.6 error

### ISSUE THREAD

**Issue by p82183645** [GC-spigot/AdvancedEnchantments#478]
`[15:10:32 ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v5.6.6
java.lang.NullPointerException: null
        at n3kas.ae.utils.AECooldown.a(AECooldown.java:17) ~[?:?]
        at n3kas.ae.enchanthandler.effectsreader.EnchantsReader.b(EnchantsReader.java:155) ~[?:?]
        at n3kas.ae.enchanthandler.enchanttypes.DEFENSE_MOB.a(DEFENSE_MOB.java:49) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1177.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-624]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:104) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:834) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:733) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:866) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity0(EntityLiving.java:1520) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity0(EntityHuman.java:905) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityLiving.damageEntity(EntityLiving.java:993) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityHuman.damageEntity(EntityHuman.java:818) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityPlayer.damageEntity(EntityPlayer.java:704) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityInsentient.B(EntityInsentient.java:1248) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityZombie.B(EntityZombie.java:316) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PathfinderGoalMeleeAttack.a(SourceFile:124) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PathfinderGoalMeleeAttack.e(SourceFile:116) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PathfinderGoalZombieAttack.e(SourceFile:28) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:108) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityInsentient.doTick(EntityInsentient.java:686) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityLiving.movementTick(EntityLiving.java:2338) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityInsentient.movementTick(EntityInsentient.java:524) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityMonster.movementTick(EntityMonster.java:24) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityZombie.movementTick(EntityZombie.java:212) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityLiving.tick(EntityLiving.java:2135) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityInsentient.tick(EntityInsentient.java:261) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityMonster.tick(EntityMonster.java:28) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.EntityZombie.tick(EntityZombie.java:186) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1562) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.World.g(World.java:1529) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1340) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:599) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1107) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

**Comment by GC-spigot** [comment]
Not full error, find first error in logs or send latest.log via discord

**Comment by GC-spigot** [comment]
Fixed
