### ISSUE TITLE
ERROR: MESSAGE IN CONSOLE

### ISSUE THREAD

**Issue by croderdai** [GC-spigot/AdvancedEnchantments#500]
[13:51:49] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v5.6.6
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:93) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:578) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:483) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:610) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity0(EntityLiving.java:1330) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity0(EntityHuman.java:871) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityLiving.damageEntity(EntityLiving.java:872) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityHuman.damageEntity(EntityHuman.java:789) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityPlayer.damageEntity(EntityPlayer.java:531) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityMonster.B(EntityMonster.java:68) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityBlaze$PathfinderGoalBlazeFireball.e(SourceFile:221) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.PathfinderGoalSelector.a(SourceFile:129) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityInsentient.doTick(EntityInsentient.java:665) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityLiving.n(EntityLiving.java:2056) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityInsentient.n(EntityInsentient.java:502) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityMonster.n(EntityMonster.java:24) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityBlaze.n(SourceFile:124) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityLiving.A_(EntityLiving.java:1916) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityInsentient.A_(EntityInsentient.java:245) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.EntityMonster.A_(EntityMonster.java:28) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1740) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.World.h(World.java:1715) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1532) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:621) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:907) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:763) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:661) [PaperSpigot-1.11.2-b1104.jar:git-Paper-1104]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException

**Comment by GC-spigot** [comment]
Not a full error stacktrace! You need to find first error of "Could not pass event EntityDamageByEntityEvent to AdvancedEnchantments v5.6.6" in latest.log and post it
