### ISSUE TITLE
AE not working (Red In Plugin List)

### ISSUE THREAD

**Issue by RainDropped** [GC-spigot/AdvancedEnchantments#525]
[00:08:52] [Server thread/INFO]: [AdvancedEnchantments] Enabling AdvancedEnchantments v5.7.1
[00:08:53] [Server thread/INFO]: [AdvancedEnchantments] NoCheatPlus support has been enabled.
[00:08:53] [Server thread/ERROR]: Error occurred while enabling AdvancedEnchantments v5.7.1 (Is it up to date?)
java.lang.IllegalArgumentException: No enum constant n3kas.ae.api.AEnchantmentType.KILL MOB
	at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_212]
	at n3kas.ae.api.AEnchantmentType.valueOf(AEnchantmentType.java:1) ~[?:?]
	at n3kas.ae.enchanthandler.enchantments.AEnchants.a(AEnchants.java:96) ~[?:?]
	at n3kas.ae.enchanthandler.enchantments.AEnchantmentSorting.a(AEnchantmentSorting.java:10) ~[?:?]
	at n3kas.ae.Core.onEnable(Core.java:305) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[paper-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [paper-1.8.8.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[00:08:53] [Server thread/INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v5.7.1
[00:08:53] [Server thread/INFO]: [NoamsSouls] Enabling NoamsSouls v1.0.5
[00:08:53] [Server thread/ERROR]: [NoamsSouls] Plugin NoamsSouls v1.0.5 has failed to register events for class gc.soulsaddon.listeners.SoulAttemptEvent because n3kas/ae/api/SoulUseEvent does not exist.
[00:08:53] [Server thread/ERROR]: [NoamsSouls] Plugin NoamsSouls v1.0.5 has failed to register events for class gc.soulsaddon.listeners.SoulApplying because n3kas/ae/api/SoulApplyEvent does not exist.
[00:08:53] [Server thread/INFO]: [SilkSpawners] Enabling SilkSpawners v5.0.2
[00:08:53] [Server thread/INFO]: [SilkSpawners] WorldGuard was found and support is enabled
[00:08:53] [Server thread/INFO]: [SilkSpawners] Loading support for v1_8_R3
[00:08:53] [Server thread/INFO]: [SilkSpawners] AutoUpdater is enabled.
[00:08:53] [Server thread/INFO]: [SilkSpawners] Result from AutoUpdater is: NO_UPDATE
[00:08:53] [Server thread/INFO]: [SilkSpawners] BarAPI is disabled due to config setting.
[00:08:53] [Server thread/INFO]: [AEBooksDupeAddon] Enabling AEBooksDupeAddon v1.0.0
[00:08:53] [Server thread/INFO]: [EliteArmor] Enabling EliteArmor v5.0.7
[00:08:53] [Server thread/INFO]: -----------------------------------------------------------
[00:08:53] [Server thread/INFO]: EliteArmor: Version: 5.0.7
[00:08:53] [Server thread/INFO]: Factions: ENABLED
[00:08:53] [Server thread/INFO]: PlaceholderAPI: ENABLED
[00:08:53] [Server thread/INFO]: AdvancedEnchantments: DISABLED
[00:08:53] [Server thread/INFO]: -----------------------------------------------------------

**Comment by RainDropped** [comment]
fixed
