### ISSUE TITLE
Console errors 

### ISSUE THREAD

**Issue by MrPungle** [GC-spigot/AdvancedEnchantments#552]
I have a console error that appears on my server (with the 100% default config of AE, on a 1.12.2 server & with the latest build available on spigot
Seems not to be gamebreaking because the plugin is working fine, but this error is weird

`[06:46:13 INFO]: AdvancedEnchantments caught an error with an action involving inventories
[06:46:13 WARN]: java.lang.NullPointerException
[06:46:13 WARN]:        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324)
[06:46:13 WARN]:        at n3kas.ae.features.enchanter.InventoryEvent.a(InventoryEvent.java:25)
[06:46:13 WARN]:        at n3kas.ae.features.enchanter.InventoryEvent.a(InventoryEvent.java:46)
[06:46:13 WARN]:        at n3kas.ae.globallisteners.InventoryClicks.a(InventoryClicks.java:26)
[06:46:13 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor740.execute(Unknown Source)
[06:46:13 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[06:46:13 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[06:46:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[06:46:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2158)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[06:46:13 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[06:46:13 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[06:46:13 WARN]:        at java.lang.Thread.run(Unknown Source)
[06:46:13 INFO]: AdvancedEnchantments caught an error with an action involving inventories
[06:46:13 WARN]: java.lang.NullPointerException
[06:46:13 WARN]:        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:324)
[06:46:13 WARN]:        at n3kas.ae.features.enchanter.InventoryEvent.a(InventoryEvent.java:25)
[06:46:13 WARN]:        at n3kas.ae.features.enchanter.InventoryEvent.a(InventoryEvent.java:46)
[06:46:13 WARN]:        at n3kas.ae.globallisteners.InventoryClicks.a(InventoryClicks.java:26)
[06:46:13 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor740.execute(Unknown Source)
[06:46:13 WARN]:        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70)
[06:46:13 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[06:46:13 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[06:46:13 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2158)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:23)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInSetCreativeSlot.a(SourceFile:9)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[06:46:13 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[06:46:13 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[06:46:13 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[06:46:13 WARN]:        at java.lang.Thread.run(Unknown Source)`

If you know why I go that ^^

**Comment by GC-spigot** [comment]
Seems like your enchanter inventory name is missing
