### ISSUE TITLE
Excessive velocity set detected

### ISSUE THREAD

**Issue by clarkkentz** [GC-spigot/AdvancedEnchantments#561]
[10:40:30 WARN]: Excessive velocity set detected: tried to set velocity of entity #3598336 to (0.0,30.0,0.0).
[10:40:30 WARN]: java.lang.Exception: Stack trace
[10:40:30 WARN]:        at java.lang.Thread.dumpStack(Unknown Source)
[10:40:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.entity.CraftEntity.setVelocity(CraftEntity.java:213)
[10:40:30 WARN]:        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.g(RunnableEffect.java:598)
[10:40:30 WARN]:        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.e(RunnableEffect.java:104)
[10:40:30 WARN]:        at n3kas.ae.enchanthandler.ProcessEnchantment.a(ProcessEnchantment.java:240)
[10:40:30 WARN]:        at n3kas.ae.enchanthandler.ProcessEnchantment.c(ProcessEnchantment.java:120)
[10:40:30 WARN]:        at n3kas.ae.enchanthandler.enchanttypes.DEFENSE.a(DEFENSE.java:58)
[10:40:30 WARN]:        at sun.reflect.GeneratedMethodAccessor799.invoke(Unknown Source)
[10:40:30 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:40:30 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[10:40:30 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
[10:40:30 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78)
[10:40:30 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[10:40:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501)
[10:40:30 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486)
[10:40:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87)
[10:40:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553)
[10:40:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466)
[10:40:30 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1112)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.EntityHuman.d(EntityHuman.java:860)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:748)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.EntityHuman.damageEntity(EntityHuman.java:801)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.EntityPlayer.damageEntity(EntityPlayer.java:504)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1382)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[10:40:30 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[10:40:30 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713)
[10:40:30 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616)
[10:40:30 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by GC-spigot** [comment]
Fixed (you need to change rocketescape BOOST values to lower to fix this)
