### ISSUE TITLE
Could not pass event EntityDeathEvent

### ISSUE THREAD

**Issue by clarkkentz** [GC-spigot/AdvancedEnchantments#565]
[12:12:33 ERROR]: Could not pass event EntityDeathEvent to AdvancedEnchantments v5.8.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:378) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityLiving.die(EntityLiving.java:884) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityZombie.die(EntityZombie.java:561) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:822) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityZombie.damageEntity(EntityZombie.java:167) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityHuman.attack(EntityHuman.java:1002) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.EntityPlayer.attack(EntityPlayer.java:1086) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1382) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:52) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PacketPlayInUseEntity.a(SourceFile:11) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchFieldError: wildStackerAPI
        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.run(RunnableEffect.java:832) ~[?:?]
        at n3kas.ae.enchanthandler.effectsreader.RunnableEffect.init(RunnableEffect.java:104) ~[?:?]
        at n3kas.ae.enchanthandler.ProcessEnchantment.run(ProcessEnchantment.java:240) ~[?:?]
        at n3kas.ae.enchanthandler.ProcessEnchantment.init(ProcessEnchantment.java:120) ~[?:?]
        at n3kas.ae.enchanthandler.enchanttypes.KILL_MOB.onMobDeath(KILL_MOB.java:44) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor790.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        ... 24 more

**Comment by GC-spigot** [comment]
Fixed, thanks for reporting
