### ISSUE TITLE
Plugin not wokring

### ISSUE THREAD

**Issue by PoTatoAPX** [GC-spigot/AdvancedEnchantments#569]
So I bought the plugin and put it into the plugins folder and its green but none of the commands works here is the error it's giving in the console, the server is running 1.14.3 spigot

`[22:04:39] [Server thread/ERROR]: Error occurred while enabling AdvancedEnchantments v5.8.4 (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/permission/Permission
	at n3kas.ae.Core.setupPermissions(Core.java:564) ~[?:?]
	at n3kas.ae.Core.onEnable(Core.java:478) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:416) [spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:439) [spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:258) [spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:764) [spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.permission.Permission
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot.jar:git-Spigot-d05d3c1-604c8bf]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	... 11 more
[22:04:39] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it`

**Comment by digital-r** [comment]
Do You have Vault plugin installed? Seems like no Vault is found, or incompatible Vault version...

**Comment by PoTatoAPX** [comment]
Ahh, that will be the issue then no vault, Ill give that a go
