### ISSUE TITLE
[Bug] Advanced Enchantments error on startup

### ISSUE THREAD

**Issue by Aeyori** [GC-spigot/AdvancedEnchantments#586]
I can't run the plugin and I get this error on startup
`[20:44:55 WARN]: [AdvancedEnchantments] Plugin AdvancedEnchantments v5.8.5 generated an exception while executing task 111
java.lang.NoClassDefFoundError: org/fusesource/jansi/Ansi
        at n3kas.ae.Core.retest(Core.java:673) ~[?:?]
        at n3kas.ae.Core$3.run(Core.java:543) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-132]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.3.jar:git-Paper-132]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.3.jar:git-Paper-132]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_201]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.Ansi
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.3.jar:git-Paper-132]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.3.jar:git-Paper-132]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_201]
        ... 8 more`

**Comment by GC-spigot** [comment]
This issue is insignificant and does not affect the plugin in any way. If you're having actual issues ask for help on Discord server or PM me.

**Comment by Aeyori** [comment]
Okay, I was just worried cause it looked significant. I'll let you know if anything goes wrong then!
