### ISSUE TITLE
AdvancedEnchantments disabling itself after checking the market

### ISSUE THREAD

**Issue by kidZDragoon** [GC-spigot/AdvancedEnchantments#606]
Using paperspigot 1.14.4 build 147

Logs:
```
[16:00:00 INFO]: [AdvancedEnchantments] Cached 15 enchantments from Market.
[16:00:00 WARN]: java.net.UnknownHostException: n3.fyi
[16:00:00 WARN]:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[16:00:00 WARN]:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[16:00:00 WARN]:        at java.net.Socket.connect(Socket.java:589)
[16:00:00 WARN]:        at java.net.Socket.connect(Socket.java:538)
[16:00:00 WARN]:        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[16:00:00 WARN]:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[16:00:00 WARN]:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[16:00:00 WARN]:        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[16:00:00 WARN]:        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
[16:00:00 WARN]:        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
[16:00:00 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
[16:00:00 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
[16:00:00 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
[16:00:00 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
[16:00:00 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[16:00:00 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[16:00:00 WARN]:        at n3kas.ae.Core.retest(Core.java:651)
[16:00:00 WARN]:        at n3kas.ae.Core$3.run(Core.java:542)
[16:00:00 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[16:00:00 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[16:00:00 WARN]:        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[16:00:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[16:00:00 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[16:00:00 WARN]:        at java.lang.Thread.run(Thread.java:748)
[16:00:00 WARN]: [AdvancedEnchantments] Could not initialise plugin, contact developer with code 122
[16:00:00 INFO]: [AdvancedEnchantments] Disabling AdvancedEnchantments v5.8.9
```

Plugins (19): AdvancedEnchantments*, CoreProtect, Essentials, EssentialsChat, EssentialsSpawn, IPWhitelist*, LuckPerms, MMOItems, Multiverse-Core, RealPing*, ShopGUIPlus, Skript, Towny, TownyChat, TownyNameUpdater*, Vault, WorldEdit, WorldEditSelectionVisualizer, WorldGuard

**Comment by GC-spigot** [comment]
What is your Spigot username?

**Comment by kidZDragoon** [comment]
my spigot username: kidZDragoon

https://www.spigotmc.org/members/kidzdragoon.44719/

**Comment by GC-spigot** [comment]
Update
