### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xComboed** [GC-spigot/AdvancedEnchantments#669]
I Keep getting this error: (im using version spigot 1.8.8)

ERROR] Error occurred while enabling AdvancedEnchantments v6.1.2 (Is it up to date?)

java.lang.NoClassDefFoundError: net.milkbowl.vault.permission.Permission

at n3kas.ae.Core.setupPermissions(Core.java:583) ~[?:?]

at n3kas.ae.Core.onEnable(Core.java:496) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.permission.Permission

at java.net.URLClassLoader.findClass(URLClassLoader.java:591) ~[?:1.8.0_212]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]

at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:946) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:891) ~[?:1.8.0_212]

at java.lang.ClassLoader.loadClass(ClassLoader.java:874) ~[?:1.8.0_212]

... 13 more

**Comment by xComboed** [comment]
Sorry it was because i didnt have vault, its fixed now!
