### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by MatthewNoble** [GC-spigot/AdvancedEnchantments#680]
Can you help me with this error log please it happened when i clicked the inventory?
thnx

[latest.log](https://github.com/GC-spigot/AdvancedEnchantments/files/3670578/latest.log)

[12:04:25] [Server thread/INFO]: AdvancedEnchantments caught an error with an action involving inventories
[12:04:25] [Server thread/WARN]: java.lang.IllegalArgumentException: Cannot translate null text
[12:04:25] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
[12:04:25] [Server thread/WARN]: 	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354)
[12:04:25] [Server thread/WARN]: 	at n3kas.ae.features.enchanter.InventoryEvent.colour(InventoryEvent.java:25)
[12:04:25] [Server thread/WARN]: 	at n3kas.ae.features.enchanter.InventoryEvent.onClick(InventoryEvent.java:46)
[12:04:25] [Server thread/WARN]: 	at n3kas.ae.globallisteners.InventoryClicks.onInvClix(InventoryClicks.java:26)
[12:04:25] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:04:25] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[12:04:25] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[12:04:25] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[12:04:25] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316)
[12:04:25] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[12:04:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529)
[12:04:25] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2133)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:144)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:118)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:910)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:903)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:103)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:886)
[12:04:25] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:820)
[12:04:25] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by GC-spigot** [comment]
Fixed
