### ISSUE TITLE
1.15 Errors when trying to add enchants

### ISSUE THREAD

**Issue by QueenAslan** [GC-spigot/AdvancedEnchantments#736]
Hi,

I just bought the plugin. I have a clean install of 1.15 just added basic stuff like vault and cmi. I can see that AE has been successfully installed. There are no error starting up. 
But I get errors when I try to do stuff. When I do drag-drop onto an item with an AE book I get the following error:
`[13:48:27] [Server thread/ERROR]: Could not pass event InventoryClickEvent to AdvancedEnchantments v6.5.6
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-f39a89e-f777640]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-f39a89e-f777640]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-f39a89e-f777640]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-f39a89e-f777640]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2147) ~[spigot.jar:git-Spigot-f39a89e-f777640]`

Further when I try to do /ae enchant .... i get the following error:

`[14:00:20] [Server thread/INFO]: QueenAslan issued server command: /ae enchant glowing 1
[14:00:20] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ae' in plugin AdvancedEnchantments v6.5.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot.jar:git-Spigot-f39a89e-f777640]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot.jar:git-Spigot-f39a89e-f777640]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:711) ~[spigot.jar:git-Spigot-f39a89e-f777640]
	at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1657) ~[spigot.jar:git-Spigot-f39a89e-f777640]` 

I tried this with multiple enchants. I have checked in the config that I try to enchant on the right type of items.

I hope this is able to reproduce or that there is a logic explanation.

Thanks QueenAslan

**Comment by GC-spigot** [comment]
Fixed
