### ISSUE TITLE
Errors in console.

### ISSUE THREAD

**Issue by Puruuuu** [GC-spigot/AdvancedEnchantments#938]
[AdvancedEnchantments] Failed to show 'HAPPY_VILLAGER' particle

[10:46:37 INFO]: Failed to match 'venom' material, check your configuration or use materials.txt to find needed material.
[10:46:37 INFO]: Further information has been pasted to console...
[10:46:37 WARN]: java.lang.NullPointerException
[10:46:37 WARN]: at org.bukkit.craftbukkit.v1_15_R1.legacy.CraftLegacy.name(CraftLegacy.java:245)
[10:46:37 WARN]: at n3kas.ae.utils.AManager.matchMaterial(AManager.java:61)
[10:46:37 WARN]: at n3kas.ae.handlers.commands.AEGiveCommand.execute(AEGiveCommand.java:60)
[10:46:37 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:46:37 WARN]: at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015)
[10:46:37 WARN]: at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938)
[10:46:37 WARN]: at java.lang.Thread.run(Thread.java:748)

**Comment by GC-spigot** [comment]
1st error - some particle names are changed between versions, you'd need to replaceall of this name in configs to one that matches your version
2nd error - coming from wrong command arguments, material was put as 'venom' which is not an item in minecraft
